### ISSUE TITLE
Another hang when running out of registered memory

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#101]
This is related to, but different from, #2155 and #2157.

Steve Wise discovered a new and 23% more fun situation that can cause a deadlock when running out of registered memory (#2155 is potentially a problem in ob1).  In Steve's situation, if he runs IMB at ppn=2, all works fine.  If he runs at ppn=3, he hangs.  The bt for a hung process is really, really deep (see below).

What's happening is that the RDMA CM CPC is calling cpc_complete() in the upper layer to indicate that a new incoming connection has completed.  The upper layer calls FREE_LIST_WAIT to get some receive buffers.  In the depths of FREE_LIST_WAIT, we allocate the memory and then try to ibv_reg_mr() it (i.e., in mpool_rdma_module.c:register_cache_bypass() we call mpool_rdma->resources.register_mem(), which calls ibv_reg_mr).  If that fails, we return !=OMPI_SUCCESS, which then causes the mpool to block on a condition_wait.

We then call opal_progress(), which allows another RDMA CM incoming connection to complete and try to progress.  It, too, calls FREE_LIST_WAIT to try to get buffers, and fails in the same way (ibv_reg_mr() fails).  This can keep happening until no more incoming connections complete.

The recursion is not really the issue here -- the problem is that we call FREE_LIST_WAIT for buffers that may not be available, and therefore we block.  Yoinks.

I guess we need to add another state to _cpc_complete() such that if we can't get buffers immediately, keep the endpoint in the CONNECTING state and just try again next time.

Pasha -- is this handled better in ofacm, perchance?

Here's the bt of a hung process, just for giggles:

```
(gdb) bt
#0  internal driver call
#1  internal driver call
#2  0x00007fb6ebdaac13 in ibv_poll_cq (cq=0x6db770, num_entries=1, wc=0x7fff4b69faa0)
    at /usr/include/infiniband/verbs.h:934
#3  0x00007fb6ebdaaaa0 in poll_device (device=0x6a34a0, count=0)
    at btl_openib_component.c:3056
#4  0x00007fb6ebdab146 in progress_one_device (device=0x6a34a0)
    at btl_openib_component.c:3186
#5  0x00007fb6ebdab1ef in btl_openib_component_progress () at btl_openib_component.c:3211
#6  0x00007fb6ee939fdc in opal_progress () at runtime/opal_progress.c:207
#7  0x00007fb6ebdb0214 in opal_condition_wait (c=0x6b3218, m=0x6b31b0)
    at ../../../../opal/threads/condition.h:99
#8  0x00007fb6ebdaff0d in __ompi_free_list_wait (fl=0x6b30e8, item=0x7fff4b69fc68)
    at ../../../../ompi/class/ompi_free_list.h:263
#9  0x00007fb6ebdafc13 in post_recvs (ep=0x6ca900, qp=0, num_post=256)
    at btl_openib_endpoint.h:308
#10 0x00007fb6ebdaf9d4 in mca_btl_openib_endpoint_post_rr_nolock (ep=0x6ca900, qp=0)
    at btl_openib_endpoint.h:352
#11 0x00007fb6ebdaf7d3 in mca_btl_openib_endpoint_post_recvs (endpoint=0x6ca900)
    at btl_openib_endpoint.c:482
#12 0x00007fb6ebdb07a4 in mca_btl_openib_endpoint_cpc_complete (endpoint=0x6ca900)
    at btl_openib_endpoint.c:567
#13 0x00007fb6ebdcc1e0 in local_endpoint_cpc_complete (context=0x6ca900)
    at connect/btl_openib_connect_rdmacm.c:1073
#14 0x00007fb6ebdbcaaf in main_pipe_cmd_call_function (cmd=0x7fff4b69fdd0)
    at btl_openib_fd.c:328
#15 0x00007fb6ebdbd3bc in main_thread_event_callback (fd=10, opal_event=2, context=0x0)
#16 0x00007fb6ee95f08e in event_process_active (base=0x628510) at event.c:686
#17 0x00007fb6ee95f5e4 in opal_event_base_loop (base=0x628510, flags=2) at event.c:855
#18 0x00007fb6ee95f29f in opal_event_loop (flags=2) at event.c:766
#19 0x00007fb6ee939fb4 in opal_progress () at runtime/opal_progress.c:189
#20 0x00007fb6ebdb0214 in opal_condition_wait (c=0x6b3218, m=0x6b31b0)
    at ../../../../opal/threads/condition.h:99
#21 0x00007fb6ebdaff0d in __ompi_free_list_wait (fl=0x6b30e8, item=0x7fff4b69ff88)
    at ../../../../ompi/class/ompi_free_list.h:263
#22 0x00007fb6ebdafc13 in post_recvs (ep=0x6c9f80, qp=0, num_post=256)
    at btl_openib_endpoint.h:308
#23 0x00007fb6ebdaf9d4 in mca_btl_openib_endpoint_post_rr_nolock (ep=0x6c9f80, qp=0)
    at btl_openib_endpoint.h:352
#24 0x00007fb6ebdaf7d3 in mca_btl_openib_endpoint_post_recvs (endpoint=0x6c9f80)
    at btl_openib_endpoint.c:482
#25 0x00007fb6ebdb07a4 in mca_btl_openib_endpoint_cpc_complete (endpoint=0x6c9f80)
    at btl_openib_endpoint.c:567
#26 0x00007fb6ebdcc1e0 in local_endpoint_cpc_complete (context=0x6c9f80)
    at connect/btl_openib_connect_rdmacm.c:1073
#27 0x00007fb6ebdbcaaf in main_pipe_cmd_call_function (cmd=0x7fff4b6a00f0)
    at btl_openib_fd.c:328
#28 0x00007fb6ebdbd3bc in main_thread_event_callback (fd=10, opal_event=2, context=0x0)
    at btl_openib_fd.c:489
#29 0x00007fb6ee95f08e in event_process_active (base=0x628510) at event.c:686
#30 0x00007fb6ee95f5e4 in opal_event_base_loop (base=0x628510, flags=2) at event.c:855
#31 0x00007fb6ee95f29f in opal_event_loop (flags=2) at event.c:766
#32 0x00007fb6ee939fb4 in opal_progress () at runtime/opal_progress.c:189
#33 0x00007fb6ebdb0214 in opal_condition_wait (c=0x6b3218, m=0x6b31b0)
#34 0x00007fb6ebdaff0d in __ompi_free_list_wait (fl=0x6b30e8, item=0x7fff4b6a02a8)
    at ../../../../ompi/class/ompi_free_list.h:263
#35 0x00007fb6ebdafc13 in post_recvs (ep=0x6c9600, qp=0, num_post=256)
    at btl_openib_endpoint.h:308
#36 0x00007fb6ebdaf9d4 in mca_btl_openib_endpoint_post_rr_nolock (ep=0x6c9600, qp=0)
    at btl_openib_endpoint.h:352
#37 0x00007fb6ebdaf7d3 in mca_btl_openib_endpoint_post_recvs (endpoint=0x6c9600)
    at btl_openib_endpoint.c:482
#38 0x00007fb6ebdb07a4 in mca_btl_openib_endpoint_cpc_complete (endpoint=0x6c9600)
    at btl_openib_endpoint.c:567
#39 0x00007fb6ebdcc1e0 in local_endpoint_cpc_complete (context=0x6c9600)
    at connect/btl_openib_connect_rdmacm.c:1073
#40 0x00007fb6ebdbcaaf in main_pipe_cmd_call_function (cmd=0x7fff4b6a0410)
    at btl_openib_fd.c:328
#41 0x00007fb6ebdbd3bc in main_thread_event_callback (fd=10, opal_event=2, context=0x0)
    at btl_openib_fd.c:489
#42 0x00007fb6ee95f08e in event_process_active (base=0x628510) at event.c:686
#43 0x00007fb6ee95f5e4 in opal_event_base_loop (base=0x628510, flags=2) at event.c:855
#44 0x00007fb6ee95f29f in opal_event_loop (flags=2) at event.c:766
#45 0x00007fb6ee939fb4 in opal_progress () at runtime/opal_progress.c:189
#46 0x00007fb6ebdb0214 in opal_condition_wait (c=0x6b3218, m=0x6b31b0)
    at ../../../../opal/threads/condition.h:99
#47 0x00007fb6ebdaff0d in __ompi_free_list_wait (fl=0x6b30e8, item=0x7fff4b6a05c8)
    at ../../../../ompi/class/ompi_free_list.h:263
#48 0x00007fb6ebdafc13 in post_recvs (ep=0x6c8300, qp=0, num_post=256)
    at btl_openib_endpoint.h:308
#49 0x00007fb6ebdaf9d4 in mca_btl_openib_endpoint_post_rr_nolock (ep=0x6c8300, qp=0)
#50 0x00007fb6ebdaf7d3 in mca_btl_openib_endpoint_post_recvs (endpoint=0x6c8300)
    at btl_openib_endpoint.c:482
#51 0x00007fb6ebdb07a4 in mca_btl_openib_endpoint_cpc_complete (endpoint=0x6c8300)
    at btl_openib_endpoint.c:567
#52 0x00007fb6ebdcc1e0 in local_endpoint_cpc_complete (context=0x6c8300)
    at connect/btl_openib_connect_rdmacm.c:1073
#53 0x00007fb6ebdbcaaf in main_pipe_cmd_call_function (cmd=0x7fff4b6a0730)
    at btl_openib_fd.c:328
#54 0x00007fb6ebdbd3bc in main_thread_event_callback (fd=10, opal_event=2, context=0x0)
    at btl_openib_fd.c:489
#55 0x00007fb6ee95f08e in event_process_active (base=0x628510) at event.c:686
#56 0x00007fb6ee95f5e4 in opal_event_base_loop (base=0x628510, flags=2) at event.c:855
#57 0x00007fb6ee95f29f in opal_event_loop (flags=2) at event.c:766
#58 0x00007fb6ee939fb4 in opal_progress () at runtime/opal_progress.c:189
#59 0x00007fb6ec202226 in opal_condition_wait (c=0x7fb6ef1a53e0, m=0x7fb6ef1a5440)
    at ../../../../opal/threads/condition.h:99
#60 0x00007fb6ec20206b in ompi_request_wait_completion (req=0x6c6b00)
    at ../../../../ompi/request/request.h:377
#61 0x00007fb6ec201f54 in mca_pml_ob1_recv (addr=0x7fff4b6a0a0c, count=1,
    datatype=0x6100e0, src=3, tag=1000, comm=0x6116e0, status=0x7fff4b6a09e0)
    at pml_ob1_irecv.c:104
#62 0x00007fb6eeef6553 in PMPI_Recv (buf=0x7fff4b6a0a0c, count=1, type=0x6100e0, source=3,
    tag=1000, comm=0x6116e0, status=0x7fff4b6a09e0) at precv.c:78
#63 0x0000000000403d58 in IMB_init_communicator ()
#64 0x00000000004034c4 in main ()
```

**Comment by rhc54** [comment]
Per Mellanox, this can be closed. Any further work will be done on a separate new ticket.
