### ISSUE TITLE
MPI_LONG_DOUBLE causes MPI_ERR_ARG in MPI-IO on i386

### ISSUE THREAD

**Issue by drew-parsons** [open-mpi/ompi#10287]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

4.1.3

### Describe how Open MPI was installed)

Standard deb package from Debian unstable  (Debian package 4.1.3-2)
`apt-get install libopenmpi-dev`

### Please describe the system on which you are running

* Operating system/version:  Debian unstable (linux 4.19.235-1 (2022-03-17) i686 GNU/Linux)
* Computer hardware:  i686 chroot on amd64 hardware

-----------------------------

## Details of the problem

mpi4py tests exposed a bug in OpenMPI IO in i386 systems, reported at https://github.com/mpi4py/mpi4py/issues/105
(test logs available at https://ci.debian.net/packages/m/mpi4py/testing/i386/ )

The symptom is the error message
```
MPI_ERR_ARG: invalid argument of some other kind
```
e.g.
```
ERROR: testIReadIWrite (test_io.TestIOSelf)
testGetSetName (test_win.TestWinCreateSelf) ... ----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autopkgtest-lxc.y8ez2f_q/downtmp/build.FwK/src/test/test_io.py", line 124, in testIReadIWrite
    fh.Set_view(0, etype)
  File "mpi4py/MPI/File.pyx", line 215, in mpi4py.MPI.File.Set_view
mpi4py.MPI.Exception: MPI_ERR_ARG: invalid argument of some other kind
testGetSetInfo (test_win.TestWinCreateSelf) ... 
```
We tested that the error does not occur with mpich.

With further debugging the mpi4py author identified the problem arises from MPI_LONG_DOUBLE, triggering the error in `MPI_File_set_view()`.

The problem can be reproduced with the trivial test code
```
#include <mpi.h>

int main() {
  MPI_File fh;
  MPI_Init(NULL,NULL);
  MPI_File_set_errhandler(MPI_FILE_NULL,MPI_ERRORS_ARE_FATAL);
  MPI_File_open(MPI_COMM_WORLD, "/tmp/data", MPI_MODE_CREATE|MPI_MODE_WRONLY, MPI_INFO_NULL, &fh);
  MPI_File_set_size(fh, 0);
  MPI_File_set_view(fh, 0, MPI_FLOAT, MPI_FLOAT, "native", MPI_INFO_NULL);
  MPI_File_set_view(fh, 0, MPI_DOUBLE, MPI_DOUBLE, "native", MPI_INFO_NULL);
  MPI_File_set_view(fh, 0, MPI_LONG_DOUBLE, MPI_LONG_DOUBLE, "native", MPI_INFO_NULL);
  MPI_File_close(&fh);
  MPI_Finalize();
}
```

This small test reproduces the problem (which occurs even in single process execution):
```
$ mpicc -o testmpi testmpi.c
$ ./testmpi 
[barriere:09674] *** An error occurred in MPI_File_set_view
[barriere:09674] *** reported by process [1210187777,0]
[barriere:09674] *** on file /tmp/data
[barriere:09674] *** MPI_ERR_ARG: invalid argument of some other kind
[barriere:09674] *** MPI_ERRORS_ARE_FATAL (processes in this file will now abort,
[barriere:09674] ***    and potentially your MPI job)
```
If the `MPI_LONG_DOUBLE` line is commented out then the test code runs successfully.

**Comment by edgargabriel** [comment]
Am I assuming correctly that this is a 32bit platform? I tested on 64bit platforms (I don't really have access to 32bit platforms anymore) and I cannot reproduce the issue there. I would suspect that MPI_LONG_DOUBLE is simply not defined on that platform, but for this we would have to see the output of open mpi configure

**Comment by drew-parsons** [comment]
That's right, i386 (i686) is the old intel 32-bit architecture. But in general it knows how to handle 64-bit numbers.

Build logs for openmpi are found at  https://buildd.debian.org/status/logs.php?pkg=openmpi&arch=i386
most recent (4.1.3-2) is https://buildd.debian.org/status/fetch.php?pkg=openmpi&arch=i386&ver=4.1.3-2&stamp=1649668696&raw=0

The build logs don't seem to report MPI types directly. Logging in to an i386 chroot, I find `/usr/lib/i386-linux-gnu/openmpi/include/openmpi/ompi/datatype/ompi_datatype_internal.h` defines
```
#define OMPI_DATATYPE_MPI_DOUBLE                  0x0A
#define OMPI_DATATYPE_MPI_LONG_DOUBLE             0x0B
```
and `/usr/lib/i386-linux-gnu/openmpi/include/mpi.h` has
```
#define MPI_DOUBLE OMPI_PREDEFINED_GLOBAL(MPI_Datatype, ompi_mpi_double)
#define MPI_LONG_DOUBLE OMPI_PREDEFINED_GLOBAL(MPI_Datatype, ompi_mpi_long_double)
```
`ompi_mpi_long_double` is defined in libmpi.so (libmpi.so.40.30.3)
```
$ nm -D /usr/lib/i386-linux-gnu/libmpi.so | grep ompi_mpi_long_double
00129b20 D ompi_mpi_long_double
```

**Comment by edgargabriel** [comment]
it took me a while but I am now able to reproduce the issue, and I have fix ready. The problem is that the default file view that we use internally is not an exact multiple of the data type size (since long double on a 32 bit platform is 12bytes).
