### ISSUE TITLE
Deadlock in rcache code

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#109]
With threads enabled under some circumstances with enough simultaneous MPI_Send function calls the rcache code can cause a deadlock. The following backtrace is one example:

```


(gdb) bt
#0  0x000000808052bf80 in .__GI___libc_nanosleep () from /lib64/power6/libc.so.6
#1  0x000000808052bca4 in .__sleep () from /lib64/power6/libc.so.6
#2  0x00000400002b88d4 in show_stackframe (signo=6, info=0x4000449d0e8, p=0x4000449cb10) at ../../../opal/util/stacktrace.c:87
#3  <signal handler called>
#4  0x00000080804b25a4 in .raise () from /lib64/power6/libc.so.6
#5  0x00000080804b466c in .abort () from /lib64/power6/libc.so.6
#6  0x0000040000662c64 in opal_mutex_lock (m=0x100dd358) at ../../../../../opal/threads/mutex_unix.h:106
#7  0x00000400006649d0 in mca_mpool_rdma_release_memory (mpool=0x100dcf70, base=0x40009b90000, size=458752)
    at ../../../../../ompi/mca/mpool/rdma/mpool_rdma_module.c:433
#8  0x0000040000186f10 in mca_mpool_base_mem_cb (base=0x40009b90000, size=458752, cbdata=0x0, from_alloc=true)
    at ../../../../ompi/mca/mpool/base/mpool_base_mem_cb.c:68
#9  0x0000040000257810 in opal_mem_hooks_release_hook (buf=0x40009b90000, length=458752, from_alloc=true)
    at ../../opal/memoryhooks/memory.c:131
#10 0x00000400002c30f8 in opal_memory_linux_free_ptmalloc2_munmap (start=0x40009b90000, length=458752, from_alloc=1)
    at ../../../../../opal/mca/memory/linux/memory_linux_munmap.c:71
#11 0x00000400002c3ce8 in new_heap (size=196608, top_pad=131072) at ../../../../../opal/mca/memory/linux/arena.c:552
#12 0x00000400002c44c8 in opal_memory_ptmalloc2_int_new_arena (size=336) at ../../../../../opal/mca/memory/linux/arena.c:749
#13 0x00000400002c4374 in arena_get2 (a_tsd=0x40000398f20, size=336) at ../../../../../opal/mca/memory/linux/arena.c:714
#14 0x00000400002c7b30 in opal_memory_ptmalloc2_malloc (bytes=336) at ../../../../../opal/mca/memory/linux/malloc.c:3429
#15 0x00000400002c65f8 in opal_memory_linux_malloc_hook (sz=336, caller=0x400002ad9d0)
    at ../../../../../opal/mca/memory/linux/hooks.c:682
#16 0x00000080804fedfc in .__libc_malloc () from /lib64/power6/libc.so.6
#17 0x00000400002ad9d0 in opal_malloc (size=336, file=0x400006258c8 "../../../../../opal/class/opal_object.h", line=469)
    at ../../../opal/util/malloc.c:101
#18 0x0000040000624690 in opal_obj_new (cls=0x400006360a8) at ../../../../../opal/class/opal_object.h:469
#19 0x00000400006245e4 in opal_obj_new_debug (type=0x400006360a8, 
    file=0x40000625848 "../../../../../ompi/mca/rcache/vma/rcache_vma_tree.c", line=112) at ../../../../../opal/class/opal_object.h:251
#20 0x0000040000624850 in mca_rcache_vma_new (vma_rcache=0x100dd320, start=4398203011072, end=4398203338751)
    at ../../../../../ompi/mca/rcache/vma/rcache_vma_tree.c:112
#21 0x0000040000623edc in mca_rcache_vma_tree_insert (vma_rcache=0x100dd320, reg=0x100f1800, limit=0)
    at ../../../../../ompi/mca/rcache/vma/rcache_vma_tree.c:397
#22 0x00000400006223f4 in mca_rcache_vma_insert (rcache=0x100dd320, reg=0x100f1800, limit=0)
    at ../../../../../ompi/mca/rcache/vma/rcache_vma.c:120
#23 0x00000400006639e0 in mca_mpool_rdma_register (mpool=0x100dcf70, addr=0x40009540010, size=262144, flags=0, reg=0x4000449e3a8)
    at ../../../../../ompi/mca/mpool/rdma/mpool_rdma_module.c:256
#24 0x0000040000775094 in mca_pml_ob1_rdma_btls (bml_endpoint=0x10104e00, base=0x40009540010 "", size=262144, rdma_btls=0x10102b98)
    at ../../../../../ompi/mca/pml/ob1/pml_ob1_rdma.c:70
#25 0x00000400007720bc in mca_pml_ob1_send_request_start_btl (sendreq=0x10102880, bml_btl=0x10104f60)
    at ../../../../../ompi/mca/pml/ob1/pml_ob1_sendreq.h:383
#26 0x0000040000771cb0 in mca_pml_ob1_send_request_start (sendreq=0x10102880) at ../../../../../ompi/mca/pml/ob1/pml_ob1_sendreq.h:434
#27 0x0000040000772b04 in mca_pml_ob1_send (buf=0x40009540010, count=262144, datatype=0x40000334048, dst=1, tag=0, 
    sendmode=MCA_PML_BASE_SEND_STANDARD, comm=0x4000039a8f0) at ../../../../../ompi/mca/pml/ob1/pml_ob1_isend.c:119
#28 0x000004000013b9d0 in PMPI_Send (buf=0x40009540010, count=262144, type=0x40000334048, dest=1, tag=0, comm=0x4000039a8f0)
    at psend.c:75
#29 0x0000000010001188 in runfunc (foo=0x0) at bw_th.c:89
#30 0x000000808072bfc0 in .start_thread () from /lib64/power6/libpthread.so.0
#31 0x000000808056fb48 in .__clone () from /lib64/power6/libc.so.6
```

The problem in general is that the rcache code calls functions which can do memory allocation with the rcache lock held. Memory allocation can cause the rcache code to be called which then attempts to take the rcache lock causing a deadlock.

I've attached a patch which does fix the problem, although it is pretty ugly. It precreates in a cache vma structures which are need during an rcache insert (as the rcache lock is needed during this operation). Some logic has been added to handle when the cache is empty to back out of the rcache insert operation until a point where the thread can release the rcache lock, allocate more data structures into the cache, reacquire the rcache lock and then retry.

The patch probably needs a little bit of work - there are some hardcoded numbers for cache sizes which work well on the 64-way node test system. But larger numbers would probably work better for larger SMP systems.

I think this sort of approach is ok to get 1.4.3 more thread safe, but perhaps for the 1.5 branch a more extensive rewrite of the rcache code would be appropriate (especially given some of the other active bugs related to the rcache code).

**Comment by rhc54** [comment]
Per Mellanox, this can be closed. Any further work will be done on a separate new ticket.
