### ISSUE TITLE
5.0.0rc9 - segfault in `MPI_Init`

### ISSUE THREAD

**Issue by thomasgillis** [open-mpi/ompi#10986]
Thank you for taking the time to submit an issue!

## Background information

I have installed vanilla `ompi-5.0.0rc9` with `ofi-1.16.1` for an omnipath based machine (`bebop` @ ANL)
I am trying to run a small code to check rank binding and `MPI_Init()` segfaults.
As the machine is `omnipath` I have installed `ofi` only and no `ucx` is in the path.

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

- it's `ompi v5.0.0rc9` with `ofi-v1.16.1`. No `ucx` has been installed alongside `ofi`.

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

- both installed form tar

-----------------------------

## Details of the problem

```c
#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <omp.h>
#include <mpi.h>
#include <sched.h>

int main(int argc, char* argv[]){
    int provided;
    MPI_Init(&argc, &argv);

    // get the rank
    int rank;
    MPI_Comm_rank(MPI_COMM_WORLD,&rank);

    // get the proc name
    int  len;
    char procname[MPI_MAX_PROCESSOR_NAME];
    MPI_Get_processor_name(procname, &len);

    #pragma omp parallel
    {
        int thread_num = omp_get_thread_num();
        int cpu_num = sched_getcpu();
        printf("[rank %.3d] thread %.3d is running on CPU %d on node %s\n", rank, thread_num, cpu_num, procname);
    }

    MPI_Finalize();
    return 0;
}
```

using the `--cpus-per-rank` option to get two threads on each rank (in this case 2 ranks).
```
OMP_NUM_THREADS=2 mpiexec -n 2 --cpus-per-rank 2
```

The call to `MPI_Init` segfaults with the following backtrace:

```text
AddressSanitizer:DEADLYSIGNAL
=================================================================
==33566==ERROR: AddressSanitizer: SEGV on unknown address 0x2b8ed9602dde (pc 0x2b8ed983ffb2 bp 0x2b8ed9602dee sp 0x7ffe083c0c40 T0)
==33566==The signal is caused by a WRITE memory access.
AddressSanitizer:DEADLYSIGNAL
=================================================================
==33567==ERROR: AddressSanitizer: SEGV on unknown address 0x2b71400b6dde (pc 0x2b71402f3fb2 bp 0x2b71400b6dee sp 0x7ffd6119ea00 T0)
==33567==The signal is caused by a WRITE memory access.
    #0 0x2b8ed983ffb2 in bool __sanitizer::atomic_compare_exchange_strong<__sanitizer::atomic_uint8_t>(__sanitizer::atomic_uint8_t volatile*, __sanitizer::atomic_uint8_t::Type*, __sanitizer::atomic_uint8_t::Type, __sanitizer::memory_order) /home/spack/build/spack-stage-gcc-10.2.0-z53hda3sdrdaen3tk6oir3qg5vtre66p/spack-src/libsanitizer/sanitizer_common/sanitizer_atomic_clang.h:80
    #1 0x2b8ed983ffb2 in __asan::Allocator::AtomicallySetQuarantineFlagIfAllocated(__asan::AsanChunk*, void*, __sanitizer::BufferedStackTrace*) /home/spack/build/spack-stage-gcc-10.2.0-z53hda3sdrdaen3tk6oir3qg5vtre66p/spack-src/libsanitizer/asan/asan_allocator.cpp:570
    #2 0x2b8ed983ffb2 in __asan::Allocator::Deallocate(void*, unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType) /home/spack/build/spack-stage-gcc-10.2.0-z53hda3sdrdaen3tk6oir3qg5vtre66p/spack-src/libsanitizer/asan/asan_allocator.cpp:647
    #3 0x2b8ed983ffb2 in __asan::asan_free(void*, __sanitizer::BufferedStackTrace*, __asan::AllocType) /home/spack/build/spack-stage-gcc-10.2.0-z53hda3sdrdaen3tk6oir3qg5vtre66p/spack-src/libsanitizer/asan/asan_allocator.cpp:883
    #4 0x2b8ed98c1383 in __interceptor_free /home/spack/build/spack-stage-gcc-10.2.0-z53hda3sdrdaen3tk6oir3qg5vtre66p/spack-src/libsanitizer/asan/asan_malloc_linux.cpp:128
    #5 0x2b8edc123ad9 in mca_btl_ofi_component_init (/home/tgillis/lib-OMPI-5.0.0rc9-OFI-1.16.1/lib/libopen-pal.so.80+0xcead9)
    #6 0x2b8edc1015db in mca_btl_base_select (/home/tgillis/lib-OMPI-5.0.0rc9-OFI-1.16.1/lib/libopen-pal.so.80+0xac5db)
    #7 0x2b8eda4cead3 in mca_bml_r2_component_init (/home/tgillis/lib-OMPI-5.0.0rc9-OFI-1.16.1/lib/libmpi.so.80+0xedad3)
    #8 0x2b8eda4cccb2 in mca_bml_base_init (/home/tgillis/lib-OMPI-5.0.0rc9-OFI-1.16.1/lib/libmpi.so.80+0xebcb2)
    #9 0x2b8eda5ff4ff in mca_pml_ob1_component_init (/home/tgillis/lib-OMPI-5.0.0rc9-OFI-1.16.1/lib/libmpi.so.80+0x21e4ff)
    #10 0x2b8eda5fb9d4 in mca_pml_base_select (/home/tgillis/lib-OMPI-5.0.0rc9-OFI-1.16.1/lib/libmpi.so.80+0x21a9d4)
    #11 0x2b8eda47a8e0 in ompi_mpi_instance_init_common (/home/tgillis/lib-OMPI-5.0.0rc9-OFI-1.16.1/lib/libmpi.so.80+0x998e0)
    #12 0x2b8eda47b084 in ompi_mpi_instance_init (/home/tgillis/lib-OMPI-5.0.0rc9-OFI-1.16.1/lib/libmpi.so.80+0x9a084)
    #13 0x2b8eda46da51 in ompi_mpi_init (/home/tgillis/lib-OMPI-5.0.0rc9-OFI-1.16.1/lib/libmpi.so.80+0x8ca51)
    #14 0x2b8eda4a1d9e in PMPI_Init (/home/tgillis/lib-OMPI-5.0.0rc9-OFI-1.16.1/lib/libmpi.so.80+0xc0d9e)
    #15 0x400e4c in main src/thread_detect.c:15
```

Let me know if you need other information or if there is something I can try.
Thanks for your time

**Comment by thomasgillis** [comment]
EDIT: solved using the correct mca options referred [here](https://docs.open-mpi.org/en/main/networking/ofi.html#what-are-the-libfabric-ofi-components-in-open-mpi) `--mca pml cm --mca mtl ofi --mca mtl_ofi_provider_include psm2`.

sorry for the issue raised to quickly

**Comment by jsquyres** [comment]
@hppritcha @BrendanCunningham Do we really want to consider this issue closed?  

My $0.02: Users should not have to set specific MCA vars to avoid a segfault.

**Comment by hppritcha** [comment]
this looks interesting.  i'll see if i can reproduce on one of our hfi1 clusters.  going on the assumption gcc was used for compiling.

@thomasgillis could you rebuild with the

--enable-debug

configure option enabled?  This may give us more info in the traceback.

Also, which compiler are you using?

**Comment by thomasgillis** [comment]
sure let me try. Compiler is `gcc (Spack GCC) 10.2.0`

**Comment by thomasgillis** [comment]
I have just rebuilt `ompi` with
```
  Configure command line: '--prefix=/home/tgillis/lib-OMPI-5.0.0rc9-OFI-1.16.1-DBG'
                          '--without-verbs'
                          '--enable-mpirun-prefix-by-default'
                          '--with-cuda=no' '--enable-debug'
                          '--with-pmix=internal' '--with-hwloc=internal'
                          '--with-ofi=/home/tgillis/lib-OMPI-5.0.0rc9-OFI-1.16.1-DBG'
```

and the backtrace is very similar
```bash
[beboplogin1:10541] *** Process received signal ***
[beboplogin1:10541] Signal: Aborted (6)
[beboplogin1:10541] Signal code:  (-6)
[beboplogin1:10541] [ 0] /lib64/libpthread.so.0(+0xf630)[0x2afff987c630]
[beboplogin1:10541] [ 1] /lib64/libc.so.6(gsignal+0x37)[0x2afff9abf387]
[beboplogin1:10541] [ 2] /lib64/libc.so.6(abort+0x148)[0x2afff9ac0a78]
[beboplogin1:10541] [ 3] /lib64/libc.so.6(+0x78f67)[0x2afff9b01f67]
[beboplogin1:10541] [ 4] /lib64/libc.so.6(+0x81329)[0x2afff9b0a329]
[beboplogin1:10541] [ 5] /home/tgillis/lib-OMPI-5.0.0rc9-OFI-1.16.1-DBG/lib/libopen-pal.so.80(+0xeaf3f)[0x2afffa157f3f]
[beboplogin1:10541] [ 6] /home/tgillis/lib-OMPI-5.0.0rc9-OFI-1.16.1-DBG/lib/libopen-pal.so.80(+0xe9ca5)[0x2afffa156ca5]
[beboplogin1:10541] [ 7] /home/tgillis/lib-OMPI-5.0.0rc9-OFI-1.16.1-DBG/lib/libopen-pal.so.80(mca_btl_base_select+0x201)[0x2afffa11d228]
[beboplogin1:10541] [ 8] /home/tgillis/lib-OMPI-5.0.0rc9-OFI-1.16.1-DBG/lib/libmpi.so.80(mca_bml_r2_component_init+0x29)[0x2afff9043a1f]
[beboplogin1:10541] [ 9] /home/tgillis/lib-OMPI-5.0.0rc9-OFI-1.16.1-DBG/lib/libmpi.so.80(mca_bml_base_init+0xfe)[0x2afff90408e7]
[beboplogin1:10541] [10] /home/tgillis/lib-OMPI-5.0.0rc9-OFI-1.16.1-DBG/lib/libmpi.so.80(+0x36f575)[0x2afff924c575]
[beboplogin1:10541] [11] /home/tgillis/lib-OMPI-5.0.0rc9-OFI-1.16.1-DBG/lib/libmpi.so.80(mca_pml_base_select+0x2c6)[0x2afff92452ee]
[beboplogin1:10541] [12] /home/tgillis/lib-OMPI-5.0.0rc9-OFI-1.16.1-DBG/lib/libmpi.so.80(+0xb6060)[0x2afff8f93060]
[beboplogin1:10541] [13] /home/tgillis/lib-OMPI-5.0.0rc9-OFI-1.16.1-DBG/lib/libmpi.so.80(ompi_mpi_instance_init+0x5e)[0x2afff8f939f5]
[beboplogin1:10541] [14] /home/tgillis/lib-OMPI-5.0.0rc9-OFI-1.16.1-DBG/lib/libmpi.so.80(ompi_mpi_init+0x1ae)[0x2afff8f82f9c]
[beboplogin1:10541] [15] /home/tgillis/lib-OMPI-5.0.0rc9-OFI-1.16.1-DBG/lib/libmpi.so.80(MPI_Init+0x7f)[0x2afff8fe83af]
[beboplogin1:10541] [16] ./a.out[0x400863]
[beboplogin1:10541] [17] /lib64/libc.so.6(__libc_start_main+0xf5)[0x2afff9aab555]
[beboplogin1:10541] [18] ./a.out[0x400789]
[beboplogin1:10541] *** End of error message ***
*** Error in `./a.out': free(): invalid size: 0x00007ffedc804b80 ***
```

Here is also the `ldd` of my `libmpi.so`:
```bash
ldd /home/tgillis/lib-OMPI-5.0.0rc9-OFI-1.16.1-DBG/lib/libmpi.so
	linux-vdso.so.1 =>  (0x00007fffc4fb6000)
	libgpfs.so => /lib64/libgpfs.so (0x00002b9df5c70000)
	libopen-pal.so.80 => /home/tgillis/lib-OMPI-5.0.0rc9-OFI-1.16.1-DBG/lib/libopen-pal.so.80 (0x00002b9df5e86000)
	libfabric.so.1 => /home/tgillis/lib-OMPI-5.0.0rc9-OFI-1.16.1-DBG/lib/libfabric.so.1 (0x00002b9df61fb000)
	librdmacm.so.1 => /lib64/librdmacm.so.1 (0x00002b9df653f000)
	libibverbs.so.1 => /lib64/libibverbs.so.1 (0x00002b9df6756000)
	libpsm2.so.2 => /lib64/libpsm2.so.2 (0x00002b9df696f000)
	libatomic.so.1 => /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-6.5.0/gcc-10.2.0-z53hda3/lib64/libatomic.so.1 (0x00002b9df6c03000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b9df6e0b000)
	librt.so.1 => /lib64/librt.so.1 (0x00002b9df7027000)
	libpmix.so.2 => /home/tgillis/lib-OMPI-5.0.0rc9-OFI-1.16.1-DBG/lib/libpmix.so.2 (0x00002b9df722f000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00002b9df7747000)
	libevent_core-2.1.so.7 => /home/tgillis/lib-OMPI-5.0.0rc9-OFI-1.16.1-DBG/lib/libevent_core-2.1.so.7 (0x00002b9df794a000)
	libevent_pthreads-2.1.so.7 => /home/tgillis/lib-OMPI-5.0.0rc9-OFI-1.16.1-DBG/lib/libevent_pthreads-2.1.so.7 (0x00002b9df7b7f000)
	libhwloc.so.15 => /home/tgillis/lib-OMPI-5.0.0rc9-OFI-1.16.1-DBG/lib/libhwloc.so.15 (0x00002b9df7d82000)
	libm.so.6 => /lib64/libm.so.6 (0x00002b9df7fdc000)
	libudev.so.1 => /lib64/libudev.so.1 (0x00002b9df82de000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00002b9df84f4000)
	libc.so.6 => /lib64/libc.so.6 (0x00002b9df86f8000)
	/lib64/ld-linux-x86-64.so.2 (0x00002b9df52fa000)
	libnl-route-3.so.200 => /lib64/libnl-route-3.so.200 (0x00002b9df8ac6000)
	libnl-3.so.200 => /lib64/libnl-3.so.200 (0x00002b9df8d33000)
	libnuma.so.1 => /lib64/libnuma.so.1 (0x00002b9df8f54000)
	libgcc_s.so.1 => /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-6.5.0/gcc-10.2.0-z53hda3/lib64/libgcc_s.so.1 (0x00002b9df9160000)
	libcap.so.2 => /lib64/libcap.so.2 (0x00002b9df9378000)
	libdw.so.1 => /lib64/libdw.so.1 (0x00002b9df957d000)
	libattr.so.1 => /lib64/libattr.so.1 (0x00002b9df97ce000)
	libelf.so.1 => /lib64/libelf.so.1 (0x00002b9df99d3000)
	libz.so.1 => /lib64/libz.so.1 (0x00002b9df9beb000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00002b9df9e01000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00002b9dfa027000)
```

**Comment by hppritcha** [comment]
i was able to reproduce this problem i think.

**Comment by BrendanCunningham** [comment]
> @hppritcha @BrendanCunningham Do we really want to consider this issue closed?
> 
> My $0.02: Users should not have to set specific MCA vars to avoid a segfault.

Sorry, just seeing this now. No, user shouldn't have to set MCA to avoid segfault.
