### ISSUE TITLE
ompi_comm_set segfaults when connect/accept called > 64 times

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#113]
Several users have reported that ompi_comm_set segfaults when attempting to connect/accept across more than 64 independent jobs. I found one place in ompi_dpm_base_mark_dyncomm where an array size had been hard-coded to 64 and fixed that, but it apparently doesn't solve the problem.

Here is one backtrace from such a report:

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xf7e4c6c0 (LWP 20246)]
0xf7f39905 in ompi_comm_set () from /home/gmaj/openmpi/lib/libmpi.so.0

(gdb) bt
#0  0xf7f39905 in ompi_comm_set () from /home/gmaj/openmpi/lib/libmpi.so.0
#1  0xf7e3ba95 in connect_accept () from
/home/gmaj/openmpi/lib/openmpi/mca_dpm_orte.so
#2  0xf7f62013 in PMPI_Comm_connect () from /home/gmaj/openmpi/lib/libmpi.so.0
#3  0x080489ed in main (argc=825832753, argv=0x34393638) at client.c:43

What's more: when I've added a breakpoint on ompi_comm_set in 66th
process and stepped a couple of instructions, one of the other
processes crashed (as usualy on ompi_comm_set) earlier than 66th did.

Finally I decided to recompile openmpi using -g flag for gcc. In this
case the 66 processes issue has gone! I was running my applications
exactly the same way as previously (even without recompilation) and
I've run successfully over 130 processes.
When switching back to the openmpi compilation without -g it again segfaults.

```

Note the last section - apparently, this only happens for optimized builds, which makes it sound like some kind of race condition.

This defect is found in 1.4 and the trunk, and probably in 1.5 (though not confirmed).

**Comment by rhc54** [comment]
No longer valid - fixed
