### ISSUE TITLE
openmpi-5.0.0rc10 build fails for PMIx python bindings

### ISSUE THREAD

**Issue by naughtont3** [open-mpi/ompi#11394]
The current openmpi-5.0.0rc10 tarball fails to build PMIx python bindings  (`--enable-python-bindings`).

note: this is a regression as previously this built and likely just a sync issue with upstream openmpix/prrte as the python bindings build on main there.

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

- openmpi-5.0.0rc10 tarball

### Please describe the system on which you are running

* Operating system/version: linux
* Computer hardware: x86-64
* Network type:

-----------------------------

## Details of the problem

Typical build adding `--enable-python-bindings` configure option to build PMIx python bindings.

```shell
./configure \
   --enable-python-bindings \
   --enable-mpirun-prefix-by-default \
    --prefix=$PWD/_install \
&& make && make install

 ...<snip>...

make[5]: Entering directory '/ssd/tjn/scratch/ompi-scratch/ANNOYED-TAPIR/openmpi-5.0.0rc10/build-dbg/3rd-party/openpmix/bindings/python'
ln -s /home/3t4/projects/ompi/scratch-ssd/ANNOYED-TAPIR/openmpi-5.0.0rc10/3rd-party/openpmix/bindings/python/pmix.pxi /home/3t4/projects/ompi/scratch-ssd/ANNOYED-TAPIR/openmpi-5.0.0rc10/build-dbg/3rd-party/openpmix/bindings/python/pmix.pxi
ln -s /home/3t4/projects/ompi/scratch-ssd/ANNOYED-TAPIR/openmpi-5.0.0rc10/3rd-party/openpmix/bindings/python/pmix.pyx /home/3t4/projects/ompi/scratch-ssd/ANNOYED-TAPIR/openmpi-5.0.0rc10/build-dbg/3rd-party/openpmix/bindings/python/pmix.pyx
PMIX_BINDINGS_TOP_SRCDIR=/home/3t4/projects/ompi/scratch-ssd/ANNOYED-TAPIR/openmpi-5.0.0rc10/3rd-party/openpmix PMIX_BINDINGS_TOP_BUILDDIR=/home/3t4/projects/ompi/scratch-ssd/ANNOYED-TAPIR/openmpi-5.0.0rc10/build-dbg/3rd-party/openpmix \
	/usr/bin/python3 ../../../../../3rd-party/openpmix/bindings/python/setup.py build_ext --library-dirs="/home/3t4/projects/ompi/scratch-ssd/ANNOYED-TAPIR/openmpi-5.0.0rc10/build-dbg/3rd-party/openpmix/src/.libs" --user
Compiling /home/3t4/projects/ompi/scratch-ssd/ANNOYED-TAPIR/openmpi-5.0.0rc10/build-dbg/3rd-party/openpmix/bindings/python/pmix.pyx because it changed.
[1/1] Cythonizing /home/3t4/projects/ompi/scratch-ssd/ANNOYED-TAPIR/openmpi-5.0.0rc10/build-dbg/3rd-party/openpmix/bindings/python/pmix.pyx

Error compiling Cython file:
------------------------------------------------------------
...
        self.myserver.push_stdin = <pmix_server_stdin_fn_t>pushstdin
        # v4.x interfaces
        self.myserver.group = <pmix_server_grp_fn_t>group
        self.myserver.fabric = <pmix_server_fabric_fn_t>fabric
        # v5.x interfaces
        self.myserver.session_control = <pmix_server_session_control_fn_t>sessioncontrol
                                        ^
------------------------------------------------------------

/home/3t4/projects/ompi/scratch-ssd/ANNOYED-TAPIR/openmpi-5.0.0rc10/build-dbg/3rd-party/openpmix/bindings/python/pmix.pyx:1691:41: 'pmix_server_session_control_fn_t' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        self.myserver.push_stdin = <pmix_server_stdin_fn_t>pushstdin
        # v4.x interfaces
        self.myserver.group = <pmix_server_grp_fn_t>group
        self.myserver.fabric = <pmix_server_fabric_fn_t>fabric
        # v5.x interfaces
        self.myserver.session_control = <pmix_server_session_control_fn_t>sessioncontrol
                    ^
------------------------------------------------------------

/home/3t4/projects/ompi/scratch-ssd/ANNOYED-TAPIR/openmpi-5.0.0rc10/build-dbg/3rd-party/openpmix/bindings/python/pmix.pyx:1691:21: Object of type 'pmix_server_module_t' has no attribute 'session_control'

Error compiling Cython file:
------------------------------------------------------------
...
        if PMIX_SUCCESS != rc:
            return rc

         # call the API
        if 0 < sz:
            rc = PMIx_Session_control(sessionID, info, sz, NULL, NULL)
                ^
------------------------------------------------------------

/home/3t4/projects/ompi/scratch-ssd/ANNOYED-TAPIR/openmpi-5.0.0rc10/build-dbg/3rd-party/openpmix/bindings/python/pmix.pyx:2155:17: undeclared name not builtin: PMIx_Session_control

Error compiling Cython file:
------------------------------------------------------------
...
        if PMIX_SUCCESS != rc:
            return rc

         # call the API
        if 0 < sz:
            rc = PMIx_Session_control(sessionID, info, sz, NULL, NULL)
                                                ^
------------------------------------------------------------

/home/3t4/projects/ompi/scratch-ssd/ANNOYED-TAPIR/openmpi-5.0.0rc10/build-dbg/3rd-party/openpmix/bindings/python/pmix.pyx:2155:49: Cannot convert 'pmix_info_t *' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
        if PMIX_SUCCESS != rc:
            return rc

         # call the API
        if 0 < sz:
            rc = PMIx_Session_control(sessionID, info, sz, NULL, NULL)
                                                          ^
------------------------------------------------------------

/home/3t4/projects/ompi/scratch-ssd/ANNOYED-TAPIR/openmpi-5.0.0rc10/build-dbg/3rd-party/openpmix/bindings/python/pmix.pyx:2155:59: Cannot convert 'void *' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
        if PMIX_SUCCESS != rc:
            return rc

         # call the API
        if 0 < sz:
            rc = PMIx_Session_control(sessionID, info, sz, NULL, NULL)
                                                                ^
------------------------------------------------------------

/home/3t4/projects/ompi/scratch-ssd/ANNOYED-TAPIR/openmpi-5.0.0rc10/build-dbg/3rd-party/openpmix/bindings/python/pmix.pyx:2155:65: Cannot convert 'void *' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
         # call the API
        if 0 < sz:
            rc = PMIx_Session_control(sessionID, info, sz, NULL, NULL)
            pmix_free_info(info, sz)
        else:
            rc = PMIx_Session_control(sessionID, NULL, 0, NULL, NULL)
                                                ^
------------------------------------------------------------

/home/3t4/projects/ompi/scratch-ssd/ANNOYED-TAPIR/openmpi-5.0.0rc10/build-dbg/3rd-party/openpmix/bindings/python/pmix.pyx:2158:49: Cannot convert 'void *' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
         # call the API
        if 0 < sz:
            rc = PMIx_Session_control(sessionID, info, sz, NULL, NULL)
            pmix_free_info(info, sz)
        else:
            rc = PMIx_Session_control(sessionID, NULL, 0, NULL, NULL)
                                                         ^
------------------------------------------------------------

/home/3t4/projects/ompi/scratch-ssd/ANNOYED-TAPIR/openmpi-5.0.0rc10/build-dbg/3rd-party/openpmix/bindings/python/pmix.pyx:2158:58: Cannot convert 'void *' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
         # call the API
        if 0 < sz:
            rc = PMIx_Session_control(sessionID, info, sz, NULL, NULL)
            pmix_free_info(info, sz)
        else:
            rc = PMIx_Session_control(sessionID, NULL, 0, NULL, NULL)
                                                               ^
------------------------------------------------------------

/home/3t4/projects/ompi/scratch-ssd/ANNOYED-TAPIR/openmpi-5.0.0rc10/build-dbg/3rd-party/openpmix/bindings/python/pmix.pyx:2158:64: Cannot convert 'void *' to Python object
Traceback (most recent call last):
  File "../../../../../3rd-party/openpmix/bindings/python/setup.py", line 135, in <module>
    sys.exit(main())
  File "../../../../../3rd-party/openpmix/bindings/python/setup.py", line 129, in main
    package_setup(package_name, package_vers)
  File "../../../../../3rd-party/openpmix/bindings/python/setup.py", line 114, in package_setup
    ext_modules = cythonize([Extension("pmix",
  File "/usr/lib/python3/dist-packages/Cython/Build/Dependencies.py", line 1096, in cythonize
    cythonize_one(*args)
  File "/usr/lib/python3/dist-packages/Cython/Build/Dependencies.py", line 1219, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: /home/3t4/projects/ompi/scratch-ssd/ANNOYED-TAPIR/openmpi-5.0.0rc10/build-dbg/3rd-party/openpmix/bindings/python/pmix.pyx
make[5]: *** [Makefile:881: pmix.c] Error 1
make[5]: Leaving directory '/ssd/tjn/scratch/ompi-scratch/ANNOYED-TAPIR/openmpi-5.0.0rc10/build-dbg/3rd-party/openpmix/bindings/python'
make[4]: *** [Makefile:642: all] Error 2
make[4]: Leaving directory '/ssd/tjn/scratch/ompi-scratch/ANNOYED-TAPIR/openmpi-5.0.0rc10/build-dbg/3rd-party/openpmix/bindings/python'
make[3]: *** [Makefile:696: all-recursive] Error 1
make[3]: Leaving directory '/ssd/tjn/scratch/ompi-scratch/ANNOYED-TAPIR/openmpi-5.0.0rc10/build-dbg/3rd-party/openpmix/bindings'
make[2]: *** [Makefile:857: all-recursive] Error 1
make[2]: Leaving directory '/ssd/tjn/scratch/ompi-scratch/ANNOYED-TAPIR/openmpi-5.0.0rc10/build-dbg/3rd-party/openpmix'
make[1]: *** [Makefile:1403: all-recursive] Error 1
make[1]: Leaving directory '/ssd/tjn/scratch/ompi-scratch/ANNOYED-TAPIR/openmpi-5.0.0rc10/build-dbg/3rd-party'
make: *** [Makefile:1526: all-recursive] Error 1
```

**Comment by rhc54** [comment]
> likely just a sync issue with upstream openmpix/prrte as the python bindings build on main there.

Not really - the issue is that the Python bindings in v4.x got updated with some v5 stuff that didn't get caught when downgrading it. I can take care of it over there - please close this as it has nothing to do with OMPI.

**Comment by naughtont3** [comment]
OK thanks @rhc54.  
I'll keep this open just so we have a reminder on OMPI v5.0.x to ensure we pull updated prte/pmix.

**Comment by janjust** [comment]
Closing this, stale
