### ISSUE TITLE
Segfault in OB1 @ MPI_Init (main)

### ISSUE THREAD

**Issue by gkatev** [open-mpi/ompi#11438]
Hi, in the latest main (ompi @ e4695b2, prrte @ 10496e3), I'm getting intermittent segfaults inside code in `pml/ob1`, during MPI_Init.

```
$ for i in {1..100}; do mpirun -n 30 --mca coll basic,libnbc,tuned --mca smsc xpmem --mca opal_signal "" osu_bcast -m 16K:16K || break; echo "--------------------------"; done
..
..
[After ~10 runs]
..
..
--------------------------------------------------------------------------
prterun noticed that process rank 1 with PID 0 on node taos exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
```

```c++
#0  0x00007fb6ae5b1ef4 in mca_pml_ob1_peer_lookup (comm=0x413880 <ompi_mpi_comm_world>, rank=0) at pml_ob1_comm.h:99
99	    if( OPAL_UNLIKELY(rank >= (int)pml_comm->num_procs) ) {

(gdb) bt
#0  0x00007fb6ae5b1ef4 in mca_pml_ob1_peer_lookup (comm=0x413880 <ompi_mpi_comm_world>, rank=0) at pml_ob1_comm.h:99
#1  0x00007fb6ae5b3ff4 in mca_pml_ob1_recv_frag_callback_match (btl=0x7fb6ae95d2c0 <mca_btl_sm>, 
    descriptor=0x7ffe724f7fd0) at pml_ob1_recvfrag.c:489
#2  0x00007fb6ae8e8872 in mca_btl_sm_poll_handle_frag (hdr=0x7fb6a3001e00, endpoint=0x2692830)
    at btl_sm_component.c:449
#3  0x00007fb6ae8e8989 in mca_btl_sm_poll_fifo () at btl_sm_component.c:477
#4  0x00007fb6ae8e8c39 in mca_btl_sm_component_progress () at btl_sm_component.c:563
#5  0x00007fb6ae830319 in opal_progress () at runtime/opal_progress.c:224
#6  0x00007fb6ae3ee89f in ompi_mpi_instance_init_common (argc=3, argv=0x7ffe724f89f8) at instance/instance.c:730
#7  0x00007fb6ae3eec16 in ompi_mpi_instance_init (ts_level=0, info=0x414900 <ompi_mpi_info_null>, 
    errhandler=0x7fb6ae711080 <ompi_mpi_errors_are_fatal>, instance=0x7fb6ae722160 <ompi_mpi_instance_default>, 
    argc=3, argv=0x7ffe724f89f8) at instance/instance.c:804
#8  0x00007fb6ae3de6e4 in ompi_mpi_init (argc=3, argv=0x7ffe724f89f8, requested=0, provided=0x7ffe724f881c, 
    reinit_ok=false) at runtime/ompi_mpi_init.c:348
#9  0x00007fb6ae443ccf in PMPI_Init (argc=0x7ffe724f886c, argv=0x7ffe724f8860) at init.c:67
#10 0x00000000004024d7 in main (argc=<optimized out>, argv=<optimized out>) at osu_bcast.c:43

(gdb) print pml_comm
$1 = (mca_pml_ob1_comm_t *) 0x0
```

Not sure how I would further debug this -- please let me know if I can assist.

**Comment by hppritcha** [comment]
i'll revert the commits associated with https://github.com/open-mpi/ompi/pull/11305

There appears to be some race condition now with OB1 that seems to imply we need more than two pmix fences at startup.

**Comment by hppritcha** [comment]
@gkatev could you by chance repost the traceback in a way where we can see the complete lines?

**Comment by hppritcha** [comment]
never mind figured out how to see them.
