### ISSUE TITLE
OMPI non-blocking p2p cancelation test

### ISSUE THREAD

**Issue by artpol84** [open-mpi/ompi#1175]
I'm observing 100% reproducable hang of `cancelrecv.c` test from the MPICH test suite (`./test/mpi/pt2pt/cancelrecv.c`).
It happens with all combinations of BTLs (vader+tcp, vader+openib, vader) and the simplest configuration is one node and two processes.
I'm trying with different launchers: **mpirun**, **srun --mpi=pmi2**, **srun --mpi=pmix** with the same effect (different PMI implementations are involved).
Version of OMPI that I'm using:
a) master 324534b;
b) rebased against #1163;
c) rebased against #1165;
d) includes #1164.

Here are backtraces:
**rank=0** (waiting in the MPI_Finalize())
```
(gdb) bt
#0  0x0000003e68adf343 in poll () from /lib64/libc.so.6
#1  0x00007f53239d944a in poll_dispatch (base=0x1f81a30, tv=0x7f5322b13e30) at poll.c:165
#2  0x00007f53239d3406 in opal_libevent2022_event_base_loop (base=0x1f81a30, flags=1) at event.c:1629
#3  0x00007f5323976888 in progress_engine (obj=0x1fa6888) at runtime/opal_progress_threads.c:105
#4  0x0000003e692079d1 in start_thread () from /lib64/libpthread.so.0
#5  0x0000003e68ae8b6d in clone () from /lib64/libc.so.6
(gdb) thr 1 
[Switching to thread 1 (Thread 0x7f532372d700 (LWP 3501))]#0  0x0000003e6920e75d in read () from /lib64/libpthread.so.0
(gdb) bt
#0  0x0000003e6920e75d in read () from /lib64/libpthread.so.0
#1  0x00007f53214c5d7c in PMIi_ReadCommand (fd=11, cmd=0x7fff3fae5ea0) at pmi2_api.c:1367
#2  0x00007f53214c63e5 in PMIi_ReadCommandExp (fd=11, cmd=0x7fff3fae5ea0, exp=0x7f53214c7bf0 "kvs-fence-response", rc=0x7fff3fae5ec8, 
    errmsg=0x7fff3fae5ec0) at pmi2_api.c:1505
#3  0x00007f53214c384a in PMI2_KVS_Fence () at pmi2_api.c:733
#4  0x00007f53216dd945 in s2_fence (procs=0x0, collect_data=0) at pmix_s2.c:539
#5  0x00007f5323fd922d in ompi_mpi_finalize () at runtime/ompi_mpi_finalize.c:242
#6  0x00007f5324003b2d in PMPI_Finalize () at pfinalize.c:47
#7  0x0000000000401221 in main (argc=1, argv=0x7fff3fae6678) at cancelrecv.c:142
```

**rank=1** (Hangs in the while loop calling MPI_Testall
```
(gdb) bt
#0  0x0000003e68adf343 in poll () from /lib64/libc.so.6
#1  0x00007fa17656244a in poll_dispatch (base=0x1f7da10, tv=0x7fa17569ce30) at poll.c:165
#2  0x00007fa17655c406 in opal_libevent2022_event_base_loop (base=0x1f7da10, flags=1) at event.c:1629
#3  0x00007fa1764ff888 in progress_engine (obj=0x1fa2868) at runtime/opal_progress_threads.c:105
#4  0x0000003e692079d1 in start_thread () from /lib64/libpthread.so.0
#5  0x0000003e68ae8b6d in clone () from /lib64/libc.so.6
(gdb) thr 1
[Switching to thread 1 (Thread 0x7fa1762b6700 (LWP 3502))]#0  0x0000003e68acf527 in sched_yield () from /lib64/libc.so.6
(gdb) bt
#0  0x0000003e68acf527 in sched_yield () from /lib64/libc.so.6
#1  0x00007fa1764f8b79 in opal_progress () at runtime/opal_progress.c:199
#2  0x00007fa176b5f0fc in ompi_request_default_test_all (count=2, requests=0x7fff349b0be0, completed=0x7fff349b0b80, statuses=0x7fff349b0b90)
    at request/req_test.c:205
#3  0x00007fa176bb26f7 in PMPI_Testall (count=2, requests=0x7fff349b0be0, flag=0x7fff349b0b80, statuses=0x7fff349b0b90) at ptestall.c:80
#4  0x0000000000401172 in main (argc=1, argv=0x7fff349b0d28) at cancelrecv.c:122
```

**Comment by bosilca** [comment]
Despite what the test name indicates it cancel both sends and receives. As we do not support send cancelling this test deadlocks.

**Comment by artpol84** [comment]
So this is expected behavior and I should just exclude this from MTT?

**Comment by bosilca** [comment]
The only other option I see is to propose a patch to correctly handle cancel of sends operations.

**Comment by hppritcha** [comment]
we should just document that Open MPI doesn't support canceling of sends.
Removing blocker label.

**Comment by jsquyres** [comment]
I'll actually go further and close this with the "wontfix" label.
