### ISSUE TITLE
[5.0.0rc12]How to run multi node task with Spawn?

### ISSUE THREAD

**Issue by ZZWHU** [open-mpi/ompi#11885]
For some reason, I have to use python3 to run LLM with tensor parallelism and parallel parallelism, and cannot use mpirun.
So I use `mpi4py.MPI.Spwan`， it works well in single node, but I don't know how to set MPI.Info for Multi-node.
Here is my code (single node):
```python
from mpi4py import MPI
comm = MPI.COMM_WORLD
new_comm = comm.Spawn(command="python3", 
                      args=["llama.py"],
                      maxprocs=2)
``` 
Here is my code (Multi node):
```python
from mpi4py import MPI
comm = MPI.COMM_WORLD
info = MPI.Info.Create()
# info.Set('add-hostfile', 'worker_hosts')
info.Set('host', 'c4,slurmctld1')
new_comm = comm.Spawn(command="python3", 
                      args=["llama.py"],
                      maxprocs=2
                     info=info)
``` 
And get the error:
```
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 1
slots that were requested by the application:

  python3

Either request fewer slots for your application, or make more slots
available for use.

A "slot" is the Open MPI term for an allocatable unit where we can
launch a process.  The number of slots available are defined by the
environment in which Open MPI processes are run:

  1. Hostfile, via "slots=N" clauses (N defaults to number of
     processor cores if not provided)
  2. The --host command line parameter, via a ":N" suffix on the
     hostname (N defaults to 1 if not provided)
  3. Resource manager (e.g., SLURM, PBS/Torque, LSF, etc.)
  4. If none of a hostfile, the --host command line parameter, or an
     RM is present, Open MPI defaults to the number of processor cores

In all the above cases, if you want Open MPI to default to the number
of hardware threads instead of the number of processor cores, use the
--use-hwthread-cpus option.

Alternatively, you can use the --oversubscribe option to ignore the
number of available slots when deciding the number of processes to
launch.
--------------------------------------------------------------------------
[2023-08-30 10:41:30,687] ERROR in app: Exception on /init_model [POST]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "../examples/pytorch/llama/app.py", line 26, in init_model
    new_comm = comm.Spawn(command="python3",
  File "mpi4py/MPI/Comm.pyx", line 1931, in mpi4py.MPI.Intracomm.Spawn
mpi4py.MPI.Exception: MPI_ERR_SPAWN: could not spawn processes
```

**Comment by ZZWHU** [comment]
Follow other issues, I update OMPI from 4.1.3 to 5.0.0rc12
And this problem arises,  whether it's single node or  multi nodes
```python
    comm = MPI.COMM_WORLD
    procs = 2
    info = MPI.Info.Create()
    info.Set('PMIX_ENVAR', 'TENSOR_PARA_SIZE=2')
    info.Set('PMIX_ENVAR', 'OMPI_ALLOW_RUN_AS_ROOT=1')
    info.Set('PMIX_ENVAR', 'OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1')
    info.Set('PMIX_ENVAR', 'OMPI_MCA_btl=tcp,vader,self')
   new_comm = comm.Spawn(command="python3", 
                        args=["llama.py"],
                        maxprocs=2
                       info=info)
``` 
```
prte has detected an attempt to run as root.

Running as root is *strongly* discouraged as any mistake (e.g., in
defining TMPDIR) or bug can result in catastrophic damage to the OS
file system, leaving your system in an unusable state.

We strongly suggest that you run prte as a non-root user.

You can override this protection by adding the --allow-run-as-root
option to your command line.  However, we reiterate our strong advice
against doing so - please do so at your own risk.
--------------------------------------------------------------------------
[slurmctld1:01129] OPAL ERROR: Error in file dpm/dpm.c at line 2136
[2023-09-01 09:58:59,151] ERROR in app: Exception on /init_model [POST]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "../examples/pytorch/llama/app.py", line 35, in init_model
    new_comm = comm.Spawn(command="/opt/conda/bin/python3",
  File "mpi4py/MPI/Comm.pyx", line 1931, in mpi4py.MPI.Intracomm.Spawn
mpi4py.MPI.Exception: MPI_ERR_UNKNOWN: unknown error
```

**Comment by never-to-never** [comment]
Why is this question unanswered?

**Comment by rhc54** [comment]
> Why is this question unanswered?

🤷‍♂️  Guess nobody decided to pick it up. It is a rather confusing and limited description.

>     info.Set('PMIX_ENVAR', 'OMPI_ALLOW_RUN_AS_ROOT=1')
>    info.Set('PMIX_ENVAR', 'OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1')

I don't know if this will entirely solve your problem - I couldn't figure out what you are doing. However, setting those envars from inside the app won't do any good. You have to put them into your environment _before_ starting your application.
