### ISSUE TITLE
[mpi4py]: Regression in MPI_Comm_create_from_group

### ISSUE THREAD

**Issue by dalcinl** [open-mpi/ompi#11928]
New regression in mpi4py CI at `MPI_Comm_create_from_group`.  Full logs [here](https://github.com/mpi4py/mpi4py-testing/actions/runs/6153311809/job/16701373363).

Please note that the failure happens in branch `v5.0.x` only, and not in `main`.
@awlauria This is most likely after you merge of #11920.

**Comment by hppritcha** [comment]
I can't seem to reproduce this with the tests in our IBM testsuite.
I tried to build/run the mpi4py unit tests but am getting errors.

One, for example, is this:
```
======================================================================
ERROR: testImportTyping (test_package.TestImport)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/users/hpritchard/mpi4py/build/lib.linux-aarch64-3.6/mpi4py/typing.py", line 18, in <module>
    from typing import Protocol
ImportError: cannot import name 'Protocol'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/users/hpritchard/mpi4py/test/test_package.py", line 26, in testImportTyping
    import mpi4py.typing
  File "/users/hpritchard/mpi4py/build/lib.linux-aarch64-3.6/mpi4py/typing.py", line 21, in <module>
    from typing_extensions import Protocol
  File "/users/hpritchard/.local/lib/python3.6/site-packages/typing_extensions.py", line 159, in <module>
    class _FinalForm(typing._SpecialForm, _root=True):
AttributeError: module 'typing' has no attribute '_SpecialForm'

----------------------------------------------------------------------
```
Could you point me to instructions on how to build/run the mpi4py test suite?

**Comment by hppritcha** [comment]
oh never mind i was using main i will try 5.0.x.

**Comment by dalcinl** [comment]
@hppritcha Regarding the failure you got, you are using Python 3.6, which has been EOL from some time. I'm doing my best to keep supporting it, but testing is becoming difficult over time as many packages and CI services are simply removing Python 3.6. The particular failure you got is not mpi4py's fault, you have the `typing_extensions` module installed, and that particular version you have seems to be actually incompatible with Python 3.6. I'm investigating what's the best alternative to fix this testing issue.

**Comment by dalcinl** [comment]
@hppritcha Your `typing_extensions` package installed under `~/.local/...` is most likely outdated. Running `python 3.6 -m pip install --user -U typing_extensions` should fix things.

**Comment by rhc54** [comment]
The fix for the problem is here: https://github.com/openpmix/prrte/pull/1791. I also updated the "group.c" example in the PMIx v4.2 branch since group construct now returns multiple values that include the final group membership and (for this example) the assigned group context ID.

Will create a PR over here to update the submodule pointers.

**Comment by rhc54** [comment]
Okay, submodule pointer update is here: https://github.com/open-mpi/ompi/pull/11931

**Comment by dalcinl** [comment]
I triggered a new CI run [here](https://github.com/mpi4py/mpi4py-testing/actions/runs/6190838233/job/16807924181).

**Comment by dalcinl** [comment]
I confirm #11931 fixes the mpi4py testsuite.

**Comment by qkoziol** [comment]
@hppritcha - can this issue be closed?

**Comment by hppritcha** [comment]
fixed via #11931
