### ISSUE TITLE
mpi4py: PMIX error output

### ISSUE THREAD

**Issue by dalcinl** [open-mpi/ompi#12013]
I'm currently getting the following PMIX error output with ompi@master (have not tried v5.0.x).

```
$ mpiexec -n 1 python test/main.py test_exceptions -v -k testGetNthPsetPos
[0@kw61149] Python 3.11.6 (/usr/bin/python)
[0@kw61149] numpy 1.24.1 (/home/dalcinl/.local/lib/python3.11/site-packages/numpy)
[0@kw61149] MPI 3.1 (Open MPI 5.1.0)
[0@kw61149] mpi4py 4.0.0.dev0 (/home/dalcinl/Devel/mpi4py/build/lib.linux-x86_64-cpython-311/mpi4py)
[kw61149:831127] PMIX ERROR: PMIX_ERR_EMPTY in file ../../../../ompi/3rd-party/prrte/src/prted/pmix/pmix_server_queries.c at line 785
testGetNthPsetPos (test_exceptions.TestExcSession.testGetNthPsetPos) ... ok
```

This output happens in the context of testing whether OMPI properly generates an error on an invalid argument value:

```python
# file: test.py
from mpi4py import MPI

session = MPI.Session.Init()
num_psets = session.Get_num_psets()
session.Get_nth_pset(num_psets)  # <- should fail with exception!
session.Finalize()
```

```
$ mpiexec -n 1 python /tmp/test.py 
[kw61149:831205] PMIX ERROR: PMIX_ERR_EMPTY in file ../../../../ompi/3rd-party/prrte/src/prted/pmix/pmix_server_queries.c at line 785
Traceback (most recent call last):
  File "/tmp/test.py", line 5, in <module>
    session.Get_nth_pset(num_psets)
  File "src/mpi4py/MPI/Session.pyx", line 72, in mpi4py.MPI.Session.Get_nth_pset
    CHKERR( MPI_Session_get_nth_pset(
mpi4py.MPI.Exception: MPI_ERR_ARG: invalid argument of some other kind
```

**Comment by rhc54** [comment]
Fixed in https://github.com/openpmix/prrte/pull/1830

**Comment by dalcinl** [comment]
That was quick, thanks!
