### ISSUE TITLE
osu_bcast fails with OFI cxi provider when using CUDA device buffers

### ISSUE THREAD

**Issue by BenWibking** [open-mpi/ompi#12231]
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v4.1.6, v5.0.1, git branch name and hash, etc.)

5.0.1

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Built from 5.0.1 tarball with:
```
Configure command line: '--prefix=/projects/cvz/bwibking/openmpi-5.0.1-ss11-cuda12.3' '--with-slurm' '--with-pmix=internal' '--disable-oshmem' '--disable-mpi-fortran' '--with-cuda=/sw/spack/de
ltas11-2023-03/apps/linux-rhel8-x86_64/gcc-8.5.0/cuda-12.3.0-7oylpzc' '--with-cuda-libdir=/usr/lib64' '--with-ofi=/opt/cray/libfabric/1.15.2.0'
```

### Please describe the system on which you are running

* Operating system/version: RHEL 8.8
* Computer hardware: AMD Milan w/ 4x NVIDIA A100 40GB
* Network type: HPE Slingshot 11

-----------------------------

## Details of the problem

Using the OSU Micro Benchmarks v7.0, I ran the `osu_bcast` test with device buffers on NVIDIA A100 GPUs:

```
export FI_LOG_LEVEL=Debug
EXE="./osu-micro-benchmarks-7.0.1/c/mpi/collective/osu_bcast"
INPUTS="-f -d cuda"
mpirun -np 8 bash -c "${EXE} ${INPUTS}"
```

This produces an enormous amount of debugging output, but the relevant part is here:
```
libfabric:152388:1705097113::cxi:ep_ctrl:cxip_coll_enable():3510<info> gpua003.delta.ncsa.illinois.edu: FI_COLLECTIVE not requested

# OSU MPI-CUDA Broadcast Latency Test v7.0
# Size       Avg Latency(us)   Min Latency(us)   Max Latency(us)  Iterations
cxil_map: write error
libfabric:152385:1705097113::cxi:mr:cxip_do_map():94<warn> gpua003.delta.ncsa.illinois.edu: cxil_map failed: -22:Invalid argument
cxil_map: write error
libfabric:152386:1705097113::cxi:mr:cxip_do_map():94<warn> gpua003.delta.ncsa.illinois.edu: cxil_map failed: -22:Invalid argument
cxil_map: write error
libfabric:152385:1705097113::cxi:mr:cxip_do_map():94<warn> gpua003.delta.ncsa.illinois.edu: cxil_map failed: -22:Invalid argument
cxil_map: write error
libfabric:152386:1705097113::cxi:mr:cxip_do_map():94<warn> gpua003.delta.ncsa.illinois.edu: cxil_map failed: -22:Invalid argument
cxil_map: write error
libfabric:152385:1705097113::cxi:mr:cxip_do_map():94<warn> gpua003.delta.ncsa.illinois.edu: cxil_map failed: -22:Invalid argument
cxil_map: write error
libfabric:152386:1705097113::cxi:mr:cxip_do_map():94<warn> gpua003.delta.ncsa.illinois.edu: cxil_map failed: -22:Invalid argument
cxil_map: write error
```

**Comment by BenWibking** [comment]
The processes hang, and I get this backtrace:
```
(gdb) bt
#0  0x00007f746fb43a17 in write () from /lib64/libpthread.so.0
#1  0x00007f746d4bf4b9 in device_write.isra () from /lib64/libcxi.so.1
#2  0x00007f746d4c0eab in cxil_map () from /lib64/libcxi.so.1
#3  0x00007f746ee9c1de in cxip_do_map () from /opt/cray/libfabric/1.15.2.0/lib64/libfabric.so.1
#4  0x00007f746ee62136 in ofi_mr_cache_search () from /opt/cray/libfabric/1.15.2.0/lib64/libfabric.so.1
#5  0x00007f746ee9d046 in cxip_map () from /opt/cray/libfabric/1.15.2.0/lib64/libfabric.so.1
#6  0x00007f746ee864f3 in cxip_recv_req_alloc () from /opt/cray/libfabric/1.15.2.0/lib64/libfabric.so.1
#7  0x00007f746ee91bed in cxip_recv_common () from /opt/cray/libfabric/1.15.2.0/lib64/libfabric.so.1
#8  0x00007f746ee9263f in cxip_trecv () from /opt/cray/libfabric/1.15.2.0/lib64/libfabric.so.1
#9  0x00007f747085ef4b in ompi_mtl_ofi_irecv_true () from /projects/cvz/bwibking/openmpi-5.0.1-ss11-cuda12.3/lib/libmpi.so.40
#10 0x00007f74708ec36e in mca_pml_cm_irecv () from /projects/cvz/bwibking/openmpi-5.0.1-ss11-cuda12.3/lib/libmpi.so.40
#11 0x00007f74707755e8 in ompi_coll_base_bcast_intra_generic () from /projects/cvz/bwibking/openmpi-5.0.1-ss11-cuda12.3/lib/libmpi.so.40
#12 0x00007f7470775b6e in ompi_coll_base_bcast_intra_bintree () from /projects/cvz/bwibking/openmpi-5.0.1-ss11-cuda12.3/lib/libmpi.so.40
#13 0x00007f74707ace9c in ompi_coll_tuned_bcast_intra_dec_fixed () from /projects/cvz/bwibking/openmpi-5.0.1-ss11-cuda12.3/lib/libmpi.so.40
#14 0x00007f74707ce2b7 in mca_coll_han_bcast_t1_task () from /projects/cvz/bwibking/openmpi-5.0.1-ss11-cuda12.3/lib/libmpi.so.40
#15 0x00007f74707ce709 in mca_coll_han_bcast_intra () from /projects/cvz/bwibking/openmpi-5.0.1-ss11-cuda12.3/lib/libmpi.so.40
#16 0x00007f7470724215 in PMPI_Bcast () from /projects/cvz/bwibking/openmpi-5.0.1-ss11-cuda12.3/lib/libmpi.so.40
#17 0x0000000000402985 in main (argc=<optimized out>, argv=<optimized out>) at osu_bcast.c:112
```

**Comment by BenWibking** [comment]
Although this looks like a libfabric/cxi provider issue, this error does not happen for OpenMPI 4.1.5.

**Comment by hppritcha** [comment]
you may want to try setting
```
export OMPI_MCA_mtl_ofi_disable_hmem=true
```
and rerunning.

**Comment by hppritcha** [comment]
however, the CXI provider should work okay with CUDA allocated memory.

**Comment by hppritcha** [comment]
Did you get a chance to rerun with the suggested OMPI_MCA env variable set?

**Comment by BenWibking** [comment]
> Did you get a chance to rerun with the suggested OMPI_MCA env variable set?

The sysadmins changed something in the configuration and it started working without this change, so I didn't end up trying it.

If it happens again, I'll try it and report back. For now, I'll close this.
