### ISSUE TITLE
UDCM hang

### ISSUE THREAD

**Issue by artpol84** [open-mpi/ompi#1269]
@hjelmn I've faced the situation where application hangs because of UDCM. It is **VERY** rare! I saw this only once among 1000's of runs. 
**And I'm still have this hanged app "running" so we can do further postmortem analysis if you'll can think of anything that can be inspected with GDB.**

The application was `mpi_test_suite`. It has hanged at very beginning when application calls `MPI_Comm_dup()` (this seems to be a first communication call in this app).

Backtraces on all ranks looks the same:
```
#0  0x00000030a6ecf527 in sched_yield () from /lib64/libc.so.6
#1  0x00007f57b7aa5c19 in opal_progress () at runtime/opal_progress.c:199
#2  0x00007f57b810c608 in opal_condition_wait (c=0x7f57b8438b40, m=0x7f57b8438ac0) at ../opal/threads/condition.h:76
#3  0x00007f57b810cb99 in ompi_request_default_wait_all (count=2, requests=0x7fffc43044e0, statuses=0x0) at request/req_wait.c:287
#4  0x00007f57b81960ee in ompi_coll_base_allreduce_intra_recursivedoubling (sbuf=0x7fffc43046b8, rbuf=0x7fffc43046bc, count=1, dtype=0x65e4c0, 
    op=0x65fac0, comm=0x660ee0, module=0x2267800) at base/coll_base_allreduce.c:224
#5  0x00007f57b2635bd5 in ompi_coll_tuned_allreduce_intra_dec_fixed (sbuf=0x7fffc43046b8, rbuf=0x7fffc43046bc, count=1, dtype=0x65e4c0, op=0x65fac0, 
    comm=0x660ee0, module=0x2267800) at coll_tuned_decision_fixed.c:66
#6  0x00007f57b80e88ce in ompi_comm_allreduce_intra (inbuf=0x7fffc43046b8, outbuf=0x7fffc43046bc, count=1, op=0x65fac0, comm=0x660ee0, 
    bridgecomm=0x0, local_leader=0x0, remote_leader=0x0, send_first=-1, tag=0x7f57b81c6d2e "nextcid", iter=0) at communicator/comm_cid.c:878
#7  0x00007f57b80e733a in ompi_comm_nextcid (newcomm=0x226db60, comm=0x660ee0, bridgecomm=0x0, local_leader=0x0, remote_leader=0x0, mode=32, 
    send_first=-1) at communicator/comm_cid.c:221
#8  0x00007f57b80e4279 in ompi_comm_dup_with_info (comm=0x660ee0, info=0x0, newcomm=0x657888) at communicator/comm.c:1033
#9  0x00007f57b80e414d in ompi_comm_dup (comm=0x660ee0, newcomm=0x657888) at communicator/comm.c:994
#10 0x00007f57b8130cb0 in PMPI_Comm_dup (comm=0x660ee0, newcomm=0x657888) at pcomm_dup.c:63
#11 0x000000000043c082 in tst_comm_init (num_comms=0x7fffc4304c7c) at tst_comm.c:111
#12 0x000000000041548a in main (argc=7, argv=0x7fffc4304e78) at mpi_test_suite.c:278
```
However more detailed analysis has shown that they are on different steps (according to the `distance` variable). 

| ranks  | distance |
| ------------- | ------------- |
| 0-15  | 16  |
| 16-23  | 8  |
| 24-27  | 4  |
| 28-29  | 2  |
| 30-31  | 1  |

So it was abvious that ranks 30 and 31 failed to communicate. Checking more closely request content:
**rank 0**:
```
(gdb) frame 3
#3  0x00007f8e7d170b99 in ompi_request_default_wait_all (count=2, requests=0x7ffff7c9c670, statuses=0x0) at request/req_wait.c:287
287                     opal_condition_wait(&ompi_request_cond, &ompi_request_lock);
(gdb) p *requests[0]
$37 = {super = {super = {super = {obj_magic_id = 16046253926196952813, obj_class = 0x7f57b372e680, obj_reference_count = 1, 
        cls_init_file_name = 0x7f57b3526cb1 "pml_ob1_recvreq.c", cls_init_lineno = 1060}, opal_list_next = 0x201bbe0, opal_list_prev = 0x201bbe0, 
      item_free = 1, opal_list_item_refcount = 0, opal_list_item_belong_to = 0x0}, registration = 0x0, ptr = 0x0}, req_type = OMPI_REQUEST_PML, 
  req_status = {MPI_SOURCE = 31, MPI_TAG = -12, MPI_ERROR = 0, _cancelled = 0, _ucount = 4}, req_complete = true, req_state = OMPI_REQUEST_ACTIVE, 
  req_persistent = false, req_f_to_c_index = -32766, req_free = 0x7f57b351a5b3 <mca_pml_ob1_recv_request_free>, 
  req_cancel = 0x7f57b351a64d <mca_pml_ob1_recv_request_cancel>, req_complete_cb = 0, req_complete_cb_data = 0x0, req_mpi_object = {comm = 0x660ee0, 
    file = 0x660ee0, win = 0x660ee0}}
(gdb) p *requests[1]
$38 = {super = {super = {super = {obj_magic_id = 16046253926196952813, obj_class = 0x7f57b372e700, obj_reference_count = 1, 
        cls_init_file_name = 0x7f57b7b6068c "class/opal_free_list.c", cls_init_lineno = 232}, opal_list_next = 0x0, opal_list_prev = 0x0, 
      item_free = 1, opal_list_item_refcount = 0, opal_list_item_belong_to = 0x0}, registration = 0x0, ptr = 0x0}, req_type = OMPI_REQUEST_PML, 
  req_status = {MPI_SOURCE = 0, MPI_TAG = 0, MPI_ERROR = 0, _cancelled = 0, _ucount = 0}, req_complete = false, req_state = OMPI_REQUEST_ACTIVE, 
  req_persistent = false, req_f_to_c_index = -32766, req_free = 0x7f57b351ee19 <mca_pml_ob1_send_request_free>, 
  req_cancel = 0x7f57b351eeb3 <mca_pml_ob1_send_request_cancel>, req_complete_cb = 0, req_complete_cb_data = 0x0, req_mpi_object = {comm = 0x660ee0, 
    file = 0x660ee0, win = 0x660ee0}}
```
**rank 31**
```
(gdb) frame 3
#3  0x00007f8e7d170b99 in ompi_request_default_wait_all (count=2, requests=0x7ffff7c9c670, statuses=0x0) at request/req_wait.c:287
287                     opal_condition_wait(&ompi_request_cond, &ompi_request_lock);
(gdb) p *requests[0]
$10 = {super = {super = {super = {obj_magic_id = 16046253926196952813, obj_class = 0x7f8e7899b680, obj_reference_count = 1,
        cls_init_file_name = 0x7f8e78793cb1 "pml_ob1_recvreq.c", cls_init_lineno = 1060}, opal_list_next = 0x18fdba0, opal_list_prev = 0x18fdba0,
      item_free = 1, opal_list_item_refcount = 1, opal_list_item_belong_to = 0x18fdb78}, registration = 0x0, ptr = 0x0},
  req_type = OMPI_REQUEST_PML, req_status = {MPI_SOURCE = -1, MPI_TAG = -1, MPI_ERROR = 0, _cancelled = 0, _ucount = 0}, req_complete = false,
  req_state = OMPI_REQUEST_ACTIVE, req_persistent = false, req_f_to_c_index = -32766, req_free = 0x7f8e787875b3 <mca_pml_ob1_recv_request_free>,
  req_cancel = 0x7f8e7878764d <mca_pml_ob1_recv_request_cancel>, req_complete_cb = 0, req_complete_cb_data = 0x0, req_mpi_object = {comm = 0x660ee0,
    file = 0x660ee0, win = 0x660ee0}}
(gdb) p *requests[1]
$11 = {super = {super = {super = {obj_magic_id = 16046253926196952813, obj_class = 0x7f8e7899b700, obj_reference_count = 1,
        cls_init_file_name = 0x7f8e7cbc468c "class/opal_free_list.c", cls_init_lineno = 232}, opal_list_next = 0x0, opal_list_prev = 0x0,
      item_free = 1, opal_list_item_refcount = 0, opal_list_item_belong_to = 0x0}, registration = 0x0, ptr = 0x0}, req_type = OMPI_REQUEST_PML,
  req_status = {MPI_SOURCE = 31, MPI_TAG = -12, MPI_ERROR = 0, _cancelled = 0, _ucount = 4}, req_complete = true, req_state = OMPI_REQUEST_ACTIVE,
  req_persistent = false, req_f_to_c_index = -32766, req_free = 0x7f8e7878be19 <mca_pml_ob1_send_request_free>,
  req_cancel = 0x7f8e7878beb3 <mca_pml_ob1_send_request_cancel>, req_complete_cb = 0, req_complete_cb_data = 0x0, req_mpi_object = {comm = 0x660ee0,
    file = 0x660ee0, win = 0x660ee0}}
```
 I figured that failed communication is from **rank 30** to **rank31**. And looking closer to the openib proc list I found that on connection is half-established:

**rank 30**
```
(gdb) p ((mca_btl_openib_proc_t*)mca_btl_openib_component.ib_procs->opal_list_sentinel->opal_list_prev)->proc_endpoints[0]->rem_info
$33 = {rem_lid = 20, rem_subnet_id = 18338657682652659712, rem_mtu = 5, rem_index = 33, rem_qps = 0x226b4f0, rem_srqs = 0x0, rem_vendor_id = 713, 
  rem_vendor_part_id = 4113, rem_transport_type = MCA_BTL_OPENIB_TRANSPORT_IB}
(gdb) p ((mca_btl_openib_proc_t*)mca_btl_openib_component.ib_procs->opal_list_sentinel->opal_list_prev)->proc_endpoints[0]->endpoint_state 
$34 = MCA_BTL_IB_CONNECTING
(gdb) p ((mca_btl_openib_proc_t*)mca_btl_openib_component.ib_procs->opal_list_sentinel->opal_list_prev)->proc_endpoints[1]->rem_info
$35 = {rem_lid = 18, rem_subnet_id = 18338657682652659712, rem_mtu = 5, rem_index = 0, rem_qps = 0x226b060, rem_srqs = 0x0, rem_vendor_id = 713, 
  rem_vendor_part_id = 4113, rem_transport_type = MCA_BTL_OPENIB_TRANSPORT_IB}
(gdb) p ((mca_btl_openib_proc_t*)mca_btl_openib_component.ib_procs->opal_list_sentinel->opal_list_prev)->proc_endpoints[1]->endpoint_state 
$36 = MCA_BTL_IB_CLOSED
```

**rank 31**
```
(gdb) p ((mca_btl_openib_proc_t*)mca_btl_openib_component.ib_procs->opal_list_sentinel->opal_list_prev)->proc_endpoints[0]->rem_info
$12 = {rem_lid = 14, rem_subnet_id = 18338657682652659712, rem_mtu = 5, rem_index = 0, rem_qps = 0x1b50080, rem_srqs = 0x0, rem_vendor_id = 713, 
  rem_vendor_part_id = 4113, rem_transport_type = MCA_BTL_OPENIB_TRANSPORT_IB}
(gdb) p ((mca_btl_openib_proc_t*)mca_btl_openib_component.ib_procs->opal_list_sentinel->opal_list_prev)->proc_endpoints[0]->endpoint_state 
$13 = MCA_BTL_IB_CLOSED
(gdb) p ((mca_btl_openib_proc_t*)mca_btl_openib_component.ib_procs->opal_list_sentinel->opal_list_prev)->proc_endpoints[1]->rem_info
$14 = {rem_lid = 15, rem_subnet_id = 18338657682652659712, rem_mtu = 5, rem_index = 32, rem_qps = 0x1b50370, rem_srqs = 0x0, rem_vendor_id = 713, 
  rem_vendor_part_id = 4113, rem_transport_type = MCA_BTL_OPENIB_TRANSPORT_IB}
(gdb) p ((mca_btl_openib_proc_t*)mca_btl_openib_component.ib_procs->opal_list_sentinel->opal_list_prev)->proc_endpoints[1]->endpoint_state 
$15 = MCA_BTL_IB_CONNECTED
```

and here is the full content of OB1 requests:
**rank 30**:
```
(gdb) p *((mca_pml_ob1_send_request_t*)requests[1])
$39 = {req_send = {req_base = {req_ompi = {super = {super = {super = {obj_magic_id = 16046253926196952813, obj_class = 0x7f57b372e700, 
              obj_reference_count = 1, cls_init_file_name = 0x7f57b7b6068c "class/opal_free_list.c", cls_init_lineno = 232}, opal_list_next = 0x0, 
            opal_list_prev = 0x0, item_free = 1, opal_list_item_refcount = 0, opal_list_item_belong_to = 0x0}, registration = 0x0, ptr = 0x0}, 
        req_type = OMPI_REQUEST_PML, req_status = {MPI_SOURCE = 0, MPI_TAG = 0, MPI_ERROR = 0, _cancelled = 0, _ucount = 0}, req_complete = false, 
        req_state = OMPI_REQUEST_ACTIVE, req_persistent = false, req_f_to_c_index = -32766, 
        req_free = 0x7f57b351ee19 <mca_pml_ob1_send_request_free>, req_cancel = 0x7f57b351eeb3 <mca_pml_ob1_send_request_cancel>, 
        req_complete_cb = 0, req_complete_cb_data = 0x0, req_mpi_object = {comm = 0x660ee0, file = 0x660ee0, win = 0x660ee0}}, 
      req_pml_complete = false, req_type = MCA_PML_REQUEST_SEND, req_comm = 0x660ee0, req_datatype = 0x65e4c0, req_free_called = false, 
      req_convertor = {super = {obj_magic_id = 16046253926196952813, obj_class = 0x7f57b7da6600, obj_reference_count = 1, 
          cls_init_file_name = 0x7f57b81ea7c5 "base/pml_base_sendreq.c", cls_init_lineno = 39}, remoteArch = 4291367424, flags = 136074038, 
        local_size = 4, remote_size = 4, pDesc = 0x65e4c0, use_desc = 0x65e578, count = 1, stack_size = 5, pBaseBuf = 0x201bae0 "\003", 
        pStack = 0x1fcabe8, fAdvance = 0, master = 0x1ecd8c0, stack_pos = 0, partial_length = 0, bConverted = 4, checksum = 0, csum_ui1 = 0, 
        csum_ui2 = 0, static_stack = {{index = 0, type = 0, count = 0, disp = 0}, {index = 0, type = 0, count = 0, disp = 0}, {index = 0, type = 0, 
            count = 0, disp = 0}, {index = 0, type = 0, count = 0, disp = 0}, {index = 0, type = 0, count = 0, disp = 0}}}, req_addr = 0x201bae0, 
      req_count = 1, req_peer = 31, req_tag = -12, req_proc = 0x226a710, req_sequence = 1}, req_addr = 0x201bae0, req_bytes_packed = 4, 
    req_send_mode = MCA_PML_BASE_SEND_STANDARD}, req_endpoint = 0x226e7b0, req_recv = {lval = 0, ival = 0, pval = 0x0, sval = {uval = 0, lval = 0}}, 
  req_state = 0, req_lock = 0, req_throttle_sends = false, req_pipeline_depth = 0, req_bytes_delivered = 0, req_rdma_cnt = 0, 
  req_pending = MCA_PML_OB1_SEND_PENDING_NONE, req_send_range_lock = {super = {obj_magic_id = 16046253926196952813, obj_class = 0x7f57b7da62a0, 
      obj_reference_count = 1, cls_init_file_name = 0x7f57b3527452 "pml_ob1_sendreq.c", cls_init_lineno = 143}, m_lock_pthread = {__data = {
        __lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 2, __spins = 0, __list = {__prev = 0x0, __next = 0x0}}, 
      __size = '\000' <repeats 16 times>, "\002", '\000' <repeats 22 times>, __align = 0}, m_lock_debug = 0, m_lock_file = 0x0, m_lock_line = 0, 
    m_lock_atomic = {u = {lock = 0, sparc_lock = 0 '\000', padding = "\000\000\000"}}}, req_send_ranges = {super = {
      obj_magic_id = 16046253926196952813, obj_class = 0x7f57b7da5c00, obj_reference_count = 1, 
      cls_init_file_name = 0x7f57b3527452 "pml_ob1_sendreq.c", cls_init_lineno = 142}, opal_list_sentinel = {super = {
        obj_magic_id = 16046253926196952813, obj_class = 0x7f57b7da5bc0, obj_reference_count = 1, 
        cls_init_file_name = 0x7f57b7b616bb "class/opal_list.c", cls_init_lineno = 88}, opal_list_next = 0x1fcad68, opal_list_prev = 0x1fcad68, 
      item_free = 1, opal_list_item_refcount = 1, opal_list_item_belong_to = 0x1fcad40}, opal_list_length = 0}, rdma_frag = 0x0, 
  req_rdma = 0x1fcaa80}
```

**rank 31**
```
(gdb) p *((mca_pml_ob1_recv_request_t*)requests[0])
$16 = {req_recv = {req_base = {req_ompi = {super = {super = {super = {obj_magic_id = 16046253926196952813, obj_class = 0x7f8e7899b680, 
              obj_reference_count = 1, cls_init_file_name = 0x7f8e78793cb1 "pml_ob1_recvreq.c", cls_init_lineno = 1060}, opal_list_next = 0x18fdba0, 
            opal_list_prev = 0x18fdba0, item_free = 1, opal_list_item_refcount = 1, opal_list_item_belong_to = 0x18fdb78}, registration = 0x0, 
          ptr = 0x0}, req_type = OMPI_REQUEST_PML, req_status = {MPI_SOURCE = -1, MPI_TAG = -1, MPI_ERROR = 0, _cancelled = 0, _ucount = 0}, 
        req_complete = false, req_state = OMPI_REQUEST_ACTIVE, req_persistent = false, req_f_to_c_index = -32766, 
        req_free = 0x7f8e787875b3 <mca_pml_ob1_recv_request_free>, req_cancel = 0x7f8e7878764d <mca_pml_ob1_recv_request_cancel>, 
        req_complete_cb = 0, req_complete_cb_data = 0x0, req_mpi_object = {comm = 0x660ee0, file = 0x660ee0, win = 0x660ee0}}, 
      req_pml_complete = false, req_type = MCA_PML_REQUEST_RECV, req_comm = 0x660ee0, req_datatype = 0x65e4c0, req_free_called = false, 
      req_convertor = {super = {obj_magic_id = 16046253926196952813, obj_class = 0x7f8e7ce0a600, obj_reference_count = 1, 
          cls_init_file_name = 0x7f8e7d24dfb5 "base/pml_base_recvreq.c", cls_init_lineno = 42}, remoteArch = 4291367424, flags = 1725238, 
        local_size = 4, remote_size = 4, pDesc = 0x65e4c0, use_desc = 0x65e578, count = 1, stack_size = 5, pBaseBuf = 0x7ffff7c9c84c "", 
        pStack = 0x18adbe8, fAdvance = 0, master = 0x180c340, stack_pos = 0, partial_length = 0, bConverted = 0, checksum = 0, csum_ui1 = 0, 
        csum_ui2 = 0, static_stack = {{index = 0, type = 0, count = 0, disp = 0}, {index = 0, type = 0, count = 0, disp = 0}, {index = 0, type = 0, 
            count = 0, disp = 0}, {index = 0, type = 0, count = 0, disp = 0}, {index = 0, type = 0, count = 0, disp = 0}}}, 
      req_addr = 0x7ffff7c9c84c, req_count = 1, req_peer = 30, req_tag = -12, req_proc = 0x18fdca0, req_sequence = 0}, req_bytes_packed = 0}, 
  remote_req_send = {lval = 0, ival = 0, pval = 0x0, sval = {uval = 0, lval = 0}}, req_lock = 0, req_pipeline_depth = 0, req_bytes_received = 0, 
  req_bytes_expected = 4, req_rdma_offset = 0, req_send_offset = 0, req_rdma_cnt = 0, req_rdma_idx = 0, req_pending = false, req_ack_sent = false, 
  req_match_received = false, lock = {super = {obj_magic_id = 16046253926196952813, obj_class = 0x7f8e7ce0a2a0, obj_reference_count = 1, 
      cls_init_file_name = 0x7f8e78793cb1 "pml_ob1_recvreq.c", cls_init_lineno = 155}, m_lock_pthread = {__data = {__lock = 0, __count = 0, 
        __owner = 0, __nusers = 0, __kind = 2, __spins = 0, __list = {__prev = 0x0, __next = 0x0}}, 
      __size = '\000' <repeats 16 times>, "\002", '\000' <repeats 22 times>, __align = 0}, m_lock_debug = 0, m_lock_file = 0x0, m_lock_line = 0, 
    m_lock_atomic = {u = {lock = 0, sparc_lock = 0 '\000', padding = "\000\000\000"}}}, rdma_bml = 0x0, local_handle = 0x0, req_rdma = 0x18ada80}
```

**Comment by artpol84** [comment]
Fixed by PR https://github.com/open-mpi/ompi/pull/1283.
