### ISSUE TITLE
osc/pt2pt : CUDA tests broken

### ISSUE THREAD

**Issue by sjeaugey** [open-mpi/ompi#1342]
Several CUDA tests are failing in MTT since Feb 3. This seems related to the recent osc/pt2pt commits.

Here is the stack trace from osu_get_bw_cuda :

```
#0  0x00007f9788fb45d0 in ?? ()
#1  <signal handler called>
#2  0x00007f978836cd9f in _opal_list_append () from /ivylogin/home/sjeaugey/tests/mtt/scratches/mtt-scratch-3/installs/rPaA/install/lib/openmpi/mca_osc_pt2pt.so
#3  0x00007f978836d93f in osc_pt2pt_gc_add_request () from /ivylogin/home/sjeaugey/tests/mtt/scratches/mtt-scratch-3/installs/rPaA/install/lib/openmpi/mca_osc_pt2pt.so
#4  0x00007f978836e015 in ompi_osc_pt2pt_comm_complete () from /ivylogin/home/sjeaugey/tests/mtt/scratches/mtt-scratch-3/installs/rPaA/install/lib/openmpi/mca_osc_pt2pt.so
#5  0x00007f978836e09e in ompi_osc_pt2pt_req_comm_complete () from /ivylogin/home/sjeaugey/tests/mtt/scratches/mtt-scratch-3/installs/rPaA/install/lib/openmpi/mca_osc_pt2pt.so
#6  0x00007f9789a4451e in ompi_request_complete () from /ivylogin/home/sjeaugey/tests/mtt/scratches/mtt-scratch-3/installs/rPaA/install/lib/openmpi/mca_pml_ob1.so
#7  0x00007f9789a44fa7 in recv_request_pml_complete () from /ivylogin/home/sjeaugey/tests/mtt/scratches/mtt-scratch-3/installs/rPaA/install/lib/openmpi/mca_pml_ob1.so
#8  0x00007f9789a45c7f in mca_pml_ob1_recv_frag_callback_match () from /ivylogin/home/sjeaugey/tests/mtt/scratches/mtt-scratch-3/installs/rPaA/install/lib/openmpi/mca_pml_ob1.so
#9  0x00007f978b146266 in btl_openib_handle_incoming () from /ivylogin/home/sjeaugey/tests/mtt/scratches/mtt-scratch-3/installs/rPaA/install/lib/openmpi/mca_btl_openib.so
#10 0x00007f978b1472f1 in handle_wc () from /ivylogin/home/sjeaugey/tests/mtt/scratches/mtt-scratch-3/installs/rPaA/install/lib/openmpi/mca_btl_openib.so
#11 0x00007f978b14799e in poll_device () from /ivylogin/home/sjeaugey/tests/mtt/scratches/mtt-scratch-3/installs/rPaA/install/lib/openmpi/mca_btl_openib.so
#12 0x00007f978b147d22 in progress_one_device () from /ivylogin/home/sjeaugey/tests/mtt/scratches/mtt-scratch-3/installs/rPaA/install/lib/openmpi/mca_btl_openib.so
#13 0x00007f978b147dd7 in btl_openib_component_progress () from /ivylogin/home/sjeaugey/tests/mtt/scratches/mtt-scratch-3/installs/rPaA/install/lib/openmpi/mca_btl_openib.so
#14 0x00007f978fd2220e in opal_progress () from /ivylogin/home/sjeaugey/tests/mtt/scratches/mtt-scratch-3/installs/rPaA/install/lib/libopen-pal.so.0
#15 0x00007f97883797b3 in opal_condition_wait () from /ivylogin/home/sjeaugey/tests/mtt/scratches/mtt-scratch-3/installs/rPaA/install/lib/openmpi/mca_osc_pt2pt.so
#16 0x00007f978837a9f7 in ompi_osc_pt2pt_complete () from /ivylogin/home/sjeaugey/tests/mtt/scratches/mtt-scratch-3/installs/rPaA/install/lib/openmpi/mca_osc_pt2pt.so
#17 0x00007f9791007146 in PMPI_Win_complete () from /ivylogin/home/sjeaugey/tests/mtt/scratches/mtt-scratch-3/installs/rPaA/install/lib/libmpi.so.0
#18 0x0000000000401a59 in main ()
```

**Comment by ggouaillardet** [comment]
@sjeaugey did you give a try to #1341 ?

**Comment by sjeaugey** [comment]
Oh, I didn't see this commit was done today. I'll see tomorrow if the problem persists.

**Comment by ggouaillardet** [comment]
right now, this is a PR.
but it should be committed shortly

**Comment by hjelmn** [comment]
Yup. Has a couple of bugs from changes that didn't make it into the final set of threading fixes. Should run clean tonight.

**Comment by hppritcha** [comment]
@sjeaugey can you verify this PR fixes the osc problems you were observing?

**Comment by sjeaugey** [comment]
Fixed indeed. Closing.
