### ISSUE TITLE
v2.x : Segmentation fault in Aint tests with IB

### ISSUE THREAD

**Issue by sjeaugey** [open-mpi/ompi#1427]
Aint tests have been broken for a long time in v2.x (~ at the same time we got all the onesided tests failing also).

The onesided fixes on openib fixed all errors on master, but on v2.x, there are still tests failing : aint and c_post_start. Not sure it c_post_start is the same error as I can't get a working core file, but the stack for aint is :
```
#0  0x00007f1832e705d0 in ?? ()
#1  <signal handler called>
#2  0x00007f1835a97f31 in mca_btl_openib_get () from /ivylogin/home/sjeaugey/tests/mtt/scratches/mtt-scratch-4/installs/x5xY/install/lib/openmpi/mca_btl_openib.so
#3  0x00007f183244af94 in ompi_osc_get_data_blocking () from /ivylogin/home/sjeaugey/tests/mtt/scratches/mtt-scratch-4/installs/x5xY/install/lib/openmpi/mca_osc_rdma.so
#4  0x00007f183245e5cf in ompi_osc_rdma_refresh_dynamic_region () from /ivylogin/home/sjeaugey/tests/mtt/scratches/mtt-scratch-4/installs/x5xY/install/lib/openmpi/mca_osc_rdma.so
#5  0x00007f183245e855 in ompi_osc_rdma_find_dynamic_region () from /ivylogin/home/sjeaugey/tests/mtt/scratches/mtt-scratch-4/installs/x5xY/install/lib/openmpi/mca_osc_rdma.so
#6  0x00007f183244abac in osc_rdma_get_remote_segment () from /ivylogin/home/sjeaugey/tests/mtt/scratches/mtt-scratch-4/installs/x5xY/install/lib/openmpi/mca_osc_rdma.so
#7  0x00007f183244d0d5 in ompi_osc_rdma_get_w_req () from /ivylogin/home/sjeaugey/tests/mtt/scratches/mtt-scratch-4/installs/x5xY/install/lib/openmpi/mca_osc_rdma.so
#8  0x00007f183244d5fb in ompi_osc_rdma_get () from /ivylogin/home/sjeaugey/tests/mtt/scratches/mtt-scratch-4/installs/x5xY/install/lib/openmpi/mca_osc_rdma.so
#9  0x00007f183b5dc26d in PMPI_Get () from /ivylogin/home/sjeaugey/tests/mtt/scratches/mtt-scratch-4/installs/x5xY/install/lib/libmpi.so.20
#10 0x00000000004014ec in do_the_test ()
#11 0x00000000004015ed in main ()
```

**Comment by hjelmn** [comment]
Tracked it down to the two missing commits. Once open-mpi/ompi-release#1009 is in 2.x we can close this.
