### ISSUE TITLE
orterun crashes in PMIx with current master branch

### ISSUE THREAD

**Issue by nysal** [open-mpi/ompi#1498]
pmix 112 and pmix 120 seem to be geeting mixed up, based on the stack trace below:

```
$ /u/user1/ompi-master/bin/mpirun -np 2 ./hello_c                                    
libnuma: Warning: /sys not mounted or invalid. Assuming one node: No such file or directory
[c712f5n10:16759] PACK-PMIX-VALUE: UNSUPPORTED TYPE 0
[c712f5n10:16759] PMIX ERROR: ERROR in file /u/user1/src/ompi-master/opal/mca/pmix/pmix112/pmix/src/server/pmix_server.c at line 338
*** Error in `/u/user1/ompi-master/bin/mpirun': free(): invalid pointer: 0x0000010025ded1a0 ***
======= Backtrace: =========
/lib64/power8/libc.so.6(+0x8f284)[0x3fff8e30f284]
/u/user1/ompi-master/lib/openmpi/mca_pmix_pmix112.so(+0x263a4)[0x3fff8c4c63a4]
/u/user1/ompi-master/lib/openmpi/mca_pmix_pmix112.so(+0x572a0)[0x3fff8c4f72a0]
/u/user1/ompi-master/lib/openmpi/mca_pmix_pmix112.so(PMIx_server_init+0x3fc)[0x3fff8c4f8a8c]
/u/user1/ompi-master/lib/openmpi/mca_pmix_pmix120.so(pmix120_server_init+0x1c0)[0x3fff8c3f99e8]
/u/user1/ompi-master/lib/libopen-rte.so.0(pmix_server_init+0x690)[0x3fff8e853a30]
/u/user1/ompi-master/lib/openmpi/mca_ess_hnp.so(+0x58f4)[0x3fff8e0f58f4]
/u/user1/ompi-master/lib/libopen-rte.so.0(orte_init+0x4bc)[0x3fff8e800294]
/u/user1/ompi-master/bin/mpirun[0x10005458]
/u/user1/ompi-master/bin/mpirun[0x10003a60]
/lib64/power8/libc.so.6(+0x24580)[0x3fff8e2a4580]
/lib64/power8/libc.so.6(__libc_start_main+0xc4)[0x3fff8e2a4774]



(gdb) bt
#0  0x00003fffb6d1e578 in raise () from /lib64/power8/libc.so.6
#1  0x00003fffb6d20650 in abort () from /lib64/power8/libc.so.6
#2  0x00003fffb6d64844 in __libc_message () from /lib64/power8/libc.so.6
#3  0x00003fffb6d6f284 in _int_free () from /lib64/power8/libc.so.6
#4  0x00003fffb4f263a4 in kvdes (k=0x3fffd2be59c8)
    at /u/user1/src/ompi-master/opal/mca/pmix/pmix112/pmix/src/buffer_ops/open_close.c:114
#5  0x00003fffb4f572a0 in pmix_obj_run_destructors (object=0x3fffd2be59c8)
    at /u/user1/src/ompi-master/opal/mca/pmix/pmix112/pmix/src/class/pmix_object.h:449
#6  0x00003fffb4f58a8c in PMIx_server_init (module=0x3fffb4ef0b80 <pmix120_module>, info=0x100057fd180, ninfo=1)
    at /u/user1/src/ompi-master/opal/mca/pmix/pmix112/pmix/src/server/pmix_server.c:339
#7  0x00003fffb4e599e8 in pmix120_server_init (module=0x3fffb7372438 <pmix_server>, info=0x3fffd2be5bd8)
    at /u/user1/src/ompi-master/opal/mca/pmix/pmix120/pmix120_server_south.c:80
#8  0x00003fffb72b3a30 in pmix_server_init () at /u/user1/src/ompi-master/orte/orted/pmix/pmix_server.c:246
#9  0x00003fffb6b558f4 in rte_init () at /u/user1/src/ompi-master/orte/mca/ess/hnp/ess_hnp_module.c:635
#10 0x00003fffb7260294 in orte_init (pargc=0x3fffd2be6540, pargv=0x3fffd2be6548, flags=4)
    at /u/user1/src/ompi-master/orte/runtime/orte_init.c:243
#11 0x0000000010005458 in orterun (argc=6, argv=0x3fffd2be69b8)
    at /u/user1/src/ompi-master/orte/tools/orterun/orterun.c:834
#12 0x0000000010003a60 in main (argc=6, argv=0x3fffd2be69b8) at /u/user1/src/ompi-master/orte/tools/orterun/main.c:13
(gdb) 
```

**Comment by nysal** [comment]
This report is invalid. A build issue.
