### ISSUE TITLE
segv while running "Allgather with MPI_IN_PLACE" test in mpi_test_suite.

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#159]
Trying to run the following will result in segv (This happens on 1.6.2 branch.):

```
mpirun -np 6 -bind-to-core -bynode -display-map -mca btl sm,self,openib ./mpi_test_suite -x relaxed -t 'Allgather with MPI_IN_PLACE,^One-sided'
```

The output:

```
(Rank:0) tst_test_array[0]:Allgather with MPI_IN_PLACE        
Collective tests Allgather with MPI_IN_PLACE (33/1), comm MPI_COMM_WORLD (1/13), type MPI_CHAR (1/29)
...
...
Collective tests Allgather with MPI_IN_PLACE (33/1), comm Duplicated MPI_COMM_WORLD (4/13), type MPI_CHAR (1/29)
--------------------------------------------------------------------------
mpirun noticed that process rank 4 with PID 31065 on node boo31 exited on signal 11 (Segmentation fault).
```

Here's the bt from the corefile:

```
(gdb) bt
#0  0x00007fd657ee6150 in ?? ()
#1  <signal handler called>
#2  opal_memory_ptmalloc2_int_free (av=0x7fd65db44c00, mem=<value optimized out>) at malloc.c:4401
#3  0x00007fd65d882023 in opal_memory_ptmalloc2_free (mem=0x1fa9e20) at malloc.c:3511
#4  0x00007fd657915577 in ompi_coll_tuned_allgather_intra_bruck (sbuf=<value optimized out>, scount=33201713, sdtype=<value optimized out>, rbuf=0x7fd650d16051, rcount=<value optimized out>,
    rdtype=0x1f9f820, comm=0x6669e0, module=0x1ea0d00) at coll_tuned_allgather.c:200
#5  0x00007fd65d7adf97 in PMPI_Allgather (sendbuf=0x1, sendcount=0, sendtype=0x6663e0, recvbuf=0x7fd650d16051, recvcount=1000, recvtype=<value optimized out>, comm=0x6669e0) at pallgather.c:117
#6  0x000000000040ac9c in tst_coll_allgather_in_place_run (env=0x7fffba7f7770) at coll/tst_coll_allgather_in_place.c:66
#7  0x0000000000447df0 in tst_test_run_func (env=0x7fffba7f7770) at tst_tests.c:1455
#8  0x000000000041cb4a in main (argc=5, argv=0x7fffba7f7a38) at mpi_test_suite.c:639
```

**Comment by bosilca** [comment]
All tests pass with 3.1, 4.0 and master.
