### ISSUE TITLE
2.0.0: hello_oshmem segv's in oshmem_init()

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1919]
Running with the v2.0.0 tarball or a 2.x head default build segv's with `hello_oshmem`:

```
# SLURM allocation of 4 servers
$ mpirun --mca btl tcp,vader,self hello_oshmem 
...segv output...

$ gdb hello_oshmem core.hello_oshmem-mpi005-19647
...gdb init output...
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00002aaac0d8574f in mca_spml_yoda_add_procs () from /home/jsquyres/bogus/lib/openmpi/mca_spml_yoda.so
[Current thread is 1 (Thread 0x2aaaab8abaa0 (LWP 19647))]
(gdb) bt
#0  0x00002aaac0d8574f in mca_spml_yoda_add_procs () from /home/jsquyres/bogus/lib/openmpi/mca_spml_yoda.so
#1  0x00002aaaaaad65cd in oshmem_shmem_init () from /home/jsquyres/bogus/lib/liboshmem.so.20
#2  0x00002aaaaaad8fc4 in shmem_init () from /home/jsquyres/bogus/lib/liboshmem.so.20
#3  0x0000000000400925 in main (argc=1, argv=0x7fffffffbfc8) at hello_oshmem_c.c:25
```

@jladd-mlnx Can you have a look?  This feels like a blocker for v2.0.1.

A user just reported this on the mailing list, too: https://www.mail-archive.com/users@lists.open-mpi.org/msg00009.html

**Comment by ggouaillardet** [comment]
fwiw, I was unable to reproduce this with a machinefile and no RM
can you confirm this is SLURM or RM related ?

**Comment by jsquyres** [comment]
I was running in a SLURM job, so I guess it was related to that...?
