### ISSUE TITLE
Calling MPI_T_init_thread before MPI_Init causes SEGV

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#197]
I ran this test against the trunk.  Strange error when we call MPI_T_init_thread first.

mpirun -np 1 simple_tool_test

```
Program received signal SIGSEGV, Segmentation fault.
0x0000000001188030 in ?? ()
(gdb) where
#0  0x0000000001188030 in ?? ()
#1  0x00007f641ca27c8a in opal_obj_run_constructors (object=0x7f641ccbf280)
    at ../../../opal/class/opal_object.h:424
#2  0x00007f641ca27d6b in opal_malloc_init () at ../../../opal/util/malloc.c:63
#3  0x00007f641c9db269 in opal_init_util (pargc=0x7fffa0c26a3c, pargv=0x7fffa0c26a30)
    at ../../opal/runtime/opal_init.c:258
#4  0x00007f641e13a665 in ompi_mpi_init (argc=1, argv=0x7fffa0c26c58, requested=0, provided=0x7fffa0c26b28)
    at ../../ompi/runtime/ompi_mpi_init.c:398
#5  0x00007f641e16f8d6 in PMPI_Init (argc=0x7fffa0c26b6c, argv=0x7fffa0c26b60) at pinit.c:84
#6  0x0000000000400c6a in main (argc=1, argv=0x7fffa0c26c58) at simple_tool_test.c:16
(gdb) 
```

**Comment by hppritcha** [comment]
this problem has gotten fixed at some point.  we have tests in ompi-tests private that test this and they pass.
