### ISSUE TITLE
Getting Segmentation fault when run OpenFoam with openib on aarch64

### ISSUE THREAD

**Issue by rishards** [open-mpi/ompi#3145]
Recently I have been testing OpenFoam with openib on **aarch64**, and get a segmentation fault:
```
__kernel_rt_sigreturn
[node5:45736] *** Process received signal ***
[node5:45736] Signal: Segmentation fault (11)
[node5:45736] Signal code:  (-6)
[node5:45736] Failing at address: 0xb2a8
[node5:45736] [ 0] linux-vdso.so.1(__kernel_rt_sigreturn+0x0)[0x4000048f1500]
[node5:45736] [ 1] /usr/lib64/libc.so.6(gsignal+0x38)[0x400007ed08f0]
[node5:45736] [ 2] linux-vdso.so.1(__kernel_rt_sigreturn+0x0)[0x4000048f1500]
[node5:45736] *** End of error message ***
```
the core dump backtrace:
```#1  <signal handler called>         
#2  0x0000000000000000 in ?? ()                
#3  0x000040003af1c5f8 in btl_openib_handle_incoming (openib_btl=0x799b9d0, ep=0x7e116b0,          frag=0x825e030, byte_len=218) at btl_openib_component.c:3103 
#4  0x000040003af1ddac in progress_one_device (device=0x7990a90) at btl_openib_component.c:3736
#5  0x000040003af1df38 in btl_openib_component_progress () at btl_openib_component.c:3768
#6  0x0000400038c57d48 in opal_progress () at runtime/opal_progress.c:222
#7  0x00004000384a701c in sync_wait_st (sync=0xffffe52a3048) at ../opal/threads/wait_sync.h:82
#8  0x00004000384a79c0 in ompi_request_default_wait_all (count=12, requests=0x7e2af20, statuses=0x0) at request/req_wait.c:237
#9  0x0000400038527d10 in PMPI_Waitall (count=12, requests=0x7e2af20, statuses=0x0) at pwaitall.c:77
#10 0x00004000376df128 in Foam::UPstream::waitRequests(int) () from /home/OpenFOAM-4.1/platforms/linuxAArch64GccDPInt32Opt/lib/openmpi-system/libPstream.so
#11 0x0000400036e40bd4 in Foam::lduMatrix::updateMatrixInterfaces(Foam::FieldField<Foam::Field, double> const&, Foam::UPtrList<Foam::lduInterfaceField const> const&, Foam::Field<double> const&, Foam::Field<double>&, unsigned char) const () from /home/OpenFOAM-4.1/platforms/linuxAArch64GccDPInt32Opt/lib/libOpenFOAM.so
#12 0x0000400036e4ee28 in Foam::GaussSeidelSmoother::smooth(Foam::word const&, Foam::Field<double>&, Foam::lduMatrix const&, Foam::Field<double> const&, Foam::FieldField<Foam::Field, double> const&, Foam::UPtrList<Foam::lduInterfaceField const> const&, unsigned char, int) () from /home/OpenFOAM-4.1/platforms/linuxAArch64GccDPInt32Opt/lib/libOpenFOAM.so
#13 0x0000400036e6b1d4 in Foam::GAMGSolver::Vcycle(Foam::PtrList<Foam::lduMatrix::smoother> const&, Foam::Field<double>&, Foam::Field<double> const&, Foam::Field<double>&, Foam::Field<double>&, Foam::Field<double>&, Foam::Field<double>&, Foam::Field<double>&, Foam::PtrList<Foam::Field<double> >&, Foam::PtrList<Foam::Field<double> >&, unsigned char) const ()
   from /home/OpenFOAM-4.1/platforms/linuxAArch64GccDPInt32Opt/lib/libOpenFOAM.so
#14 0x0000400036e6caec in Foam::GAMGSolver::solve(Foam::Field<double>&, Foam::Field<double> const&, unsigned char) const ()
   from /home/OpenFOAM-4.1/platforms/linuxAArch64GccDPInt32Opt/lib/libOpenFOAM.so
#15 0x0000400035010180 in Foam::fvMatrix<double>::solveSegregated(Foam::dictionary const&) () from /home/OpenFOAM-4.1/platforms/linuxAArch64GccDPInt32Opt/lib/libfiniteVolume.so
#16 0x000000000046728c in Foam::fvMatrix<double>::solve (this=this@entry=0xffffe52a4b10, solverControls=...) at /home/OpenFOAM-4.1/src/finiteVolume/lnInclude/fvMatrixSolve.C:82
#17 0x0000000000467520 in Foam::fvMatrix<double>::solve (this=this@entry=0xffffe52a4b10) at /home/OpenFOAM-4.1/src/finiteVolume/lnInclude/fvMatrixSolve.C:325
#18 0x0000000000423100 in main (argc=<optimized out>, argv=<optimized out>) at pEqn.H:33
```
I found that the **reg->cbfunc=0x00**,so i print the value of hdr->tag,and found **the value of hdr->tag** just changed around the line.

tag before:0x2
tag after:0x41    
```
int tag_before = hdr->tag;
#if OPAL_CUDA_SUPPORT /* CUDA_ASYNC_RECV */
        /* The COPY_ASYNC flag should not be set */
        assert(0 == (des->des_flags & MCA_BTL_DES_FLAGS_CUDA_COPY_ASYNC));
#endif /* OPAL_CUDA_SUPPORT */
        reg = mca_btl_base_active_message_trigger + hdr->tag;

        if(reg->cbfunc==0){
                printf("tag before:%x\n",tag_before);
                printf("tag after:%x\n",hdr->tag);
        }
        reg->cbfunc( &openib_btl->super, hdr->tag, des, reg->cbdata ); 
```
Version of Openmpi:Master
Version of Openfoam:4.1
The example : /tutorials/incompressible/simpleFoam/motorBike/ 
The command: mpirun -mca btl openib,sm,self  -np 6 --hostfile mfile snappyHexMesh/simpleFoam -overwrite –parallel

Have someone met this before,i hope to get some help!

**Comment by hppritcha** [comment]
Do you know how your OpenMPI was configured?  Could you post the output of ```ompi_info```?

**Comment by rishards** [comment]
@rhc54 @hppritcha @jsquyres Can someone please take a look ?

**Comment by jsquyres** [comment]
@shamisp ARM: Can you have a look at this?
