### ISSUE TITLE
v2.x: oshmem tests keep running after oshrun is killed

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#3256]
Reported a similar issue on master / v3.x in #3225.

It looks like I'm seeing a similar issue on v2.x Cisco MTT runs: OSHMEM tests are hanging / not dying.  If the issue is the same (which it may not be, because the version of PMIx is different between master+v3.x and v2.x), back-porting the following two commits on master may be sufficient:

* 55e4fba5f5633d08b283c247301c17926c4f5b6b
* 7dd34d0c9a58c50f47295d866e675dcda91a5e07

**Comment by rhc54** [comment]
The error for 7dd34d0 does not exist on the PMIx v1.2 code branch

**Comment by jsquyres** [comment]
This issue appears nominally similar to #3225, but the symptoms appear to be somewhat different (the PMIx code is quite different between OMPI master and v2.x). In this case, the hung processes do not have a thread that is stuck in PMIx_Abort.  Hence, I'm changing the title of this issue to "oshmem tests keep running after oshrun is killed".

@artpol84 Per our discussion yesterday, this should hopefully give you enough information to replicate.

The UH OSHMEM tests (https://github.com/openshmem-org/tests-uh) have a bunch of tests that are designed to hang.  In each directory in the UH OSHMEM tests, there's a `test_parameters.conf` CSV file that indicates several things about each test: how many procs to run, what the expected result is, ...etc.  For example, in `feature_tests/Fortran/broadcast`, the `test_parameters.conf` file has the following lines about the `*_05_*` tests in that directory:

```
test_shmem_broadcast_05_int4.x, 3, Broadcast fails when not all PEs call broadcast at the same point of the execution,,5,Timeout
test_shmem_broadcast_05_int8.x, 3, Broadcast fails when not all PEs call broadcast at the same point of the execution,,5,Timeout
test_shmem_broadcast_05_real4.x, 3, Broadcast fails when not all PEs call broadcast at the same point of the execution,,5,Timeout
test_shmem_broadcast_05_real8.x, 3, Broadcast fails when not all PEs call broadcast at the same point of the execution,,5,Timeout
test_shmem_broadcast_05_double.x, 3, Broadcast fails when not all PEs call broadcast at the same point of the execution,,5,Timeout
test_shmem_broadcast_05_char.x, 3, Broadcast fails when not all PEs call broadcast at the same point of the execution,,5,Timeout
test_shmem_broadcast_05_logical.x, 3, Broadcast fails when not all PEs call broadcast at the same point of the execution,,5,Timeout
```

Note the last token -- `Timeout`.  This indicates that the test is *supposed* to hang.  I.e., if that test hangs, then the test *passes* (because it's *supposed* to hang).

To invoke these tests, you are supposed to use the `common/testrunner.pl` script.  Cisco's MTT is invoking:

```
export RUN_OPTIONS="--map-by node ...other_mca_params..."
&test_build_dir()/common/testrunner.pl &test_executable_basename()
```

Which basically gets evaluated as:

```
export RUN_OPTIONS="--map-by node --mca btl vader,tcp,self"
/path/to/mtt/test/uh-oshmem-tests/build/dir/common/testrunner.pl test_shmem_broadcast_05_char.x
```

`testrun.pl` then:

1. forks a child thread for monitoring purposes
1. the child thread then fork/execs `oshrun` with the `--map-by node ... test_shmem_broadcast_05_char.x`.
1. after a timeout, the child kills `oshrun` with `SIGKILL` and then notifies the parent that the child died badly, and then exits itself
1. the parent receives the message that the grandchild timedout, and therefore rules the test a success (because the grandchild was *supposed* to hang), and exits

At this point, `testrunner.pl` is dead and `oshrun` is dead.  But some/all of the OSHMEM executables still remain.

I do not know offhand if the OSHMEM processes that remain are local to `oshrun` or were remote / forked by an `orted`.

I am running all of these tests on a pair of 16-core Sandy bridge machines, allocated by SLURM.  I sbatch a script that invokes `mtt --test-run ...` and ultimately invokes `testrunner.pl ...` as described above.  I.e., I am *not* using direct launch -- I'm using `oshrun` and the SLURM PLM, etc.

Here's typical stack traces in the OSHMEM tests that are left (from a hung `test_shmem_broadcast_05_char.x`):

## Thread 1: app thread (it is spinning endlessly)

```
#0  0x00000035f4adf343 in poll () from /lib64/libc.so.6
#1  0x00002aaaac121925 in poll_dispatch (base=0x641a20, tv=0x7fffffffc900)
    at poll.c:165
#2  0x00002aaaac116603 in opal_libevent2022_event_base_loop (base=0x641a20, 
    flags=3) at event.c:1630
#3  0x00002aaaac067c8a in opal_progress () at runtime/opal_progress.c:207
#4  0x00002aaaab01f02b in ompi_request_wait_completion (req=0x7863f0)
    at ../ompi/request/request.h:392
#5  0x00002aaaab01f7f2 in ompi_comm_nextcid (newcomm=0x7bdb80, 
    comm=0x2aaaab4bea80 <ompi_mpi_comm_world>, bridgecomm=0x0, 
    arg0=0x7fffffffca7c, arg1=0x0, send_first=false, mode=512)
    at communicator/comm_cid.c:292
#6  0x00002aaaab01ce92 in ompi_comm_create_group (
    comm=0x2aaaab4bea80 <ompi_mpi_comm_world>, group=0x7bdb10, tag=1, 
    newcomm=0x7fffffffcac8) at communicator/comm.c:1199
#7  0x00002aaaaab2de1d in mca_scoll_mpi_comm_query (osh_group=0x7b5b60, 
    priority=0x7fffffffcbd8) at scoll_mpi_module.c:146
#8  0x00002aaaaab2c9ab in query_1_0_0 (
    component=0x2aaaaad5e880 <mca_scoll_mpi_component>, group=0x7b5b60, 
    priority=0x7fffffffcbd8, module=0x7fffffffcc00)
    at base/scoll_base_select.c:380
#9  0x00002aaaaab2c96f in query (
    component=0x2aaaaad5e880 <mca_scoll_mpi_component>, group=0x7b5b60, 
    priority=0x7fffffffcbd8, module=0x7fffffffcc00)
    at base/scoll_base_select.c:363
#10 0x00002aaaaab2c844 in check_one_component (group=0x7b5b60, 
    component=0x2aaaaad5e880 <mca_scoll_mpi_component>, module=0x7fffffffcc00)
    at base/scoll_base_select.c:325
#11 0x00002aaaaab2c696 in check_components (
    components=0x2aaaaad5e710 <oshmem_scoll_base_framework+80>, group=0x7b5b60)
    at base/scoll_base_select.c:290
#12 0x00002aaaaab2b684 in mca_scoll_base_select (group=0x7b5b60)
    at base/scoll_base_select.c:210
#13 0x00002aaaaaad713e in oshmem_proc_group_create (pe_start=0, pe_stride=1, 
    pe_size=3) at proc/proc.c:197
#14 0x00002aaaaab1a66f in shmem_broadcast4_f (target=6296912, source=6296896, 
    nlong=0x401024, PE_root=0x401020, PE_start=0x401020, logPE_stride=0x401020, 
    PE_size=0x7fffffffd090, pSync=6296832) at pshmem_broadcast_f.c:134
#15 0x00002aaaaab1a295 in pshmem_broadcast4_ (target=6296912, source=6296896, 
    nlong=0x401024, PE_root=0x401020, PE_start=0x401020, logPE_stride=0x401020, 
    PE_size=0x7fffffffd090, pSync=6296832) at pshmem_broadcast_f.c:30
#16 0x0000000000400ce1 in test_shmem_broadcast ()
    at test_shmem_broadcast_05_char.f90:84
#17 0x0000000000400eee in main (argc=1, argv=0x7fffffffd6db)
    at test_shmem_broadcast_05_char.f90:111
#18 0x00000035f4a1ed1d in __libc_start_main () from /lib64/libc.so.6
#19 0x0000000000400a89 in _start ()
```

## Thread 2

```
#0  0x00000035f4ae9163 in epoll_wait () from /lib64/libc.so.6
(gdb) bt
#0  0x00000035f4ae9163 in epoll_wait () from /lib64/libc.so.6
#1  0x00002aaaac112a33 in epoll_dispatch (base=0x677e20, tv=0x0) at epoll.c:407
#2  0x00002aaaac116603 in opal_libevent2022_event_base_loop (base=0x677e20, 
    flags=1) at event.c:1630
#3  0x00002aaaac1c61e9 in progress_engine (obj=0x677e20)
    at src/util/progress_threads.c:52
#4  0x00000035f4e079d1 in start_thread () from /lib64/libpthread.so.0
#5  0x00000035f4ae8b6d in clone () from /lib64/libc.so.6
```

## Thread 3

```
#0  0x00000035f4adf343 in poll () from /lib64/libc.so.6
#1  0x00002aaaac121925 in poll_dispatch (base=0x679260, tv=0x2aaaace8ce50)
    at poll.c:165
#2  0x00002aaaac116603 in opal_libevent2022_event_base_loop (base=0x679260, 
    flags=1) at event.c:1630
#3  0x00002aaaac06d4ab in progress_engine (obj=0x678b88)
    at runtime/opal_progress_threads.c:105
#4  0x00000035f4e079d1 in start_thread () from /lib64/libpthread.so.0
#5  0x00000035f4ae8b6d in clone () from /lib64/libc.so.6
```

## Other characteristics about the process

All OMPI env vars from /proc/PID/env (note `pmix_base_async_modex`):

```
OMPI_APP_CTX_NUM_PROCS=3
OMPI_COMMAND=test_shmem_broadcast_05_char.x
OMPI_COMM_WORLD_LOCAL_RANK=1
OMPI_COMM_WORLD_LOCAL_SIZE=2
OMPI_COMM_WORLD_NODE_RANK=1
OMPI_COMM_WORLD_RANK=2
OMPI_COMM_WORLD_SIZE=3
OMPI_FILE_LOCATION=/tmp/openmpi-sessions-1001@mpi016_0/1188/1/2
OMPI_FIRST_RANKS=0
OMPI_MCA_async_mpi_init=1
OMPI_MCA_btl=vader,tcp,self
OMPI_MCA_ess_base_jobid=77856769
OMPI_MCA_ess_base_vpid=2
OMPI_MCA_ess=pmi
OMPI_MCA_initial_wdir=/home/mpiteam/scratches/community/2017-03-29cron/qHnM/instal\
ls/MMw0/tests/oshmem/tests-uh.git/feature_tests/Fortran/broadcast
OMPI_MCA_mpi_yield_when_idle=0
OMPI_MCA_oob=tcp
OMPI_MCA_orte_app_num=0
OMPI_MCA_orte_bound_at_launch=1
OMPI_MCA_orte_ess_node_rank=1
OMPI_MCA_orte_ess_num_procs=3
OMPI_MCA_orte_hnp_uri=77856768.0;tcp://10.0.8.16,10.10.0.16,10.2.0.16,10.3.0.16:47\
677
OMPI_MCA_orte_launch=1
OMPI_MCA_orte_local_daemon_uri=77856768.0;tcp://10.0.8.16,10.10.0.16,10.2.0.16,10.\
3.0.16:47677
OMPI_MCA_orte_num_nodes=2
OMPI_MCA_orte_precondition_transports=e35de111f8a81b06-62f7c8152a81d30f
OMPI_MCA_orte_tmpdir_base=/tmp
OMPI_MCA_pmix_base_async_modex=1
OMPI_MCA_pmix=^s1,s2,cray
OMPI_MCA_rmaps_base_mapping_policy=node
OMPI_MCA_shmem_RUNTIME_QUERY_hint=mmap
OMPI_NUM_APP_CTX=1
OMPI_UNIVERSE_SIZE=32
OPAL_OUTPUT_STDERR_FD=35
```

**Comment by jsquyres** [comment]
@artpol84 I'm returning to the office from vacation tomorrow, but I just logged into Cisco's MTT systems and I see that this issue is still occurring.  Any progress?

**Comment by artpol84** [comment]
@jsquyres, sorry - it was a busy weeks. We will try to return to this asap (this week)

**Comment by artpol84** [comment]
@karasevb please, take a look.

**Comment by jsquyres** [comment]
@artpol84 @karasevb Any news?  This is still a large problem.  Thanks!

**Comment by jsquyres** [comment]
@artpol84 @karasevb Any news? This is still a large problem. Thanks!

**Comment by artpol84** [comment]
@jsquyres 
Jeff, sorry for the long silence. Is this still a problem?

**Comment by artpol84** [comment]
Sounds like it was fixed. Reopen if need.
