### ISSUE TITLE
make check failure on ppc64

### ISSUE THREAD

**Issue by adrianreber** [open-mpi/ompi#371]
There have been two reports that make check fails on ppc64. One on my system and one from Christopher Samuel: http://www.open-mpi.org/community/lists/devel/2015/02/16872.php

My MTT error log: http://mtt.open-mpi.org/index.php?do_redir=2229

and GDB backtrace
```
Core was generated by `/home/adrian/mtt-scratch/mpi-install/QMjb/src/openmpi-dev-750-gff7be58/test/cla'.                                            
Program terminated with signal SIGSEGV, Segmentation fault.                                                                                         
#0  0x0000000010001438 in opal_atomic_swap_32 (addr=0x38, newval=1) at ../../opal/include/opal/sys/atomic_impl.h:51                                 
51              old = *addr;                                                                                                                        
Missing separate debuginfos, use: debuginfo-install glibc-2.20-5.fc21.ppc64                                                                         
(gdb) bt                                                                                                                                            
#0  0x0000000010001438 in opal_atomic_swap_32 (addr=0x38, newval=1) at ../../opal/include/opal/sys/atomic_impl.h:51                                 
#1  0x00000000100018b8 in opal_lifo_pop_atomic (lifo=0x3fffd6ed2da0) at ../../opal/class/opal_lifo.h:193                                            
#2  0x0000000010001a9c in thread_test (arg=0x3fffd6ed2da0) at opal_lifo.c:50                                                                        
#3  0x00003fff98a7ba64 in .start_thread () from /lib64/libpthread.so.0                                                                              
#4  0x00003fff989a09b4 in .__clone () from /lib64/libc.so.6
```
This error is not easy to reproduce on my system. Most of the time it works.

This is Christopher's error log: http://www.open-mpi.org/community/lists/devel/att-16872/opal-lifo-stack.log

I assume this could be for @hjelmn

**Comment by hjelmn** [comment]
Yup. Will look into this today.

**Comment by hjelmn** [comment]
298f238 should fix the issue. Please close the issue if it does.

**Comment by adrianreber** [comment]
As this was not easily reproducible I am closing it for now. If it happens again I will re-open it. Thanks.
