### ISSUE TITLE
v3.0.x: PMIx v1.2 external doesn't work with v3.0.x

### ISSUE THREAD

**Issue by karasevb** [open-mpi/ompi#3977]
The problem reproduced with v3.0.x and PMIx v1.2 as external component and`hello_c` program.

There is a hang when the client is trying to request a key from the server:
```
(gdb) bt
#0  0x00007f8e9378ff3d in nanosleep () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f8e937c14a4 in usleep (useconds=<optimized out>) at ../sysdeps/unix/sysv/linux/usleep.c:32
#2  0x00007f8e90748997 in PMIx_Get (proc=0x7ffd021e0a10, key=0x7f8e913b21bf "pmix.appnum", info=0x0, ninfo=0, val=0x7ffd021e0a00) at src/client/pmix_client_get.c:104
#3  0x00007f8e909a3cae in pmix1_get () from /home/user/ompi/v3.0.x/v1.2_ext/install/lib/openmpi/mca_pmix_ext1x.so
#4  0x00007f8e913b13c8 in rte_init () from /home/user/ompi/v3.0.x/v1.2_ext/install/lib/openmpi/mca_ess_singleton.so
#5  0x00007f8e93437929 in orte_init () from /home/user/ompi/v3.0.x/v1.2_ext/install/lib/libopen-rte.so.40
#6  0x00007f8e93cffa75 in ompi_mpi_init () from /home/user/ompi/v3.0.x/v1.2_ext/install/lib/libmpi.so.40
#7  0x00007f8e93d21deb in PMPI_Init () from /home/user/ompi/v3.0.x/v1.2_ext/install/lib/libmpi.so.40
#8  0x00000000004009ae in main ()
```

**Comment by karasevb** [comment]
@artpol84

**Comment by hppritcha** [comment]
This is a known limitation.  We'll make sure its documented.

**Comment by artpol84** [comment]
@hppricha, we need 1.2 working in 3.0. It seems that I missed the decision of making this problem just a "known limitation".

**Comment by bwbarrett** [comment]
We won't hold 3.0.0rc2 (which has already been cut, will be released today), but I think it's reasonable to pull these in for 3.0.0, assuming @rhc54 is on board.

**Comment by artpol84** [comment]
Sounds good.

**Comment by jladd-mlnx** [comment]
@karasevb @artpol84 please close the issue once satisfied that it's working.

**Comment by artpol84** [comment]
Yes, it's working now.
