### ISSUE TITLE
MPI_testany() returns flag=1 and index=undefined

### ISSUE THREAD

**Issue by miked-mellanox** [open-mpi/ompi#402]
Intel test fails with segv:

``` shell
$mpirun  -np 10  --map-by node --display-map --report-bindings -mca coll_fca_enable 0   MPI_Testany_c
 Data for JOB [852,1] offset 0

 ========================   JOB MAP   ========================

 Data for node: boo11   Num slots: 8    Max slots: 0    Num procs: 2
        Process OMPI jobid: [852,1] App: 0 Process rank: 0
        Process OMPI jobid: [852,1] App: 0 Process rank: 8

 Data for node: boo12   Num slots: 8    Max slots: 0    Num procs: 2
        Process OMPI jobid: [852,1] App: 0 Process rank: 1
        Process OMPI jobid: [852,1] App: 0 Process rank: 9

 Data for node: boo13   Num slots: 8    Max slots: 0    Num procs: 1
        Process OMPI jobid: [852,1] App: 0 Process rank: 2

 Data for node: boo14   Num slots: 8    Max slots: 0    Num procs: 1
        Process OMPI jobid: [852,1] App: 0 Process rank: 3

 Data for node: boo15   Num slots: 8    Max slots: 0    Num procs: 1
        Process OMPI jobid: [852,1] App: 0 Process rank: 4

 Data for node: boo16   Num slots: 8    Max slots: 0    Num procs: 1
        Process OMPI jobid: [852,1] App: 0 Process rank: 5

 Data for node: boo17   Num slots: 8    Max slots: 0    Num procs: 1
        Process OMPI jobid: [852,1] App: 0 Process rank: 6

 Data for node: boo21   Num slots: 8    Max slots: 0    Num procs: 1
        Process OMPI jobid: [852,1] App: 0 Process rank: 7

 =============================================================
[boo15:15989] MCW rank 4 bound to socket 0[core 0[hwt 0]]: [B/././.][./././.]
[boo14:27542] MCW rank 3 bound to socket 0[core 0[hwt 0]]: [B/././.][./././.]
[boo21:20163] MCW rank 7 bound to socket 0[core 0[hwt 0]]: [B/././.][./././.]
[boo12:17404] MCW rank 1 bound to socket 0[core 0[hwt 0]]: [B/././.][./././.]
[boo12:17404] MCW rank 9 bound to socket 0[core 1[hwt 0]]: [./B/./.][./././.]
[boo11:18580] MCW rank 0 bound to socket 0[core 0[hwt 0]]: [B/././.][./././.]
[boo11:18580] MCW rank 8 bound to socket 0[core 1[hwt 0]]: [./B/./.][./././.]
[boo16:30034] MCW rank 5 bound to socket 0[core 0[hwt 0]]: [B/././.][./././.]
[boo13:25403] MCW rank 2 bound to socket 0[core 0[hwt 0]]: [B/././.][./././.]
[boo17:10741] MCW rank 6 bound to socket 0[core 0[hwt 0]]: [B/././.][./././.]
MPITEST info  (0): Starting:  MPI_Testany
MPITEST error (0): Non-zero return code ierr/flag (16384/1) from MPI_Testall on Isend, after 1 calls to MPI_Testany
MPITEST error (0): Non-zero return code ierr/flag (16384/1) from MPI_Testall on Isend, after 1 calls to MPI_Testany
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node boo11 exited on signal 11 (Segmentation fault).


#0  0x00007ffff249d1d0 in ?? ()
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.132.el6.x86_64 hcoll-3.1.690-1.x86_64 libgcc-4.4.7-4.el6.x86_64 libibmad-1.3.11.MLNX20140817.fad53c6-0.1.x86_64 libibumad-1.3.9.MLNX20140817.485ffa6-0.1.x86_64 libibverbs-1.1.8mlnx1-OFED.2.4.45.ga305acd.x86_64 libmlx4-1.0.6mlnx1-OFED.2.4.0.1.2.x86_64 libmlx5-1.0.1mlnx2-OFED.2.4.46.g727de14.x86_64 libnl-1.1.4-2.el6.x86_64 libpciaccess-0.13.1-2.el6.x86_64 librdmacm-1.0.19mlnx-OFED.2.4.28.g50d12b8.x86_64 libxml2-2.7.6-14.el6.x86_64 mxm-3.2.2990-1.x86_64 numactl-2.0.7-8.el6.x86_64 opensm-libs-4.3.0.MLNX20141222.713c9d5-0.1.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) bt
#0  0x00007ffff249d1d0 in ?? ()
#1  <signal handler called>
#2  0x00007ffff7cf5ac0 in PMPI_Test_cancelled (status=0x7ffffff3ba90, flag=0x7fffffffc918) at ptest_cancelled.c:59
#3  0x00000000004025f4 in main (argc=1, argv=0x7fffffffca38) at MPI_Testany_c.c:279
(gdb) f 3
#3  0x00000000004025f4 in main (argc=1, argv=0x7fffffffca38) at MPI_Testany_c.c:279
279             ierr = MPI_Test_cancelled(&send_stat[index], &flag);
(gdb) p flag
$1 = 1
(gdb) p one
one        one.10503  one.1683   one.1685   one.1688   one.2438   one.2530   one.2556   one_stat
(gdb) p one_stat
$2 = {MPI_SOURCE = -1, MPI_TAG = -1, MPI_ERROR = 0, _cancelled = 0, _ucount = 0}
(gdb) p index
$3 = -32766
(gdb) p send_loop_cnt
$4 = 1
(gdb) p ierr
$5 = 0
(gdb) quit
```

**Comment by bosilca** [comment]
MPI 3.0 page 58 line 39.

> The array may contain null or inactive handles. If the array contains no active handles then the call returns immediately with flag = true, index = MPI_UNDEFINED, and an empty status.

Can you please check if the requests are all completed in the testcase?

**Comment by miked-mellanox** [comment]
``` shell
(gdb) p **send_request
$10 = {super = {super = {super = {obj_magic_id = 16046253926196952813, obj_class = 0x7ffff7fbaa40, obj_reference_count = 1, cls_init_file_name = 0x7ffff7d63cc1 "request/request.c", cls_init_lineno = 111}, opal_list_next = 0x0,
      opal_list_prev = 0x0, item_free = 1, opal_list_item_refcount = 0, opal_list_item_belong_to = 0x0}, registration = 0x0, ptr = 0x0}, req_type = OMPI_REQUEST_NULL, req_status = {MPI_SOURCE = -1, MPI_TAG = -1, MPI_ERROR = 0,
    _cancelled = 0, _ucount = 0}, req_complete = true, req_state = OMPI_REQUEST_INACTIVE, req_persistent = false, req_f_to_c_index = 0, req_free = 0x7ffff7c89a29 <ompi_request_null_free>,
  req_cancel = 0x7ffff7c89a38 <ompi_request_null_cancel>, req_complete_cb = 0, req_complete_cb_data = 0x0, req_mpi_object = {comm = 0x617d00, file = 0x617d00, win = 0x617d00}}
```

**Comment by miked-mellanox** [comment]
all completed

``` shell
(gdb) set $i=0
(gdb) p send_request[$i++]->req_complete
$11 = true
(gdb) p send_request[$i++]->req_complete
$12 = true
(gdb) p send_request[$i++]->req_complete
$13 = true
(gdb) p send_request[$i++]->req_complete
$14 = true
(gdb) p send_request[$i++]->req_complete
$15 = true
(gdb) p send_request[$i++]->req_complete
$16 = true
...
(gdb) p send_request[$i++]->req_complete
$90 = true
```

**Comment by jsquyres** [comment]
To be clear, I think the *real* problem here is that MPI_Testall apparently returned != MPI_SUCCESS.  After that, any subsequent errors are just side effects.  Hence, looking at the results of MPI_Test_cancelled or MPI_Testany are just looking into what happened *after* the real error.

Can you re-run this through a debugger and stop when MPI_Testall is about to return an error?  That would be good to help specify the root cause.

**Comment by jsquyres** [comment]
Hah, and actually, apparently the printf is wrong -- it says "Non-zero return code ierr/flag (16384/1) from MPI_Testall on Isend..." but it's really after a call to *MPI_Testany* (I just pushed a printf fix to the ompi-tests git master).

Sooo... take my above remark as: "The *real* problem is that MPI_Testany apparently returned != MPI_SUCCESS..."

I asked for stopping in a debugger before MPI_Testany returns a failure because seeing the core file from then MPI_Test_cancelled segv'ed seems like a symptom, not the real cause.

**Comment by jsquyres** [comment]
@miked-mellanox Is this with yalla or ob1?

**Comment by miked-mellanox** [comment]
fails with both

**Comment by bosilca** [comment]
I can't reproduce it. I tried all combinations with ob1 (ib, vader, sm,
tcp,self) to no avail.

**Comment by miked-mellanox** [comment]
fixed with yalla patch.
unable to repro on ob1 now.
will reopen if reappear.
