### ISSUE TITLE
All tests fail with SEGV from ofi component

### ISSUE THREAD

**Issue by rolfv** [open-mpi/ompi#405]
Just did a build of the master and all my tests fail with SEGV.  Here is simple np=2 ibm test send.
```
[rvandevaart@drossetti-ivy4 pt2pt]$ mpirun -np 2 send
Sleep on 6254
Sleep on 6255

send:6255 terminated with signal 11 at PC=7f88c7cfa461 SP=7fffac6213d8.  Backtrace:
/lib64/libc.so.6(+0x81461)[0x7f88c7cfa461]
/lib64/libc.so.6(__strdup+0x16)[0x7f88c7cfa176]
/ivylogin/home/rvandevaart/ompi-repos/ompi-master-collbugs/64-dbg-nocuda/lib/openmpi/mca_mtl_ofi.so(+0x2bd6)[0x7f88bf79fbd6]
/ivylogin/home/rvandevaart/ompi-repos/ompi-master-collbugs/64-dbg-nocuda/lib/libmpi.so.0(ompi_mtl_base_select+0xb7)[0x7f88c82fa783]
/ivylogin/home/rvandevaart/ompi-repos/ompi-master-collbugs/64-dbg-nocuda/lib/openmpi/mca_pml_cm.so(+0x23e5)[0x7f88bfddb3e5]
/ivylogin/home/rvandevaart/ompi-repos/ompi-master-collbugs/64-dbg-nocuda/lib/libmpi.so.0(mca_pml_base_select+0x29c)[0x7f88c830a903]
/ivylogin/home/rvandevaart/ompi-repos/ompi-master-collbugs/64-dbg-nocuda/lib/libmpi.so.0(ompi_mpi_init+0x56a)[0x7f88c827ac87]
/ivylogin/home/rvandevaart/ompi-repos/ompi-master-collbugs/64-dbg-nocuda/lib/libmpi.so.0(MPI_Init+0x185)[0x7f88c82af752]
send[0x401115]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x7f88c7c97d1d]
send[0x400ff9]
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[43605,1],1]
  Exit code:    1
--------------------------------------------------------------------------
[rvandevaart@drossetti-ivy4 pt2pt]$ 
```

Here is stack trace
```
Program received signal SIGSEGV, Segmentation fault.
0x00007f3e8f8b4461 in __strlen_sse2 () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install infinipath-psm-3.1-364.1140_open.x86_64 libgcc-4.4.7-4.el6.x86_64 libibumad-1.3.9.MLNX20140817.485ffa6-0.1.x86_64 libibverbs-1.1.7mlnx1-OFED.2.3.100.g481c951.x86_64 libmlx4-1.0.5mlnx1-OFED.2.3.98.gb668608.x86_64 libmlx5-1.0.1mlnx1-OFED.2.3.90.g8f96155.x86_64 libnl-1.1.4-2.el6.x86_64 librdmacm-1.0.17.2mlnx3-OFED.2.3.93.ge488100.x86_64 opensm-libs-4.2.5.MLNX20140828.7f05469-0.1.x86_64
(gdb) where
#0  0x00007f3e8f8b4461 in __strlen_sse2 () from /lib64/libc.so.6
#1  0x00007f3e8f8b4176 in strdup () from /lib64/libc.so.6
#2  0x00007f3e87359bd6 in ompi_mtl_ofi_component_init (enable_progress_threads=false, enable_mpi_threads=false)
    at ../../../../../ompi/mca/mtl/ofi/mtl_ofi_component.c:165
#3  0x00007f3e8feb4783 in ompi_mtl_base_select (enable_progress_threads=false, enable_mpi_threads=false)
    at ../../../../ompi/mca/mtl/base/mtl_base_frame.c:74
#4  0x00007f3e879953e5 in mca_pml_cm_component_init (priority=0x7fff463431d0, enable_progress_threads=false, 
    enable_mpi_threads=false) at ../../../../../ompi/mca/pml/cm/pml_cm_component.c:154
#5  0x00007f3e8fec4903 in mca_pml_base_select (enable_progress_threads=false, enable_mpi_threads=false)
    at ../../../../ompi/mca/pml/base/pml_base_select.c:128
#6  0x00007f3e8fe34c87 in ompi_mpi_init (argc=1, argv=0x7fff463434e8, requested=0, provided=0x7fff46343308)
    at ../../ompi/runtime/ompi_mpi_init.c:618
#7  0x00007f3e8fe69752 in PMPI_Init (argc=0x7fff4634336c, argv=0x7fff46343360) at pinit.c:84
#8  0x0000000000401115 in main (argc=1, argv=0x7fff463434e8) at send.c:36
```

**Comment by jsquyres** [comment]
@yburette Can you have a look?

**Comment by rhc54** [comment]
I've got it - a trivial fix, will commit in a minute

**Comment by rhc54** [comment]
Fix committed: open-mpi/ompi@8b625c2

**Comment by jsquyres** [comment]
@rolfv Can you confirm that this fix works for you?  If so, please close the issue.  Thanks.

**Comment by rolfv** [comment]
Yes, this has fixed my issue.
