### ISSUE TITLE
Delete nspace causes segfaults in PMIx dstore

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#4296]
Looking at the updated OMPI master that includes the latest PMIx commit to delete nspace upon disconnect, we are getting segfaults in the ds12 component:
```
$ mpirun -H rhc001:24 --oversubscribe --bind-to none -n 3 -mca gds_base_verbose 1 ./intercomm_create
b: MPI_Intercomm_create( intra, 0, intra, MPI_COMM_NULL, 201, &inter) [rank 3]
b: MPI_Intercomm_create( intra, 0, intra, MPI_COMM_NULL, 201, &inter) [rank 4]
b: MPI_Intercomm_create( intra, 0, intra, MPI_COMM_NULL, 201, &inter) [rank 5]
a: MPI_Intercomm_create( ab_intra, 0, ac_intra, 3, 201, &inter) (0)
a: MPI_Intercomm_create( ab_intra, 0, ac_intra, 3, 201, &inter) (0)
c: MPI_Intercomm_create( MPI_COMM_WORLD, 0, intra, 0, 201, &inter) [rank 4]
c: MPI_Intercomm_create( MPI_COMM_WORLD, 0, intra, 0, 201, &inter) [rank 5]
a: MPI_Intercomm_create( ab_intra, 0, ac_intra, 3, 201, &inter) (0)
c: MPI_Intercomm_create( MPI_COMM_WORLD, 0, intra, 0, 201, &inter) [rank 3]
c: intercomm_create (0)
c: barrier on inter-comm - before
a: intercomm_create (0)
a: barrier on inter-comm - before
b: intercomm_create (0)
b: barrier on inter-comm - before
b: intercomm_create (0)
b: barrier on inter-comm - before
b: intercomm_create (0)
b: barrier on inter-comm - before
a: intercomm_create (0)
a: barrier on inter-comm - before
a: intercomm_create (0)
a: barrier on inter-comm - before
c: intercomm_create (0)
c: barrier on inter-comm - before
c: intercomm_create (0)
c: barrier on inter-comm - before
c: barrier on inter-comm - after
c: barrier on inter-comm - after
a: barrier on inter-comm - after
b: barrier on inter-comm - after
b: barrier on inter-comm - after
b: barrier on inter-comm - after
a: barrier on inter-comm - after
a: barrier on inter-comm - after
c: barrier on inter-comm - after
a: intercomm_merge(0) (0) [rank 2]
c: intercomm_merge(0) (0) [rank 7]
c: intercomm_merge(0) (0) [rank 8]
a: intercomm_merge(0) (0) [rank 1]
b: intercomm_merge(1) (0) [rank 4]
b: intercomm_merge(1) (0) [rank 5]
a: intercomm_merge(0) (0) [rank 0]
c: intercomm_merge(0) (0) [rank 6]
b: intercomm_merge(1) (0) [rank 3]
a: barrier (0)
c: barrier (0)
a: barrier (0)
b: barrier (0)
b: barrier (0)
b: barrier (0)
a: barrier (0)
c: barrier (0)
c: barrier (0)
intercomm_create: gds_dstore.c:2757: dstore_del_nspace: Assertion `((0xdeafbeedULL << 32) + 0xdeafbeedULL) == ((pmix_object_t *) (trk))->obj_magic_id' failed.
[rhc001:58370] *** Process received signal ***
intercomm_create: gds_dstore.c:2757: dstore_del_nspace: Assertion `((0xdeafbeedULL << 32) + 0xdeafbeedULL) == ((pmix_object_t *) (trk))->obj_magic_id' failed.
[rhc001:58371] *** Process received signal ***
[rhc001:58371] Signal: Aborted (6)
[rhc001:58371] Signal code:  (-6)
intercomm_create: gds_dstore.c:2757: dstore_del_nspace: Assertion `((0xdeafbeedULL << 32) + 0xdeafbeedULL) == ((pmix_object_t *) (trk))->obj_magic_id' failed.
[rhc001:58360] *** Process received signal ***
[rhc001:58360] Signal: Aborted (6)
[rhc001:58360] Signal code:  (-6)
intercomm_create: gds_dstore.c:2757: dstore_del_nspace: Assertion `((0xdeafbeedULL << 32) + 0xdeafbeedULL) == ((pmix_object_t *) (trk))->obj_magic_id' failed.
[rhc001:58361] *** Process received signal ***
[rhc001:58361] Signal: Aborted (6)
[rhc001:58361] Signal code:  (-6)
[rhc001:58361] [ 0] intercomm_create: gds_dstore.c:2757: dstore_del_nspace: Assertion `((0xdeafbeedULL << 32) + 0xdeafbeedULL) == ((pmix_object_t *) (trk))->obj_magic_id' failed.
[rhc001:58362] *** Process received signal ***
[rhc001:58362] Signal: Aborted (6)
[rhc001:58362] Signal code:  (-6)
intercomm_create: gds_dstore.c:2757: dstore_del_nspace: Assertion `((0xdeafbeedULL << 32) + 0xdeafbeedULL) == ((pmix_object_t *) (trk))->obj_magic_id' failed.
[rhc001:58369] *** Process received signal ***
[rhc001:58369] Signal: Aborted (6)
[rhc001:58369] Signal code:  (-6)
[rhc001:58370] Signal: Aborted (6)
[rhc001:58370] Signal code:  (-6)
[rhc001:58370] [ 0] /lib64/libpthread.so.0(+0xf370)[0x7f6f226bc370]
[rhc001:58370] [ 1] intercomm_create: gds_dstore.c:2757: dstore_del_nspace: Assertion `((0xdeafbeedULL << 32) + 0xdeafbeedULL) == ((pmix_object_t *) (trk))->obj_magic_id' failed.
[rhc001:58378] *** Process received signal ***
[rhc001:58378] Signal: Aborted (6)
[rhc001:58378] Signal code:  (-6)
intercomm_create: gds_dstore.c:2757: dstore_del_nspace: Assertion `((0xdeafbeedULL << 32) + 0xdeafbeedULL) == ((pmix_object_t *) (trk))->obj_magic_id' failed.
[rhc001:58379] *** Process received signal ***
[rhc001:58379] Signal: Aborted (6)
[rhc001:58379] Signal code:  (-6)
intercomm_create: gds_dstore.c:2757: dstore_del_nspace: Assertion `((0xdeafbeedULL << 32) + 0xdeafbeedULL) == ((pmix_object_t *) (trk))->obj_magic_id' failed.
[rhc001:58380] *** Process received signal ***
[rhc001:58380] Signal: Aborted (6)
[rhc001:58380] Signal code:  (-6)
[rhc001:58380] [ 0] /lib64/libpthread.so.0(+0xf370)[0x7f2c39252370]
[rhc001:58380] [ 1] /lib64/libc.so.6(gsignal+0x37)[0x7f2c38eb71d7]
[rhc001:58380] [ 2] /lib64/libc.so.6(abort+0x148)[0x7f2c38eb88c8]
[rhc001:58380] [ 3] /lib64/libc.so.6(+0x2e146)[0x7f2c38eb0146]
[rhc001:58380] [ 4] /lib64/libc.so.6(+0x2e1f2)[0x7f2c38eb01f2]
[rhc001:58380] [ 5] /home/common/openmpi/build/foobar/lib/pmix/mca_gds_ds12.so(+0xfcef)[0x7f2c35142cef]
[rhc001:58380] [ 6] /home/common/openmpi/build/foobar/lib/libpmix.so.0(OPAL_MCA_PMIX2X_PMIx_Disconnect_nb+0x1fa)[0x7f2c36008592]
[rhc001:58380] [ 7] /home/common/openmpi/build/foobar/lib/libpmix.so.0(OPAL_MCA_PMIX2X_PMIx_Disconnect+0x26a)[0x7f2c360080f6]
[rhc001:58380] [ 8] /home/common/openmpi/build/foobar/lib/openmpi/mca_pmix_pmix2x.so(pmix2x_disconnect+0x33b)[0x7f2c362fdd0e]
[rhc001:58380] [ 9] /home/common/openmpi/build/foobar/lib/libmpi.so.0(ompi_dpm_disconnect+0x491)[0x7f2c3a629388]
[rhc001:58380] [10] /home/common/openmpi/build/foobar/lib/libmpi.so.0(MPI_Comm_disconnect+0x14b)[0x7f2c3a66e008]
[rhc001:58380] [11] ./intercomm_create[0x40153b]
[rhc001:58380] [12] ./intercomm_create[0x400fbc]
[rhc001:58380] [13] /lib64/libc.so.6(__libc_start_main+0xf5)[0x7f2c38ea3b35]
[rhc001:58380] [14] ./intercomm_create[0x400c99]
[rhc001:58380] *** End of error message ***
[rhc001:58360] [ 0] /lib64/libpthread.so.0(+0xf370)[0x7fde9df90370]
[rhc001:58360] [ 1] /lib64/libc.so.6(gsignal+0x37)[0x7fde9dbf51d7]
[rhc001:58360] [ 2] /lib64/libc.so.6(abort+0x148)[0x7fde9dbf68c8]
[rhc001:58360] [ 3] /lib64/libc.so.6(+0x2e146)[0x7fde9dbee146]
[rhc001:58360] [ 4] /lib64/libc.so.6(+0x2e1f2)[0x7fde9dbee1f2]
[rhc001:58360] [ 5] /home/common/openmpi/build/foobar/lib/pmix/mca_gds_ds12.so(+0xfcef)[0x7fde99e80cef]
[rhc001:58360] [ 6] /home/common/openmpi/build/foobar/lib/libpmix.so.0(OPAL_MCA_PMIX2X_PMIx_Disconnect_nb+0x1fa)[0x7fde9ad46592]
[rhc001:58360] [ 7] /home/common/openmpi/build/foobar/lib/libpmix.so.0(OPAL_MCA_PMIX2X_PMIx_Disconnect+0x26a)[0x7fde9ad460f6]
[rhc001:58360] [ 8] /home/common/openmpi/build/foobar/lib/openmpi/mca_pmix_pmix2x.so(pmix2x_disconnect+0x33b)[0x7fde9b03bd0e]
[rhc001:58360] [ 9] /home/common/openmpi/build/foobar/lib/libmpi.so.0(ompi_dpm_disconnect+0x491)[0x7fde9f367388]
[rhc001:58360] [10] /home/common/openmpi/build/foobar/lib/libmpi.so.0(MPI_Comm_disconnect+0x14b)[0x7fde9f3ac008]
[rhc001:58360] [11] ./intercomm_create[0x4012f6]
[rhc001:58360] [12] ./intercomm_create[0x400fd2]
[rhc001:58360] [13] /lib64/libc.so.6(__libc_start_main+0xf5)[0x7fde9dbe1b35]
[rhc001:58360] [14] ./intercomm_create[0x400c99]
[rhc001:58360] *** End of error message ***
/lib64/libpthread.so.0(+0xf370)[0x7f40da98f370]
[rhc001:58361] [ 1] /lib64/libc.so.6(gsignal+0x37)[0x7f40da5f41d7]
[rhc001:58361] [ 2] /lib64/libc.so.6(abort+0x148)[0x7f40da5f58c8]
[rhc001:58361] [ 3] /lib64/libc.so.6(+0x2e146)[0x7f40da5ed146]
[rhc001:58361] [ 4] /lib64/libc.so.6(+0x2e1f2)[0x7f40da5ed1f2]
[rhc001:58361] [ 5] /home/common/openmpi/build/foobar/lib/pmix/mca_gds_ds12.so(+0xfcef)[0x7f40d687fcef]
[rhc001:58361] [ 6] /home/common/openmpi/build/foobar/lib/libpmix.so.0(OPAL_MCA_PMIX2X_PMIx_Disconnect_nb+0x1fa)[0x7f40d7745592]
[rhc001:58361] [ 7] /home/common/openmpi/build/foobar/lib/libpmix.so.0(OPAL_MCA_PMIX2X_PMIx_Disconnect+0x26a)[0x7f40d77450f6]
[rhc001:58361] [ 8] /home/common/openmpi/build/foobar/lib/openmpi/mca_pmix_pmix2x.so(pmix2x_disconnect+0x33b)[0x7f40d7a3ad0e]
[rhc001:58361] [ 9] /home/common/openmpi/build/foobar/lib/libmpi.so.0(ompi_dpm_disconnect+0x491)[0x7f40dbd66388]
[rhc001:58361] [10] /home/common/openmpi/build/foobar/lib/libmpi.so.0(MPI_Comm_disconnect+0x14b)[0x7f40dbdab008]
[rhc001:58361] [11] ./intercomm_create[0x4012f6]
[rhc001:58361] [12] ./intercomm_create[0x400fd2]
[rhc001:58361] [13] /lib64/libc.so.6(__libc_start_main+0xf5)[0x7f40da5e0b35]
[rhc001:58361] [14] ./intercomm_create[0x400c99]
[rhc001:58361] *** End of error message ***
[rhc001:58362] [ 0] /lib64/libpthread.so.0(+0xf370)[0x7fb1525c3370]
[rhc001:58362] [ 1] /lib64/libc.so.6(gsignal+0x37)[0x7fb1522281d7]
[rhc001:58362] [ 2] /lib64/libc.so.6(abort+0x148)[0x7fb1522298c8]
[rhc001:58362] [ 3] /lib64/libc.so.6(+0x2e146)[0x7fb152221146]
[rhc001:58362] [ 4] /lib64/libc.so.6(+0x2e1f2)[0x7fb1522211f2]
[rhc001:58362] [ 5] /home/common/openmpi/build/foobar/lib/pmix/mca_gds_ds12.so(+0xfcef)[0x7fb14e4b3cef]
[rhc001:58362] [ 6] /home/common/openmpi/build/foobar/lib/libpmix.so.0(OPAL_MCA_PMIX2X_PMIx_Disconnect_nb+0x1fa)[0x7fb14f379592]
[rhc001:58362] [ 7] /home/common/openmpi/build/foobar/lib/libpmix.so.0(OPAL_MCA_PMIX2X_PMIx_Disconnect+0x26a)[0x7fb14f3790f6]
[rhc001:58362] [ 8] /home/common/openmpi/build/foobar/lib/openmpi/mca_pmix_pmix2x.so(pmix2x_disconnect+0x33b)[0x7fb14f66ed0e]
[rhc001:58362] [ 9] /home/common/openmpi/build/foobar/lib/libmpi.so.0(ompi_dpm_disconnect+0x491)[0x7fb15399a388]
[rhc001:58362] [10] /home/common/openmpi/build/foobar/lib/libmpi.so.0(MPI_Comm_disconnect+0x14b)[0x7fb1539df008]
[rhc001:58362] [11] ./intercomm_create[0x4012f6]
[rhc001:58362] [12] ./intercomm_create[0x400fd2]
[rhc001:58362] [13] /lib64/libc.so.6(__libc_start_main+0xf5)[0x7fb152214b35]
[rhc001:58362] [14] ./intercomm_create[0x400c99]
[rhc001:58362] *** End of error message ***
[rhc001:58369] [ 0] /lib64/libpthread.so.0(+0xf370)[0x7f8fa4e83370]
[rhc001:58369] [ 1] /lib64/libc.so.6(gsignal+0x37)[0x7f8fa4ae81d7]
[rhc001:58369] [ 2] /lib64/libc.so.6(abort+0x148)[0x7f8fa4ae98c8]
[rhc001:58369] [ 3] /lib64/libc.so.6(+0x2e146)[0x7f8fa4ae1146]
[rhc001:58369] [ 4] /lib64/libc.so.6(+0x2e1f2)[0x7f8fa4ae11f2]
[rhc001:58369] [ 5] /home/common/openmpi/build/foobar/lib/pmix/mca_gds_ds12.so(+0xfcef)[0x7f8fa0d73cef]
[rhc001:58369] [ 6] /home/common/openmpi/build/foobar/lib/libpmix.so.0(OPAL_MCA_PMIX2X_PMIx_Disconnect_nb+0x1fa)[0x7f8fa1c39592]
[rhc001:58369] [ 7] /home/common/openmpi/build/foobar/lib/libpmix.so.0(OPAL_MCA_PMIX2X_PMIx_Disconnect+0x26a)[0x7f8fa1c390f6]
[rhc001:58369] [ 8] /home/common/openmpi/build/foobar/lib/openmpi/mca_pmix_pmix2x.so(pmix2x_disconnect+0x33b)[0x7f8fa1f2ed0e]
[rhc001:58369] [ 9] /lib64/libc.so.6(gsignal+0x37)[0x7f6f223211d7]
[rhc001:58370] [ 2] /lib64/libc.so.6(abort+0x148)[0x7f6f223228c8]
[rhc001:58370] [ 3] /lib64/libc.so.6(+0x2e146)[0x7f6f2231a146]
[rhc001:58370] [ 4] /lib64/libc.so.6(+0x2e1f2)[0x7f6f2231a1f2]
[rhc001:58370] [ 5] /home/common/openmpi/build/foobar/lib/pmix/mca_gds_ds12.so(+0xfcef)[0x7f6f1e5accef]
[rhc001:58370] [ 6] /home/common/openmpi/build/foobar/lib/libpmix.so.0(OPAL_MCA_PMIX2X_PMIx_Disconnect_nb+0x1fa)[0x7f6f1f472592]
[rhc001:58370] [ 7] /home/common/openmpi/build/foobar/lib/libpmix.so.0(OPAL_MCA_PMIX2X_PMIx_Disconnect+0x26a)[0x7f6f1f4720f6]
[rhc001:58370] [ 8] /home/common/openmpi/build/foobar/lib/openmpi/mca_pmix_pmix2x.so(pmix2x_disconnect+0x33b)[0x7f6f1f767d0e]
[rhc001:58370] [ 9] /home/common/openmpi/build/foobar/lib/libmpi.so.0(ompi_dpm_disconnect+0x491)[0x7f6f23a93388]
[rhc001:58370] [10] /home/common/openmpi/build/foobar/lib/libmpi.so.0(MPI_Comm_disconnect+0x14b)[0x7f6f23ad8008]
[rhc001:58370] [11] ./intercomm_create[0x40153b]
[rhc001:58370] [12] ./intercomm_create[0x400fbc]
[rhc001:58370] [13] /lib64/libc.so.6(__libc_start_main+0xf5)[0x7f6f2230db35]
[rhc001:58370] [14] ./intercomm_create[0x400c99]
[rhc001:58370] *** End of error message ***
[rhc001:58378] [ 0] /lib64/libpthread.so.0(+0xf370)[0x7efcd71a5370]
[rhc001:58378] [ 1] /lib64/libc.so.6(gsignal+0x37)[0x7efcd6e0a1d7]
[rhc001:58378] [ 2] /lib64/libc.so.6(abort+0x148)[0x7efcd6e0b8c8]
[rhc001:58378] [ 3] /lib64/libc.so.6(+0x2e146)[0x7efcd6e03146]
[rhc001:58378] [ 4] /lib64/libc.so.6(+0x2e1f2)[0x7efcd6e031f2]
[rhc001:58378] [ 5] /home/common/openmpi/build/foobar/lib/pmix/mca_gds_ds12.so(+0xfcef)[0x7efccf079cef]
[rhc001:58378] [ 6] /home/common/openmpi/build/foobar/lib/libpmix.so.0(OPAL_MCA_PMIX2X_PMIx_Disconnect_nb+0x1fa)[0x7efccfd2a592]
[rhc001:58378] [ 7] /home/common/openmpi/build/foobar/lib/libpmix.so.0(OPAL_MCA_PMIX2X_PMIx_Disconnect+0x26a)[0x7efccfd2a0f6]
[rhc001:58378] [ 8] /home/common/openmpi/build/foobar/lib/openmpi/mca_pmix_pmix2x.so(pmix2x_disconnect+0x33b)[0x7efcd4250d0e]
[rhc001:58378] [ 9] /home/common/openmpi/build/foobar/lib/libmpi.so.0(ompi_dpm_disconnect+0x491)[0x7efcd857c388]
[rhc001:58378] [10] /home/common/openmpi/build/foobar/lib/libmpi.so.0(MPI_Comm_disconnect+0x14b)[0x7efcd85c1008]
[rhc001:58378] [11] ./intercomm_create[0x40153b]
[rhc001:58378] [12] ./intercomm_create[0x400fbc]
[rhc001:58378] [13] /lib64/libc.so.6(__libc_start_main+0xf5)[0x7efcd6df6b35]
[rhc001:58378] [rhc001:58379] [ 0] /lib64/libpthread.so.0(+0xf370)[0x7f4d0dd0b370]
[rhc001:58379] [ 1] /lib64/libc.so.6(gsignal+0x37)[0x7f4d0d9701d7]
[rhc001:58379] [ 2] /lib64/libc.so.6(abort+0x148)[0x7f4d0d9718c8]
[rhc001:58379] [ 3] /lib64/libc.so.6(+0x2e146)[0x7f4d0d969146]
[rhc001:58379] [ 4] /lib64/libc.so.6(+0x2e1f2)[0x7f4d0d9691f2]
[rhc001:58379] [ 5] /home/common/openmpi/build/foobar/lib/pmix/mca_gds_ds12.so(+0xfcef)[0x7f4d09bfbcef]
[rhc001:58379] [ 6] /home/common/openmpi/build/foobar/lib/libpmix.so.0(OPAL_MCA_PMIX2X_PMIx_Disconnect_nb+0x1fa)[0x7f4d0aac1592]
[rhc001:58379] [ 7] /home/common/openmpi/build/foobar/lib/libpmix.so.0(OPAL_MCA_PMIX2X_PMIx_Disconnect+0x26a)[0x7f4d0aac10f6]
[rhc001:58379] [ 8] /home/common/openmpi/build/foobar/lib/openmpi/mca_pmix_pmix2x.so(pmix2x_disconnect+0x33b)[0x7f4d0adb6d0e]
[rhc001:58379] [ 9] /home/common/openmpi/build/foobar/lib/libmpi.so.0(ompi_dpm_disconnect+0x491)[0x7f4d0f0e2388]
[rhc001:58379] [10] /home/common/openmpi/build/foobar/lib/libmpi.so.0(MPI_Comm_disconnect+0x14b)[0x7f4d0f127008]
[rhc001:58379] [11] ./intercomm_create[0x40153b]
[rhc001:58379] [12] ./intercomm_create[0x400fbc]
[rhc001:58379] [13] [rhc001:58371] [ 0] /lib64/libpthread.so.0(+0xf370)[0x7fac6bca4370]
[rhc001:58371] [ 1] /lib64/libc.so.6(gsignal+0x37)[0x7fac6b9091d7]
[rhc001:58371] [ 2] /lib64/libc.so.6(abort+0x148)[0x7fac6b90a8c8]
[rhc001:58371] [ 3] /lib64/libc.so.6(+0x2e146)[0x7fac6b902146]
[rhc001:58371] [ 4] /lib64/libc.so.6(+0x2e1f2)[0x7fac6b9021f2]
[rhc001:58371] [ 5] /home/common/openmpi/build/foobar/lib/pmix/mca_gds_ds12.so(+0xfcef)[0x7fac639ebcef]
[rhc001:58371] [ 6] /home/common/openmpi/build/foobar/lib/libpmix.so.0(OPAL_MCA_PMIX2X_PMIx_Disconnect_nb+0x1fa)[0x7fac68a5a592]
[rhc001:58371] [ 7] /home/common/openmpi/build/foobar/lib/libpmix.so.0(OPAL_MCA_PMIX2X_PMIx_Disconnect+0x26a)[0x7fac68a5a0f6]
[rhc001:58371] [ 8] /home/common/openmpi/build/foobar/lib/openmpi/mca_pmix_pmix2x.so(pmix2x_disconnect+0x33b)[0x7fac68d4fd0e]
[rhc001:58371] [ 9] /home/common/openmpi/build/foobar/lib/libmpi.so.0(ompi_dpm_disconnect+0x491)[0x7fac6d07b388]
[rhc001:58371] [10] /home/common/openmpi/build/foobar/lib/libmpi.so.0(MPI_Comm_disconnect+0x14b)[0x7fac6d0c0008]
[rhc001:58371] [11] ./intercomm_create[0x40153b]
[rhc001:58371] [12] ./intercomm_create[0x400fbc]
[rhc001:58371] [13] /lib64/libc.so.6(__libc_start_main+0xf5)[0x7fac6b8f5b35]
[rhc001:58371] [14] ./intercomm_create[0x400c99]
[rhc001:58371] *** End of error message ***
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f4d0d95cb35]
[rhc001:58379] [14] ./intercomm_create[0x400c99]
[rhc001:58379] *** End of error message ***
/home/common/openmpi/build/foobar/lib/libmpi.so.0(ompi_dpm_disconnect+0x491)[0x7f8fa625a388]
[rhc001:58369] [10] /home/common/openmpi/build/foobar/lib/libmpi.so.0(MPI_Comm_disconnect+0x14b)[0x7f8fa629f008]
[rhc001:58369] [11] ./intercomm_create[0x40153b]
[rhc001:58369] [12] [14] ./intercomm_create[0x400c99]
[rhc001:58378] *** End of error message ***
./intercomm_create[0x400fbc]
[rhc001:58369] [13] /lib64/libc.so.6(__libc_start_main+0xf5)[0x7f8fa4ad4b35]
[rhc001:58369] [14] ./intercomm_create[0x400c99]
[rhc001:58369] *** End of error message ***
-------------------------------------------------------
Child job 2 terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 2 with PID 0 on node rhc001 exited on signal 6 (Aborted).
--------------------------------------------------------------------------
```
It looks like the _ns_track_array may not be getting initialized to NULL, or that the trackers in it are getting released too many times.

@karasevb @artpol84 Please take a look. You can find the intercomm_create code in orte/test/mpi.

**Comment by rhc54** [comment]
Here is the stacktrace - note that it is the client (not the server) that is segfaulting:
```
(gdb) where
#0  0x00007fac6b9091d7 in raise () from /lib64/libc.so.6
#1  0x00007fac6b90a8c8 in abort () from /lib64/libc.so.6
#2  0x00007fac6b902146 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007fac6b9021f2 in __assert_fail () from /lib64/libc.so.6
#4  0x00007fac639ebcef in dstore_del_nspace (nspace=0x1e09c94 "1378549761") at gds_dstore.c:2757
#5  0x00007fac68a5a592 in OPAL_MCA_PMIX2X_PMIx_Disconnect_nb (procs=0x1e09b90, nprocs=6, info=0x0, ninfo=0, cbfunc=0x7fac68a5b992 <op_cbfunc>, cbdata=0x1e3d680)
    at client/pmix_client_connect.c:259
#6  0x00007fac68a5a0f6 in OPAL_MCA_PMIX2X_PMIx_Disconnect (procs=0x1e09b90, nprocs=6, info=0x0, ninfo=0) at client/pmix_client_connect.c:226
#7  0x00007fac68d4fd0e in pmix2x_disconnect (procs=0x7fff100ae5a0) at pmix2x_client.c:1421
#8  0x00007fac6d07b388 in ompi_dpm_disconnect (comm=0x1e01a70) at dpm/dpm.c:596
#9  0x00007fac6d0c0008 in PMPI_Comm_disconnect (comm=0x7fff100ae6b0) at pcomm_disconnect.c:67
#10 0x000000000040153b in do_target (argv=0x7fff100ae808, parent=0x1e01a70) at intercomm_create.c:172
#11 0x0000000000400fbc in main (argc=2, argv=0x7fff100ae808) at intercomm_create.c:62
```

**Comment by karasevb** [comment]
@rhc54 Thanks for the details. I'm fixing.
