### ISSUE TITLE
OSU bandwidth benchmark hangs when --mca btl_openib_cuda_async_recv false option isn't used

### ISSUE THREAD

**Issue by Akshay-Venkatesh** [open-mpi/ompi#4649]
## Background information
User from Germany reported a hang when running [osu bandwidth benchmark](https://github.com/forresti/osu-micro-benchmarks) between GPU buffers on 2 GPUs connected using IB interconnect. The problem occurs after 128KB message mark.

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
Using master branch with the following config options:
../configure --prefix=$PWD --enable-mpirun-prefix-by-default --with-ucx=no --with cuda=$CUDA_HOME --with-verbs --enable-debug --enable-mpi-cxx

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
- Installed using git clone

### Please describe the system on which you are running

* Operating system/version: 
RHEL 7
* Computer hardware: 
Power8 but reproducible on haswell/ivy bridge processors
* Network type: 
ConnectX4

-----------------------------

## Details of the problem

Tracing through the bandwidth benchmark shows that opal_progress_register(mca_pml_ob1_progress) is never called - which is needed when async streams are enabled. OMPI Version 2.12 doesn't show this error.

```shell
shell$ #regular run
shell$mpirun -v -np 2 --map-by node --report-bindings --hostfile hostfile -x LD_LIBRARY_PATH=/usr/lib64:$LD_LIBRARY_PATH -x CUDA
_VISIBLE_DEVICES=0,1 ./libexec/osu-micro-benchmarks/get_local_ompi_rank ./libexec/osu-micro-benchmarks/mpi/pt2pt/osu_bw D D 
[pwr02:21685] MCW rank 0 bound to socket 0[core 0[hwt 0-7]]: [BBBBBBBB/......../......../......../......../......../......../......../......../........][......../......../......../......../......../......../......../......../......../........]
[pwr03:35037] MCW rank 1 bound to socket 0[core 0[hwt 0-7]]: [BBBBBBBB/......../......../......../......../......../......../......../......../........][......../......../......../......../......../......../......../......../......../........]
# OSU MPI-CUDA Bandwidth Test v5.3
# Send Buffer on DEVICE (D) and Receive Buffer on DEVICE (D)
# Size      Bandwidth (MB/s)
1                       0.10
2                       0.21
4                       0.41
8                       0.82
16                      1.65
32                      3.31
64                      6.62
128                    13.31
256                    26.59
512                    55.64
1024                  111.32
2048                  221.66
4096                  411.55
8192                  814.91

$shell #Benchmark hangs indefinitely here

$shell # Backtrace on rank 0
(gdb) bt
#0  0x00003fff7fc40c94 in opal_timer_linux_get_cycles_sys_timer () at ../../../../../opal/mca/timer/linux/timer_linux_component.c:236
#1  0x00003fff7fb32438 in opal_progress () at ../../opal/runtime/opal_progress.c:196
#2  0x00003effe6cd0494 in ompi_request_wait_completion (req=0x3effe6898b00) at ../../../../../ompi/request/request.h:415
#3  0x00003effe6cd1eb8 in mca_pml_ob1_recv (addr=0x3effdee00000, count=4, datatype=0x3fff804a1f50 <ompi_mpi_char>, src=1, tag=101,
    comm=0x3fff804b9458 <ompi_mpi_comm_world>, status=0x100260b0 <reqstat>) at ../../../../../ompi/mca/pml/ob1/pml_ob1_irecv.c:135
#4  0x00003fff803ad148 in PMPI_Recv (buf=0x3effdee00000, count=4, type=0x3fff804a1f50 <ompi_mpi_char>, source=1, tag=101,
    comm=0x3fff804b9458 <ompi_mpi_comm_world>, status=0x100260b0 <reqstat>) at precv.c:79
#5  0x00000000100013b4 in main (argc=<optimized out>, argv=0x3ffff64e77b8) at ../../../mpi/pt2pt/osu_bw.c:106

$shell # Backtrace on rank 1
(gdb) bt
#0  opal_sys_timer_get_cycles () at ../../../../../opal/include/opal/sys/powerpc/timer.h:35
#1  0x00003fffb3a60c84 in opal_timer_linux_get_cycles_sys_timer () at ../../../../../opal/mca/timer/linux/timer_linux_component.c:232
#2  0x00003fffb3952438 in opal_progress () at ../../opal/runtime/opal_progress.c:196
#3  0x00003fffb4133120 in sync_wait_st (sync=0x3fffd3d5c758) at ../../opal/threads/wait_sync.h:83
#4  0x00003fffb4133de8 in ompi_request_default_wait_all (count=64, requests=0x10024150 <request>, statuses=0x100260b0 <reqstat>)
    at ../../ompi/request/req_wait.c:243
#5  0x00003fffb41fb314 in PMPI_Waitall (count=64, requests=0x10024150 <request>, statuses=0x100260b0 <reqstat>) at pwaitall.c:77
#6  0x0000000010001530 in main (argc=<optimized out>, argv=0x3fffd3d5cdd8) at ../../../mpi/pt2pt/osu_bw.c:121

shell$ #Disabling async_stream for recv
shell$ mpirun -v -np 2 --map-by node --report-bindings --hostfile hostfile --mca btl_openib_cuda_async_send true --mca btl_openib
_cuda_async_recv false -x LD_LIBRARY_PATH=/usr/lib64:$LD_LIBRARY_PATH -x CUDA_VISIBLE_DEVICES=0,1 ./libexec/osu-micro-benchmarks/get_local_ompi_rank 
./libexec/osu-micro-benchmarks/mpi/pt2pt/osu_bw D D
[pwr02:21636] MCW rank 0 bound to socket 0[core 0[hwt 0-7]]: [BBBBBBBB/......../......../......../......../......../......../......../......../......
..][......../......../......../......../......../......../......../......../......../........]
[pwr03:34814] MCW rank 1 bound to socket 0[core 0[hwt 0-7]]: [BBBBBBBB/......../......../......../......../......../......../......../......../........][......../......../......../......../......../......../......../......../......../........]
# OSU MPI-CUDA Bandwidth Test v5.3
# Send Buffer on DEVICE (D) and Receive Buffer on DEVICE (D)
# Size      Bandwidth (MB/s)
1                       0.10
2                       0.20
4                       0.41
8                       0.81
16                      1.63
32                      3.26
64                      6.54
128                    13.13
256                    26.30
512                    54.92
1024                  109.66
2048                  218.46
4096                  410.85
8192                  829.11
16384                 976.64
32768                2057.62
65536                3267.32
131072               3523.92
262144               3878.86
524288               4309.74
1048576              4561.82
2097152              4702.71
4194304              4775.04
```

**Comment by hppritcha** [comment]
closing this issue, tracking with #4650 
as noted in #4659 a workaround is to set the following OMPI_MCA env. variable
```
export OMPI_MCA_btl_openib_cuda_async_recv=false
```
