### ISSUE TITLE
psm sighandler called even if psm is not selected

### ISSUE THREAD

**Issue by miked-mellanox** [open-mpi/ompi#525]
On system with OFED and PSM module available ompi fails with segv on ^C or any other signal even if PSM is unused. (Thanks to @yosefe )

It was traced that PSM signal handler is registered and called even if PSM is not selected

salloc -N2 --ntasks-per-node=28 mpirun --report-bindings osu-micro-benchmarks-4.4.1/osu_barrier
^C

``` shell
#0  0x00007f9a9e24b1d0 in ?? ()
#1  <signal handler called>
#2  0x00007f9a9e24b1d0 in ?? ()
#3  <signal handler called>
#4  0x00000034e000a7d9 in pthread_mutex_unlock () from /lib64/libpthread.so.0
#5  0x00007f9aa3f63061 in opal_libevent2021_event_base_loop (base=0x1860630, flags=<value optimized out>) at event.c:1661
#6  0x00007f9aa3f2a48b in opal_progress () at runtime/opal_progress.c:169
#7  0x00007f9aa44b5915 in ompi_mpi_init (argc=1, argv=0x7fff69579b08, requested=0, provided=<value optimized out>) at runtime/ompi_mpi_init.c:642
#8  0x00007f9aa44ca5d0 in PMPI_Init (argc=0x7fff695799cc, argv=0x7fff695799c0) at pinit.c:84
#9  0x00000000004010f2 in main (argc=1, argv=0x7fff69579b08) at osu_barrier.c:22
```

**Comment by rhc54** [comment]
Won't happen on master because the select logic is different, but I shifted the code there as well just to keep it in sync with 1.8.
