### ISSUE TITLE
MTT: usnic failed opal assertion and segfault

### ISSUE THREAD

**Issue by PeterGottesman** [open-mpi/ompi#5362]
On Cisco's MTT the tests `intel/MPI_Sendrecv_replace_ring_c ` and `intel/MPI_Sendrecv_replace_rtoa_c` are frequently failing with the following error:
```
MPI_Sendrecv_replace_ring_c:
opal_datatype_position.c:70: position_predefined_data: Assertion `((_copy_blength) != 0) && 
(((CONVERTOR)->count) != 0)' failed.
--
```

Followed by a segfault:
```
(gdb) bt
#0  0x0000003e52432925 in raise () from /lib64/libc.so.6
#1  0x0000003e52434105 in abort () from /lib64/libc.so.6
#2  0x0000003e5242ba4e in __assert_fail_base () from /lib64/libc.so.6
#3  0x0000003e5242bb10 in __assert_fail () from /lib64/libc.so.6
#4  0x00002aaaab3eb597 in position_predefined_data (CONVERTOR=0x16a9358, ELEM=0x2002b80, COUNT=0x7fffffffb6dc, POINTER=0x7fffffffb6d0, SPACE=0x7fffffffb6c8) at opal_datatype_position.c:69
#5  0x00002aaaab3ec1f8 in opal_convertor_generic_simple_position (pConvertor=0x16a9358, position=0x7fffffffb8c8) at opal_datatype_position.c:223
#6  0x00002aaaab3dd46d in opal_convertor_set_position_nocheck (convertor=0x16a9358, position=0x7fffffffb8c8) at opal_convertor.c:433
#7  0x00002aaaaacbfc29 in opal_convertor_set_position (convertor=0x16a9358, position=0x7fffffffb8c8) at ../../../../opal/datatype/opal_convertor.h:317
#8  0x00002aaaaacc20b9 in mca_pml_ob1_recv_request_progress_frag (recvreq=0x16a9280, btl=0x76d590, segments=0x7fffffffba10, num_segments=1) at pml_ob1_recvreq.c:511
#9  0x00002aaaaacbe2f9 in mca_pml_ob1_recv_frag_callback_frag (btl=0x76d590, tag=70 'F', des=0x7fffffffb980, cbdata=0x0) at pml_ob1_recvfrag.c:394
#10 0x00002aaaab475a7e in opal_btl_usnic_recv_call (module=0x76d590, seg=0x2aaad6d67800, channel=0x76e920) at btl_usnic_recv.c:301
#11 0x00002aaaab465686 in opal_btl_usnic_recv (module=0x76d590, seg=0x2aaad6d67800, channel=0x76e920) at btl_usnic_recv.h:442
#12 0x00002aaaab4678d7 in usnic_handle_completion (module=0x76d590, channel=0x76e920, completion=0x2aaaab7e4bc8 <completions+8>) at btl_usnic_component.c:1213
#13 0x00002aaaab467d8a in usnic_component_progress_2 () at btl_usnic_component.c:1325
#14 0x00002aaaab46782a in usnic_component_progress () at btl_usnic_component.c:1171
#15 0x00002aaaab3c4de9 in opal_progress () at runtime/opal_progress.c:226
#16 0x00002aaaaab36b8c in ompi_request_wait_completion (req=0x16a9280) at ../ompi/request/request.h:392
#17 0x00002aaaaab36bc7 in ompi_request_default_wait (req_ptr=0x7fffffffbd40, status=0x7fffffffbdc0) at request/req_wait.c:41
#18 0x00002aaaaab84508 in PMPI_Sendrecv (sendbuf=0x200f000, sendcount=28392, sendtype=0x2aaaaaf8ddc0 <ompi_mpi_packed>, dest=1, sendtag=0, recvbuf=0x203a740, recvcount=273, recvtype=0x2002260,
    source=17, recvtag=17, comm=0x2027bb0, status=0x7fffffffbdc0) at psendrecv.c:92
#19 0x00002aaaaab850f4 in PMPI_Sendrecv_replace (buf=0x203a740, count=273, datatype=0x2002260, dest=1, sendtag=0, source=17, recvtag=17, comm=0x2027bb0, status=0x7fffffffc770) at psendrecv_replace.c:124
#20 0x0000000000402242 in main (argc=1, argv=0x7fffffffcab8) at MPI_Sendrecv_replace_ring_c.c:226
```

When reproducing this with v2.0.x it failed on the majority of runs, with an increasing frequency as np increased. Additionally the issue doesn't seem to come up on single nodes, although it may just be unlikely.

MTT link: https://mtt.open-mpi.org/index.php?do_redir=2644

@bosilca Any idea what might be leading to this? It isn't appearing up past 3.0.x so maybe it has already come up elsewhere?

**Comment by bosilca** [comment]
There should be no link between the number of participants and the packing/unpacking of MPI datatypes. Can this be reproduced outside CISCO MTT (aka not with usnic) ?

**Comment by PeterGottesman** [comment]
Nope, it is only popping up in the usnic testing as far as I can tell.

**Comment by bosilca** [comment]
The I would bisect to see what change in usnic introduced this. Based on the stack trace I would assume this is coming from the message fragmentation.

**Comment by jsquyres** [comment]
This has been fixed.
