### ISSUE TITLE
Hang on MPI_Abort with external pmix 3.0 / libevent

### ISSUE THREAD

**Issue by amckinstry** [open-mpi/ompi#5528]
## Background information
This is seen in Debian, leading to multiple failures (eg. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=904825)

### What version of Open MPI are you using? 
* OpenMPI 3.0.0
* External PMIX 3.0.0 
* libevent 2.1.8

(With a hack to identify pmix 3.0 ; see
https://salsa.debian.org/hpc-team/openmpi/blob/debian/master/debian/patches/force-pmix-3.patch
) ; 
Everything else is Vanilla

### Describe how Open MPI was installed 
* Debian unstable
* Simple VM. mpirun -n 1 ./a.out will do) 
* Any network

The problem goes away if the internal versions of pmix /libevent are used.

## Details of the problem

Just call `MPI_Abort(MPI_COMM_WORLD, x)`. I get the expected failure/abort messages from OMPI, but mpiexec / a.out appear to hang in libevent.
A backtrace of mpiexec gives
```
    at ../sysdeps/unix/sysv/linux/nanosleep.c:28
28    ../sysdeps/unix/sysv/linux/nanosleep.c: No such file or directory.
(gdb) where
#0  0x00007fdd850b3c70 in __GI___nanosleep (requested_time=requested_time@entry=0x7ffcd5069000, remaining=remaining@entry=0x0)
    at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x00007fdd84e55c9a in orte_show_help_norender (filename=<optimized out>, filename@entry=0x7fdd85198117 "help-mpi-api.txt", topic=<optimized out>,
    topic@entry=0x7fdd85199c36 "mpi-abort", want_error_header=want_error_header@entry=true, output=<optimized out>,
    output@entry=0x56260520ee70 '-' <repeats 74 times>, "\nMPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD\nwith errorcode 12.\n\nNOTE: invoking MPI_ABORT caus\
es Open MPI t"...) at util/show_help.c:721
#2  0x00007fdd84e55ef4 in orte_show_help (filename=0x7fdd85198117 "help-mpi-api.txt", topic=0x7fdd85199c36 "mpi-abort", want_error_header=true)
    at util/show_help.c:614
#3  0x00007fdd851250aa in PMPI_Abort (comm=0x56260371d080 <ompi_mpi_comm_world>, errorcode=12) at pabort.c:56
#4  0x000056260371a21c in main (argc=1, argv=0x7ffcd50692d8) at ./test.c:20
```

and
```
0x00007f6cdbe91739 in __GI___poll (fds=0x5563d32ce810, nfds=9, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
29    ../sysdeps/unix/sysv/linux/poll.c: No such file or directory.
(gdb) where
#0  0x00007f6cdbe91739 in __GI___poll (fds=0x5563d32ce810, nfds=9, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f6cdc1b17c8 in ?? () from /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6
#2  0x00007f6cdc1a8329 in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6
#3  0x00005563d2c59542 in orterun (argc=<optimized out>, argv=0x7ffd05fe9bd8) at orterun.c:201
#4  0x00007f6cdbdc6b17 in __libc_start_main (main=0x5563d2c59120 <main>, argc=4, argv=0x7ffd05fe9bd8, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7ffd05fe9bc8) at ../csu/libc-start.c:310
#5  0x00005563d2c5915a in _start ()
```

So, how to proceed? what error tracing can I turn on to debug libevent issues ?

**Comment by jsquyres** [comment]
With some discussions on @rhc54 on 2018-08-13, he's sure he fixed this later on master.  He checked -- the issue is in OMPI v3.0.x and v3.1.x.  @rhc54 will make PRs for it.

**Comment by rhc54** [comment]
Both branches have been updated
