### ISSUE TITLE
master: pmix4x spawn deadlocks

### ISSUE THREAD

**Issue by abouteiller** [open-mpi/ompi#6513]
## Background information

`mpirun` process crashes with `SIGSEGV` when`MPI_COMM_SPAWN` issues `pmix.spawn_nb` at a client MPI process.

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

master 53cd31ed

Bug was **not present** in 2bd7d867

## Details of the problem

```gdb
Program received signal SIGSEGV, Segmentation fault.
(gdb) bt
#0  0x00007ffff62c43b1 in __strlen_sse2 () from /lib64/libc.so.6
#1  0x00007ffff62c40be in strdup () from /lib64/libc.so.6
#2  0x00007ffff2fbc9e5 in server_spawn_fn (p=0x7ffff0cb31c0, job_info=0x7fffe801a2c0, ninfo=2, apps=0x7fffe8019070, napps=1, cbfunc=0x7ffff304046a <spcbfunc>,
    cbdata=0x7fffe8019860) at ../../../../../master/opal/mca/pmix/pmix4x/pmix4x_server_north.c:695
#3  0x00007ffff304254f in pmix_server_spawn (peer=0x7fffe8015020, buf=0x7ffff0cb3ce0, cbfunc=0x7ffff3028b0b <spawn_cbfunc>, cbdata=0x7fffe801a090)
    at ../../../../../../../master/opal/mca/pmix/pmix4x/pmix/src/server/pmix_server_ops.c:1383
#4  0x00007ffff3035c9f in server_switchyard (peer=0x7fffe8015020, tag=108, buf=0x7ffff0cb3ce0)
    at ../../../../../../../master/opal/mca/pmix/pmix4x/pmix/src/server/pmix_server.c:3403
#5  0x00007ffff303833f in pmix_server_message_handler (pr=0x7fffe8015020, hdr=0x7fffe801a280, buf=0x7ffff0cb3ce0, cbdata=0x0)
    at ../../../../../../../master/opal/mca/pmix/pmix4x/pmix/src/server/pmix_server.c:3553
#6  0x00007ffff30d1d52 in OPAL_MCA_PMIX4X_pmix_ptl_base_process_msg (fd=-1, flags=4, cbdata=0x7fffe801a1a0)
    at ../../../../../../../../../master/opal/mca/pmix/pmix4x/pmix/src/mca/ptl/base/ptl_base_sendrecv.c:796
#7  0x00007ffff78116d9 in event_process_active_single_queue (activeq=0x79df20, base=0x79dae0)
    at ../../../../../../master/opal/mca/event/libevent2022/libevent/event.c:1370
#8  event_process_active (base=<optimized out>) at ../../../../../../master/opal/mca/event/libevent2022/libevent/event.c:1440
#9  opal_libevent2022_event_base_loop (base=0x79dae0, flags=1) at ../../../../../../master/opal/mca/event/libevent2022/libevent/event.c:1644
#10 0x00007ffff3060df5 in progress_engine (obj=0x79da68) at ../../../../../../../master/opal/mca/pmix/pmix4x/pmix/src/runtime/pmix_progress_threads.c:230

#2  0x00007ffff2fbc9e5 in server_spawn_fn (p=0x7ffff0cb31c0, job_info=0x7fffe801a2c0, ninfo=2, apps=0x7fffe8019070, napps=1, cbfunc=0x7ffff304046a <spcbfunc>,
    cbdata=0x7fffe8019860) at ../../../../../master/opal/mca/pmix/pmix4x/pmix4x_server_north.c:695
695                 oinfo->key = strdup(apps[n].info[k].key);
(gdb)
#3  0x00007ffff304254f in pmix_server_spawn (peer=0x7fffe8015020, buf=0x7ffff0cb3ce0, cbfunc=0x7ffff3028b0b <spawn_cbfunc>, cbdata=0x7fffe801a090)
    at ../../../../../../../master/opal/mca/pmix/pmix4x/pmix/src/server/pmix_server_ops.c:1383
1383        rc = pmix_host_server.spawn(&proc, cd->info, cd->ninfo, cd->apps, cd->napps, spcbfunc, cd);
(gdb) down
#2  0x00007ffff2fbc9e5 in server_spawn_fn (p=0x7ffff0cb31c0, job_info=0x7fffe801a2c0, ninfo=2, apps=0x7fffe8019070, napps=1, cbfunc=0x7ffff304046a <spcbfunc>,
    cbdata=0x7fffe8019860) at ../../../../../master/opal/mca/pmix/pmix4x/pmix4x_server_north.c:695
695                 oinfo->key = strdup(apps[n].info[k].key);
(gdb) p apps[n]
$1 = {cmd = 0x7fffe80154c0 "spawn", argv = 0x7fffe8015500, env = 0x7fffe801a720, cwd = 0x0, maxprocs = 3, info = 0x6964772e78696d70, ninfo = 114}
(gdb) p n
$2 = 0
(gdb) p k
$4 = 0
(gdb) p apps[n].info[k].key
Cannot access memory at address 0x6964772e78696d70
(gdb) list
690             }
691             app->maxprocs = apps[n].maxprocs;
692             for (k=0; k < apps[n].ninfo; k++) {
693                 oinfo = OBJ_NEW(opal_value_t);
694                 opal_list_append(&app->info, &oinfo->super);
695                 oinfo->key = strdup(apps[n].info[k].key);
696                 if (OPAL_SUCCESS != (rc = pmix4x_value_unload(oinfo, &apps[n].info[k].value))) {
```

**Comment by ggouaillardet** [comment]
@abouteiller this is a typo that is fixed in pmix/pmix#1161

For the time being, you can manually apply the inline patch below

```patch
diff --git a/opal/mca/pmix/pmix4x/pmix/src/mca/bfrops/base/bfrop_base_unpack.c b/opal/mca/pmix/pmix4x/pmix/src/mca/bfrops/base/bfrop_base_unpack.c
index 6ee9b75..7c8e76b 100644
--- a/opal/mca/pmix/pmix4x/pmix/src/mca/bfrops/base/bfrop_base_unpack.c
+++ b/opal/mca/pmix/pmix4x/pmix/src/mca/bfrops/base/bfrop_base_unpack.c
@@ -904,7 +904,7 @@ pmix_status_t pmix_bfrops_base_unpack_app(pmix_pointer_array_t *regtypes,
         if (0 < ptr[i].ninfo) {
             PMIX_INFO_CREATE(ptr[i].info, ptr[i].ninfo);
             m = ptr[i].ninfo;
-            PMIX_BFROPS_UNPACK_TYPE(ret, buffer, &ptr[i].info, &m, PMIX_INFO, regtypes);
+            PMIX_BFROPS_UNPACK_TYPE(ret, buffer, ptr[i].info, &m, PMIX_INFO, regtypes);
             if (PMIX_SUCCESS != ret) {
                 return ret;
             }
```
