### ISSUE TITLE
OSError: Unable to open file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')

### ISSUE THREAD

**Issue by ascenoputing** [open-mpi/ompi#6535]
### What version of Open MPI are you using?
open-mpi 3.1.2

### Describe how Open MPI was installed 
tarball

### Please describe the system on which you are running

* Operating system/version: ubuntu 16
* Computer hardware:  
* Network type: 

-----------------------------

## Details of the problem
Traceback (most recent call last):
  File "plot_surface.py", line 289, in <module>
    crunch(surf_file, net, w, s, d, trainloader, 'train_loss', 'train_acc', comm, rank, args)
  File "plot_surface.py", line 80, in crunch
    f = h5py.File(surf_file, 'r+' if rank == 0 else 'r')
  File "/home/lyh/anaconda3/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/lyh/anaconda3/envs/python3.6/lib/python3.6/site-packages/h5py/_hl/files.py", line 144, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')
Computing 5100 values for rank 1
Traceback (most recent call last):
  File "plot_surface.py", line 289, in <module>
    crunch(surf_file, net, w, s, d, trainloader, 'train_loss', 'train_acc', comm, rank, args)
  File "plot_surface.py", line 131, in crunch
    losses     = mpi4pytorch.reduce_max(comm, losses)
  File "/home/lyh/loss-landscape/mpi4pytorch.py", line 74, in reduce_max
    comm.Reduce(array, total, op=MPI.MAX, root=0)
  File "mpi4py/MPI/Comm.pyx", line 703, in mpi4py.MPI.Comm.Reduce
  File "mpi4py/MPI/msgbuffer.pxi", line 667, in mpi4py.MPI._p_msg_cco.for_reduce
  File "mpi4py/MPI/msgbuffer.pxi", line 633, in mpi4py.MPI._p_msg_cco.for_cro_send
  File "mpi4py/MPI/msgbuffer.pxi", line 154, in mpi4py.MPI.message_simple
  File "mpi4py/MPI/msgbuffer.pxi", line 100, in mpi4py.MPI.message_basic
KeyError: '<d'

**Comment by danziy0904** [comment]
Do you solve it? I have the same problem

**Comment by KaleabTessera** [comment]
@danziy0904  Have a look at this PR https://github.com/tomgoldstein/loss-landscape/pull/28 . 

You basically need to add ```os.environ["HDF5_USE_FILE_LOCKING"] = "FALSE"``` to fix this issue.
