### ISSUE TITLE
Intermittent deadlock/hang at initialization on shared memory

### ISSUE THREAD

**Issue by mkre** [open-mpi/ompi#7135]
### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

v3.1.3

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

from a source tarball

### Please describe the system on which you are running

* Operating system/version: CentOS 7.3
* Computer hardware: 2x Intel Xeon Broadwell
* Network type: shared memory

-----------------------------

## Details of the problem

We have seen our MPI application to hang at initialization time. Unfortunately, this issue has only appeared once so far, and we haven't been able to reproduce it. Here is a gdb backtrace which we could extract from the hang. 

```
Thread 3 (Thread 0x7f45e03b5700 (LWP 5526)):
#0  0x00007f45f5b43dfd in poll () from /lib64/libc.so.6
#1  0x00007f45e144e7aa in poll_dispatch (base=0x20ac3b0, tv=0x7f45e03b4d70) at poll.c:165
#2  0x00007f45e1448786 in opal_libevent2022_event_base_loop (base=0x20ac3b0, flags=1) at event.c:1630
#3  0x00007f45e140908e in progress_engine () from /home.local/x-pan2/petr/dev/mpi/openmpi/3.1.3-cda-006/linux-x86_64-2.12/gnu7.1/lib/libopen-pal.so.40
#4  0x00007f45f8709dc5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f45f5b4e73d in clone () from /lib64/libc.so.6
```
```
Thread 2 (Thread 0x7f45ddc37700 (LWP 5545)):
#0  0x00007f45f5b4ed13 in epoll_wait () from /lib64/libc.so.6
#1  0x00007f45e1442fd6 in epoll_dispatch (base=0x20e69d0, tv=<optimized out>) at epoll.c:407
#2  0x00007f45e1448786 in opal_libevent2022_event_base_loop (base=0x20e69d0, flags=1) at event.c:1630
#3  0x00007f45df7646ae in progress_engine () from /home.local/x-pan2/petr/dev/mpi/openmpi/3.1.3-cda-006/linux-x86_64-2.12/gnu7.1/lib/openmpi/mca_pmix_pmix2x.so
#4  0x00007f45f8709dc5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f45f5b4e73d in clone () from /lib64/libc.so.6
```
```
Thread 1 (Thread 0x7f45f9111880 (LWP 5239)):
#0  0x00007f45f870d6d5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f45df73ed4d in OPAL_MCA_PMIX2X_PMIx_Init () from /home.local/x-pan2/petr/dev/mpi/openmpi/3.1.3-cda-006/linux-x86_64-2.12/gnu7.1/lib/openmpi/mca_pmix_
pmix2x.so
#2  0x00007f45df71c0ed in pmix2x_client_init () from /home.local/x-pan2/petr/dev/mpi/openmpi/3.1.3-cda-006/linux-x86_64-2.12/gnu7.1/lib/openmpi/mca_pmix_pmix2x.
so
#3  0x00007f45e03b7a26 in rte_init () from /home.local/x-pan2/petr/dev/mpi/openmpi/3.1.3-cda-006/linux-x86_64-2.12/gnu7.1/lib/openmpi/mca_ess_pmi.so
#4  0x00007f45e16e7d88 in orte_init () from /home.local/x-pan2/petr/dev/mpi/openmpi/3.1.3-cda-006/linux-x86_64-2.12/gnu7.1/lib/libopen-rte.so.40
#5  0x00007f45e19c63d6 in ompi_mpi_init () from /home.local/x-pan2/petr/dev/mpi/openmpi/3.1.3-cda-006/linux-x86_64-2.12/gnu7.1/lib/libmpi.so.40
#6  0x00007f45e19f29cb in PMPI_Init () from /home.local/x-pan2/petr/dev/mpi/openmpi/3.1.3-cda-006/linux-x86_64-2.12/gnu7.1/lib/libmpi.so.40
#7  0x00007f45e1c8e2db in CCM_MPI_Init_imp () from /home.local/x-pan2/petr/dev/star/lib/linux-x86_64-2.17/gnu7.1-r8/lib/libStarOpenMpi3.so
#8  0x00007f45f718947f in Machine::startCommunicators(int&, char***, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, u
nsigned int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<ch
ar, std::char_traits<char>, std::allocator<char> > const, unsigned int> > >&) () from /home.local/x-pan2/petr/dev/star/lib/linux-x86_64-2.17/gnu7.1-r8/lib/cd/li
bStarMachine.so
#9 
```
I understand that this might be a very long shot, but maybe it's helpful to anyone, or someone can identify this as a known issue. Could the issue be related to PMIx (and potentially be solved the with PMIx upgrade in Open MPI 3.1.5)?

Thanks,
Moritz

**Comment by mkre** [comment]
Seems like nobody could see any smoking guns here. From our side, we haven't observed similar hangs since the one reported above. If there are no further ideas, it's fine with me to close this issue.

**Comment by jsquyres** [comment]
@mkre Sorry; this came in right before SC -- I think we lost it in the shuffle. 😦 

Can you try 3.1.5?  There were a bunch of bug fixes since 3.1.3.

**Comment by mkre** [comment]
I could try that, but as I said, I can't even reproduce the issue with 3.1.3. We only saw it once out of many runs, but I thought I'd just go ahead and dump the stack trace here regardless of that, in case it is helpful for anyone.

**Comment by jsquyres** [comment]
Gotcha.  Thank you!

I'm going to close this as (probably) fixed.  Let us know if you run into it again.
