### ISSUE TITLE
Seg fault when running ring_c test on 1152 ranks over 32 nodes with direct modex 

### ISSUE THREAD

**Issue by dipti-kothari** [open-mpi/ompi#7647]
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
master, commit ```6539a55708```

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
git clone

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.
 4a43c39c89037f52b4e25927e58caf08f3707c33 opal/mca/hwloc/hwloc2/hwloc (hwloc-2.1.0rc2-53-g4a43c39c)
 e353951a67665a9a623fd3590365f493a1bdb8dd opal/mca/pmix/pmix4x/openpmix (v1.1.3-2333-ge353951a)
 743fb9c42e6037735011d6c16f0d42d116d49d90 prrte (dev-30508-g743fb9c42e)

## Details of the problem

When running ring_c test on 32 nodes with 36 ppn and building ompi with opal_pmix_base_async_modex=true and opal_pmix_collect_all_data=false. The following output is generated. 
```
Process 0 sending 10 to 1, tag 201 (1152 processes in ring)
Process 0 sent to 1
[ip-172-31-0-61:55507] *** Process received signal ***
[ip-172-31-0-61:55507] Signal: Segmentation fault (11)
[ip-172-31-0-61:55507] Signal code: Address not mapped (1)
[ip-172-31-0-61:55507] Failing at address: 0x140000002a
[ip-172-31-0-61:55507] [ 0] /lib64/libpthread.so.0(+0xf600)[0x7fe2f3e90600]
[ip-172-31-0-61:55507] [ 1] /shared/ompi/install/lib/libopen-pal.so.0(+0x1f2a2c)[0x7fe2f4fbea2c]
[ip-172-31-0-61:55507] [ 2] /shared/ompi/install/lib/libopen-pal.so.0(+0x208f23)[0x7fe2f4fd4f23]
[ip-172-31-0-61:55507] [ 3] /shared/ompi/install/lib/libopen-pal.so.0(opal_libevent2022_event_base_loop+0xd99)[0x7fe2f4e8e199]
[ip-172-31-0-61:55507] [ 4] /shared/ompi/install/lib/libopen-pal.so.0(+0x1d2a43)[0x7fe2f4f9ea43]
[ip-172-31-0-61:55507] [ 5] /lib64/libpthread.so.0(+0x7e75)[0x7fe2f3e88e75]
[ip-172-31-0-61:55507] [ 6] /lib64/libc.so.6(clone+0x6d)[0x7fe2f3bb18fd]
[ip-172-31-0-61:55507] *** End of error message ***
Segmentation fault
[ec2-user@ip-172-31-0-61 shared]$ [ip-172-31-3-203:04849] *** Process received signal ***
[ip-172-31-3-203:04849] Signal: Segmentation fault (11)
[ip-172-31-3-203:04849] Signal code: Address not mapped (1)
[ip-172-31-3-203:04849] Failing at address: 0xcb031fd4
[ip-172-31-3-203:04849] [ 0] /lib64/libpthread.so.0(+0xf600)[0x7f052f6ca600]
[ip-172-31-3-203:04849] [ 1] /shared/ompi/install/lib/libopen-pal.so.0(+0x1f2a2c)[0x7f05307f8a2c]
[ip-172-31-3-203:04849] [ 2] /shared/ompi/install/lib/libopen-pal.so.0(+0x208f23)[0x7f053080ef23]
[ip-172-31-3-203:04849] [ 3] /shared/ompi/install/lib/libopen-pal.so.0(opal_libevent2022_event_base_loop+0xd99)[0x7f05306c8199]
[ip-172-31-3-203:04849] [ 4] /shared/ompi/install/lib/libopen-pal.so.0(+0x1d2a43)[0x7f05307d8a43]
[ip-172-31-3-203:04849] [ 5] /lib64/libpthread.so.0(+0x7e75)[0x7f052f6c2e75]
[ip-172-31-3-203:04849] [ 6] /lib64/libc.so.6(clone+0x6d)[0x7f052f3eb8fd]
[ip-172-31-3-203:04849] *** End of error message ***
[ip-172-31-1-249:48112] *** Process received signal ***
[ip-172-31-1-249:48112] Signal: Segmentation fault (11)
[ip-172-31-1-249:48112] Signal code: Address not mapped (1)
[ip-172-31-1-249:48112] Failing at address: 0x28
[ip-172-31-1-249:48112] [ 0] /lib64/libpthread.so.0(+0xf600)[0x7f7d34f71600]
[ip-172-31-1-249:48112] [ 1] /shared/ompi/install/lib/libopen-pal.so.0(+0x1f2a2c)[0x7f7d3609fa2c]
[ip-172-31-1-249:48112] [ 2] bash: line 1:  4849 Segmentation fault      /shared/ompi/install/bin/prted --prtemca ess "env" --prtemca ess_base_nspace "mpirun-ip-172-31-0-6155507" --prtemca ess_base_vpid 27 --prtemca ess_base_num_procs "32" --prtemca prrte_hnp_uri "mpirun-ip-172-31-0-6155507.0;tcp://172.31.0.61:35223:20" --prtemca plm "rsh" --tree-spawn --prtemca prrte_parent_uri "mpirun-ip-172-31-0-6155507.0;tcp://172.31.0.61:35223:20" --prtemca pmix_session_server "1" --prtemca prrte_base_help_aggregate "0"
```
A similar error can be generated by launching 144 ranks over 2 nodes. The error occurs on exiting
```
/shared/ompi/install/bin/mpirun --prefix /shared/ompi/install --tag-output --np 144 --host 172.31.10.70:72,172.31.7.197:72 ./ring_c
rocess 0 sending 10 to 1, tag 201 (144 processes in ring)
Process 0 sent to 1
Process 0 decremented value: 9
Process 0 decremented value: 8
Process 0 decremented value: 7
..
..
Process 142 exiting
Process 140 exiting
Process 143 exiting
[ip-172-31-10-70:71548] UNEXPECTED MESSAGE tag = 107 from source mpirun-ip-172-31-0-6157011:1
[ip-172-31-10-70:71560] UNEXPECTED MESSAGE tag = 106 from source mpirun-ip-172-31-0-6157011:1
[ip-172-31-10-70:71563] UNEXPECTED MESSAGE tag = 106 from source mpirun-ip-172-31-0-6157011:1
[ip-172-31-10-70:71567] UNEXPECTED MESSAGE tag = 106 from source mpirun-ip-172-31-0-6157011:1
[ip-172-31-10-70:71549] UNEXPECTED MESSAGE tag = 106 from source mpirun-ip-172-31-0-6157011:1
[ip-172-31-10-70:71545] UNEXPECTED MESSAGE tag = 106 from source mpirun-ip-172-31-0-6157011:1
[ip-172-31-10-70:71547] UNEXPECTED MESSAGE tag = 106 from source mpirun-ip-172-31-0-6157011:1
[ip-172-31-10-70:71550] UNEXPECTED MESSAGE tag = 106 from source mpirun-ip-172-31-0-6157011:1
prted: server/pmix_server.c:2670: get_cbfunc: Assertion `((0xdeafbeedULL << 32) + 0xdeafbeedULL) == ((pmix_object_t *) (cd))->obj_magic_id' failed.
bash: line 1: 71537 Aborted                 /shared/ompi/install/bin/prted --prtemca ess "env" --prtemca ess_base_nspace "mpirun-ip-172-31-0-6157011" --prtemca ess_base_vpid 1 --prtemca ess_base_num_procs "32" --prtemca prrte_hnp_uri "mpirun-ip-172-31-0-6157011.0;tcp://172.31.0.61:35169:20" --prtemca plm "rsh" --tree-spawn --prtemca prrte_parent_uri "mpirun-ip-172-31-0-6157011.0;tcp://172.31.0.61:35169:20" --prtemca pmix_session_server "1" --prtemca prrte_base_help_aggregate "0"
--------------------------------------------------------------------------
PRRTE has lost communication with a remote daemon.

  HNP daemon   : [[63068,0],0] on node ip-172-31-0-61
  Remote daemon: [[63068,0],1] on node 172.31.10.70

This is usually due to either a failure of the TCP network
connection to the node, or possibly an internal failure of
the daemon itself. We cannot recover from this failure, and
therefore will terminate the job.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
PRRTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-prun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/prrte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------
[ip-172-31-7-197:63184] *** Process received signal ***
[ip-172-31-7-197:63184] Signal: Segmentation fault (11)
[ip-172-31-7-197:63184] Signal code: Address not mapped (1)
[ip-172-31-7-197:63184] Failing at address: 0x38
[ip-172-31-7-197:63184] [ 0] /lib64/libpthread.so.0(+0xf600)[0x7f8fae4be600]
[ip-172-31-7-197:63184] [ 1] /shared/ompi/install/lib/libopen-pal.so.0(+0x1f2a2c)[0x7f8faf5eca2c]
[ip-172-31-7-197:63184] [ 2] /shared/ompi/install/lib/libopen-pal.so.0(+0x208f23)[0x7f8faf602f23]
[ip-172-31-7-197:63184] [ 3] /shared/ompi/install/lib/libopen-pal.so.0(opal_libevent2022_event_base_loop+0xd99)[0x7f8faf4bc199]
[ip-172-31-7-197:63184] [ 4] /shared/ompi/install/lib/libopen-pal.so.0(+0x1d2a43)[0x7f8faf5cca43]
[ip-172-31-7-197:63184] [ 5] /lib64/libpthread.so.0(+0x7e75)[0x7f8fae4b6e75]
[ip-172-31-7-197:63184] [ 6] /lib64/libc.so.6(clone+0x6d)[0x7f8fae1df8fd]
[ip-172-31-7-197:63184] *** End of error message ***
bash: line 1: 63184 Segmentation fault      /shared/ompi/install/bin/prted --prtemca ess "env" --prtemca ess_base_nspace "mpirun-ip-172-31-0-6157011" --prtemca ess_base_vpid 2 --prtemca ess_base_num_procs "32" --prtemca prrte_hnp_uri "mpirun-ip-172-31-0-6157011.0;tcp://172.31.0.61:35169:20" --prtemca plm "rsh" --tree-spawn --prtemca prrte_parent_uri "mpirun-ip-172-31-0-6157011.0;tcp://172.31.0.61:35169:20" --prtemca pmix_session_server "1" --prtemca prrte_base_help_aggregate "0"
[ip-172-31-0-61:57011] 1 more process has sent help message help-errmgr-base.txt / failed-daemon-launch
[ip-172-31-0-61:57011] Set MCA parameter "prrte_base_help_aggregate" to 0 to see all help / error messages
```

**Comment by karasevb** [comment]
I experienced a similar crash where two problems can be separated:
- direct-modex: some process cannot get a pml endpoint key and PMIx_Get ends due to timeout.
- segfault: at the PMIx_Get timeout scenario.

Here is backtrace:
```C
(gdb) bt
#0  0x00007f3c91eb636a in get_cbfunc (status=-24, data=0x0, ndata=0, cbdata=0x7f3c84032670, relfn=0x0, relcbd=0x0) at ../../src/server/pmix_server.c:2629
#1  0x00007f3c91eecb10 in get_timeout (sd=-1, args=1, cbdata=0x7f3c84035b60) at ../../src/server/pmix_server_get.c:1146
#2  0x00007f3c919f3690 in event_process_active_single_queue (base=base@entry=0x1edd480, activeq=0x1edd8b0, max_to_process=max_to_process@entry=2147483647, endtime=endtime@entry=0x0) at event.c:1697
#3  0x00007f3c919f3d5f in event_process_active (base=0x1edd480) at event.c:1789
#4  event_base_loop (base=0x1edd480, flags=1) at event.c:2012
#5  0x00007f3c91ef0be2 in progress_engine (obj=0x1edd380) at ../../src/runtime/pmix_progress_threads.c:232
#6  0x00007f3c906d9dd5 in start_thread () from /lib64/libpthread.so.0
#7  0x00007f3c90402ead in clone () from /lib64/libc.so.6
(gdb) l
2624        reply = PMIX_NEW(pmix_buffer_t);
2625        if (NULL == reply) {
2626            rc = PMIX_ERR_NOMEM;
2627            goto cleanup;
2628        }
2629        PMIX_BFROPS_PACK(rc, cd->peer, reply, &status, 1, PMIX_STATUS);
2630        if (PMIX_SUCCESS != rc) {
2631            PMIX_ERROR_LOG(rc);
2632            goto cleanup;
2633        }
(gdb)
```

**Comment by rhc54** [comment]
I can correct the segfault, but the real question is: why can't a process get the PML key?

**Comment by karasevb** [comment]
I'll try to collect more details.

**Comment by rhc54** [comment]
@dipti-kothari @karasevb can you folks do a quick check of the latest OMPI master and see if this persists? Just want to get a baseline before digging into it as OMPI/PMIx/PRRTE have been updated a few times over the last couple of days.

**Comment by karasevb** [comment]
The last master 91be01b is still crashing with the same backtrace.

2 nodes, 10 ppn crash:
```bash
export OMPI_MCA_pmix_base_async_modex=1
export OMPI_MCA_pmix_base_collect_data=0

mpirun -n 20 --map-by ppr:10:node ./osu_alltoall
# OSU MPI All-to-All Personalized Exchange Latency Test v5.6.2
# Size       Avg Latency(us)
1                      22.81
2                      22.70
4                      22.66
8                      23.07
16                     23.41
32                     24.38
64                     25.89
128                    26.33
256                    22.23
512                    23.25
1024                   26.22
2048                   31.65
4096                   72.98
8192                  115.57
16384                 176.66
32768                 296.31
65536                 609.70
131072               1255.87
262144               1566.19
524288               4294.75
--------------------------------------------------------------------------
PRRTE has lost communication with a remote daemon.

  HNP daemon   : [[6845,0],0] on node hpchead
  Remote daemon: [[6845,0],1] on node jazz28

This is usually due to either a failure of the TCP network
connection to the node, or possibly an internal failure of
the daemon itself. We cannot recover from this failure, and
therefore will terminate the job.
--------------------------------------------------------------------------
```

**Comment by karasevb** [comment]
I found a timeout problem, will open the PR.

**Comment by karasevb** [comment]
@dipti-kothari could you verify please, that https://github.com/openpmix/openpmix/pull/1740 fixes this issue?

**Comment by dipti-kothari** [comment]
> @dipti-kothari @karasevb can you folks do a quick check of the latest OMPI master and see if this persists? Just want to get a baseline before digging into it as OMPI/PMIx/PRRTE have been updated a few times over the last couple of days.

I still get an error with master, ill try the patch posted by @karasevb 
```
[172.31.0.61:00000] *** An error occurred in MPI_Init
[172.31.0.61:00000] *** reported by process [551419905,19]
[172.31.0.61:00000] *** on a NULL communicator
[172.31.0.61:00000] *** Unknown error
[172.31.0.61:00000] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[172.31.0.61:00000] ***    and potentially your MPI job)
[ip-172-31-0-61:23733] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2257
[ip-172-31-0-61:23733] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2257
[ip-172-31-0-61:23733] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2257
[ip-172-31-0-61:23733] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2257
[ip-172-31-0-61:23733] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2257
[ip-172-31-0-61:23733] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2257
[ip-172-31-0-61:23733] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2257
[ip-172-31-0-61:23733] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2257
```

**Comment by dipti-kothari** [comment]
Thank you @karasevb
I have hit another issue in master, which is not related to dmodex. I’ll test ompi/master once that issue is cleared and update it here.

**Comment by rhc54** [comment]
@dipti-kothari \<poke\> have you verified this is fixed?

**Comment by dipti-kothari** [comment]
@rhc54 I have verified the fix, it works. Closing the issue
