### ISSUE TITLE
Intermittent hang of ibm/communicator/comm_idup tests

### ISSUE THREAD

**Issue by rolfv** [open-mpi/ompi#778]
I am getting intermittent hangs of mostly the comm_idup_mpfh.f90 test. This happens with np=6 across two nodes using openib BTL. Figured I would capture some data here.  I have seen on both 2.x and master.

```
[rvandevaart@drossetti-ivy4 bin]$ ./ompi-top --pid 7505
======================================================================================================================\
============
Rank |       Nodename |         Command |  Pid | State |   Time | Pri | #threads |    Vsize |      RSS | Peak Vsize | \
Processor |
----------------------------------------------------------------------------------------------------------------------\
------------
   0 | drossetti-ivy4 | comm_idup_mpifh | 7509 |     R |   3:27 |  20 |        5 |      375 |       57 |        375 | \
        1 |
   1 | drossetti-ivy4 | comm_idup_mpifh | 7510 |     S |   0:13 |  20 |        5 |      375 |       57 |        376 | \
       16 |
   2 | drossetti-ivy4 | comm_idup_mpifh | 7511 |     R |   3:27 |  20 |        5 |      374 |       56 |        374 | \
        2 |
   3 | drossetti-ivy5 | comm_idup_mpifh | 4319 |     S |   0:03 |  20 |        5 |      375 |       57 |        375 | \
        1 |
   4 | drossetti-ivy5 | comm_idup_mpifh | 4320 |     R |   3:27 |  20 |        5 |      375 |       57 |        375 | \
       10 |
   5 | drossetti-ivy5 | comm_idup_mpifh | 4321 |     S |   0:03 |  20 |        5 |      374 |       56 |        374 | \
        1 |

Rank 0
(gdb) where
#0  0x00007f6a2006f537 in sched_yield () from /lib64/libc.so.6
#1  0x00007f6a1f9a6991 in opal_progress () at ../../opal/runtime/opal_progress.c:199
#2  0x00007f6a1876a275 in opal_condition_wait (c=0x7f6a2104d040, m=0x7f6a2104cfc0) at ../../../../../opal/threads/cond\
ition.h:76
#3  0x00007f6a1876a43c in ompi_request_wait_completion (req=0x1305a80) at ../../../../../ompi/request/request.h:383
#4  0x00007f6a1876b11f in mca_pml_ob1_recv (addr=0x7fffa8e04f24, count=1, datatype=0x7f6a21031a00, src=1, tag=-12, com\
m=0x7f6a1c6b9480, status=0x0)
    at ../../../../../ompi/mca/pml/ob1/pml_ob1_irecv.c:118
#5  0x00007f6a20daede6 in ompi_coll_base_allreduce_intra_recursivedoubling (sbuf=0x7fffa8e04f20, rbuf=0x7fffa8e04f24, \
count=1, dtype=0x7f6a21031a00, op=0x7f6a21046d00,
    comm=0x7f6a1c6b9480, module=0x7f6a1c6ba0e0) at ../../../../ompi/mca/coll/base/coll_base_allreduce.c:249
#6  0x00007f6a17af9b85 in ompi_coll_tuned_allreduce_intra_dec_fixed (sbuf=0x7fffa8e04f20, rbuf=0x7fffa8e04f24, count=1\
, dtype=0x7f6a21031a00, op=0x7f6a21046d00,
    comm=0x7f6a1c6b9480, module=0x7f6a1c6ba0e0) at ../../../../../ompi/mca/coll/tuned/coll_tuned_decision_fixed.c:64
#7  0x00007f6a20d46340 in PMPI_Allreduce (sendbuf=0x7fffa8e04f20, recvbuf=0x7fffa8e04f24, count=1, datatype=0x7f6a2103\
1a00, op=0x7f6a21046d00, comm=0x7f6a1c6b9480)
    at pallreduce.c:109
#8  0x00007f6a2108ca80 in ompi_allreduce_f (sendbuf=0x7fffa8e04f20 "", recvbuf=0x7fffa8e04f24 "\355\376", count=0x4019\
d0, datatype=0x4019d4, op=0x4019dc, comm=0x7fffa8e04f00,
    ierr=0x7fffa8e04f10) at pallreduce_f.c:85
#9  0x00000000004015d4 in idup_check () at comm_idup_mpifh.f90:109
#10 0x000000000040184a in main ()
#11 0x00007f6a1ffbed1d in __libc_start_main () from /lib64/libc.so.6
#12 0x0000000000400ef9 in _start ()

Rank 1
(gdb) where
#0  0x00007ff3f0f44ced in nanosleep () from /lib64/libc.so.6
#1  0x00007ff3f0f79e64 in usleep () from /lib64/libc.so.6
#2  0x00007ff3ef83d63c in native_fence (procs=0x0, nprocs=0) at ../../../../../opal/mca/pmix/native/pmix_native.c:498
#3  0x00007ff3f1c26f81 in ompi_mpi_finalize () at ../../ompi/runtime/ompi_mpi_finalize.c:232
#4  0x00007ff3f1c5023d in PMPI_Finalize () at pfinalize.c:46
#5  0x00007ff3f1f876dd in ompi_finalize_f (ierr=0x7fff9451c7d0) at pfinalize_f.c:69
#6  0x0000000000401814 in idup_check () at comm_idup_mpifh.f90:133
#7  0x000000000040184a in main ()
#8  0x00007ff3f0eb6d1d in __libc_start_main () from /lib64/libc.so.6
#9  0x0000000000400ef9 in _start ()
(gdb)

Rank 2
(gdb) where
#0  0x00007ff3f0f44ced in nanosleep () from /lib64/libc.so.6
#1  0x00007ff3f0f79e64 in usleep () from /lib64/libc.so.6
#2  0x00007ff3ef83d63c in native_fence (procs=0x0, nprocs=0) at ../../../../../opal/mca/pmix/native/pmix_native.c:498
#3  0x00007ff3f1c26f81 in ompi_mpi_finalize () at ../../ompi/runtime/ompi_mpi_finalize.c:232
#4  0x00007ff3f1c5023d in PMPI_Finalize () at pfinalize.c:46
#5  0x00007ff3f1f876dd in ompi_finalize_f (ierr=0x7fff9451c7d0) at pfinalize_f.c:69
#6  0x0000000000401814 in idup_check () at comm_idup_mpifh.f90:133
#7  0x000000000040184a in main ()
#8  0x00007ff3f0eb6d1d in __libc_start_main () from /lib64/libc.so.6
#9  0x0000000000400ef9 in _start ()
(gdb)

Rank 3
(gdb) where
#0  0x00007fc28864dced in nanosleep () from /lib64/libc.so.6
#1  0x00007fc288682e64 in usleep () from /lib64/libc.so.6
#2  0x00007fc286f4663c in native_fence (procs=0x0, nprocs=0) at ../../../../../opal/mca/pmix/native/pmix_native.c:498
#3  0x00007fc28932ff81 in ompi_mpi_finalize () at ../../ompi/runtime/ompi_mpi_finalize.c:232
#4  0x00007fc28935923d in PMPI_Finalize () at pfinalize.c:46
#5  0x00007fc2896906dd in ompi_finalize_f (ierr=0x7fff3b6b72b0) at pfinalize_f.c:69
#6  0x0000000000401814 in idup_check () at comm_idup_mpifh.f90:133
#7  0x000000000040184a in main ()
#8  0x00007fc2885bfd1d in __libc_start_main () from /lib64/libc.so.6
#9  0x0000000000400ef9 in _start ()
(gdb)

Rank 4
(gdb) where
#0  0x00007f5a78ab3537 in sched_yield () from /lib64/libc.so.6
#1  0x00007f5a783ea991 in opal_progress () at ../../opal/runtime/opal_progress.c:199
#2  0x00007f5a71237ba5 in opal_condition_wait (c=0x7f5a79a91040, m=0x7f5a79a90fc0) at ../../../../../opal/threads/cond\
ition.h:76
#3  0x00007f5a71237d89 in ompi_request_wait_completion (req=0x8e3980) at ../../../../../ompi/request/request.h:383
#4  0x00007f5a712399ce in mca_pml_ob1_send (buf=0x7fff53d48c50, count=2, datatype=0x7f5a79a75a00, dst=0, tag=0, sendmo\
de=MCA_PML_BASE_SEND_SYNCHRONOUS, comm=0xc4a120)
    at ../../../../../ompi/mca/pml/ob1/pml_ob1_isend.c:248
#5  0x00007f5a797bd9fb in PMPI_Ssend (buf=0x7fff53d48c50, count=2, type=0x7f5a79a75a00, dest=0, tag=0, comm=0xc4a120) \
at pssend.c:79
#6  0x00007f5a79ada560 in ompi_ssend_f (buf=0x7fff53d48c50 "\002", count=0x4019d8, datatype=0x4019d4, dest=0x4019a0, t\
ag=0x4019a0, comm=0x7fff53d48c44, ierr=0x7fff53d48c40)
    at pssend_f.c:78
#7  0x0000000000401572 in idup_check () at comm_idup_mpifh.f90:102
#8  0x000000000040184a in main ()
#9  0x00007f5a78a02d1d in __libc_start_main () from /lib64/libc.so.6
#10 0x0000000000400ef9 in _start ()
(gdb)

Rank 5
(gdb) where
#0  0x00007f0756398ced in nanosleep () from /lib64/libc.so.6
#1  0x00007f07563cde64 in usleep () from /lib64/libc.so.6
#2  0x00007f0754c9163c in native_fence (procs=0x0, nprocs=0) at ../../../../../opal/mca/pmix/native/pmix_native.c:498
#3  0x00007f075707af81 in ompi_mpi_finalize () at ../../ompi/runtime/ompi_mpi_finalize.c:232
#4  0x00007f07570a423d in PMPI_Finalize () at pfinalize.c:46
#5  0x00007f07573db6dd in ompi_finalize_f (ierr=0x7fff35697c50) at pfinalize_f.c:69
#6  0x0000000000401814 in idup_check () at comm_idup_mpifh.f90:133
#7  0x000000000040184a in main ()
#8  0x00007f075630ad1d in __libc_start_main () from /lib64/libc.so.6
#9  0x0000000000400ef9 in _start ()
(gdb)
```

**Comment by rolfv** [comment]
Note that this happens on both C and Fortran, but easier to get failure with Fortran tests.

**Comment by hppritcha** [comment]
@sjeaugey anyone at nvidia still observing this problem?  If not, I'd suggest closing.

**Comment by sjeaugey** [comment]
Indeed, I don't remember having seen this so it must have been fixed shortly after. Closing.
