### ISSUE TITLE
Undefined behaviour reported by clang UBSan in pml_ob1_hdr.h

### ISSUE THREAD

**Issue by cniethammer** [open-mpi/ompi#7958]
Playing around with sanitizers I get a warning about undefined behaviour in pml_ob1_hdr.h
Not sure of the exact origin and any effects.

I used 
Open MPI git master (30ba603c2c1766586b7105268f3d5f7986122dba)
Build with clang 10.0.0 and -fsanitize=address,undefined
Platform is Linux on an Intel single CPU system.

For the moment, running the mpi_test_suite, I see the behavior being triggered by MPI_Bcast with MPI_LONG or a derived datatype MPI_CONTIGUOUS(INT).
However, the tests from the mpi_test_suite all pass successfully and show no errors, data corruption, ...

Here the summary report from the sanitizer:

```
mpirun -n 4 ./mpi_test_suite -t Bcast
...
/ompi/ompi/mca/pml/ob1/pml_ob1_hdr.h:200:22: runtime error: null pointer passed as argument 2, which is declared to never be null
/usr/include/string.h:44:28: note: nonnull attribute specified here
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ompi/ompi/mca/pml/ob1/pml_ob1_hdr.h:200:22 in
```

**Comment by bosilca** [comment]
This would be legit if the size to memcpy is 0, but I don't really see how this could happen. I put a conditional breakpoint in that inlined function and I can't replicate your finding here (meaning the function is never called with a 0 length nor with a NULL pointer).

**Comment by cniethammer** [comment]
I extracted now this minimal reproducer:

```
#include <mpi.h>
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char *argv[]) {
    MPI_Init(&argc, &argv);
    MPI_Comm comm = MPI_COMM_WORLD;
    int comm_size = 1;
    int comm_rank = 0;
    MPI_Comm_size(comm, &comm_size);
    MPI_Comm_rank(comm, &comm_rank);

#define TYPES_NUM_REPEAT 7
#define OVERHEAD 8

    MPI_Datatype datatype;
    MPI_Type_contiguous(TYPES_NUM_REPEAT, MPI_INT, &datatype);
    MPI_Type_commit(&datatype);

    int count = 1000 + OVERHEAD;
    void *buffer = malloc(count * TYPES_NUM_REPEAT * sizeof(int));
    int root = 0;

    MPI_Bcast(buffer, count, datatype, root, MPI_COMM_WORLD);

    free(buffer);
    MPI_Finalize();
    return 0;
}
```

And here a backtrace to the point, when I hit a watchpoint for the assignment of the nullptr:

```
(gdb) bt
#0  mca_pml_ob1_send (buf=0x62c000003920, count=504, datatype=0x6130000042c0, dst=1, tag=-17, sendmode=MCA_PML_BASE_SEND_STANDARD, comm=0x7ffff7faf340 <ompi_mpi_comm_world>) at /home/christoph/work/codes/ompi/ompi/ompi/mca/pml/ob1/pml_ob1_isend.c:292
#1  0x00007ffff7951e44 in ompi_coll_base_bcast_intra_split_bintree (buffer=0x62c000000200, count=1008, datatype=0x6130000042c0, root=0, comm=0x7ffff7faf340 <ompi_mpi_comm_world>, module=0x61a000015c80, segsize=1024) at /home/christoph/work/codes/ompi/ompi/ompi/mca/coll/base/coll_base_bcast.c:570
#2  0x00007fffeea0de28 in ompi_coll_tuned_bcast_intra_dec_fixed (buff=0x62c000000200, count=1008, datatype=0x6130000042c0, root=0, comm=0x7ffff7faf340 <ompi_mpi_comm_world>, module=0x61a000015c80) at /home/christoph/work/codes/ompi/ompi/ompi/mca/coll/tuned/coll_tuned_decision_fixed.c:276
#3  0x00007ffff7590bb1 in PMPI_Bcast (buffer=0x62c000000200, count=1008, datatype=0x6130000042c0, root=0, comm=0x7ffff7faf340 <ompi_mpi_comm_world>) at /home/christoph/work/codes/ompi/ompi/ompi/mpi/c/profile/pbcast.c:115
#4  0x000055555564b9e6 in main (argc=1, argv=0x7fffffffd708) at Bcast_test.c:28
(gdb) print *mca_pml_ob1_sendreq->req_rdma
$3 = {
  bml_btl = 0x60800000f620,
  btl_reg = 0x0,
  length = 14112
}
```

**Comment by bosilca** [comment]
what would be the value of bml_btl->btl->btl_registration_handle_size in mca_pml_ob1_recv_request_put_frag ?

**Comment by cniethammer** [comment]
I do not see mca_pml_ob1_recv_request_put_frag being called at all.

I dived deeper for the origin of the nullptr.
Running with 2 processes I see a change in behaviour: In the Broadcast algorithm I see 14 requests of 36 elements and then a final  (seqn=15) one with 504 elements, which triggers a different behaviour due to a size larger than the eager_limit (=4040 ~ page size for sm) ending in a call to `mca_pml_ob1_rdma_btls`, which sets a nullptr consumed then followed by `mca_pml_ob1_send_request_start_rdma` resulting in the undefined behaviour.
```
(gdb) bt
#0  mca_pml_ob1_rdma_btls (bml_endpoint=0x613000004100, base=0x62c000003920 "", size=14112, rdma_btls=0x6210000150d8) at /home/christoph/work/codes/ompi/ompi/ompi/mca/pml/ob1/pml_ob1_rdma.c:99
#1  0x00007fffeef26285 in mca_pml_ob1_send_request_start_btl (sendreq=0x621000014d80, bml_btl=0x60800000f520) at /home/christoph/work/codes/ompi/ompi/ompi/mca/pml/ob1/pml_ob1_sendreq.h:429
#2  0x00007fffeef160e6 in mca_pml_ob1_send_request_start_seq (sendreq=0x621000014d80, endpoint=0x613000004100, seqn=15) at /home/christoph/work/codes/ompi/ompi/ompi/mca/pml/ob1/pml_ob1_sendreq.h:475
#3  0x00007fffeef19e10 in mca_pml_ob1_send (buf=0x62c000003920, count=504, datatype=0x6130000042c0, dst=1, tag=-17, sendmode=MCA_PML_BASE_SEND_STANDARD, comm=0x7ffff7faf340 <ompi_mpi_comm_world>) at /home/christoph/work/codes/ompi/ompi/ompi/mca/pml/ob1/pml_ob1_isend.c:278
#4  0x00007ffff7951e44 in ompi_coll_base_bcast_intra_split_bintree (buffer=0x62c000000200, count=1008, datatype=0x6130000042c0, root=0, comm=0x7ffff7faf340 <ompi_mpi_comm_world>, module=0x61a000015c80, segsize=1024) at /home/christoph/work/codes/ompi/ompi/ompi/mca/coll/base/coll_base_bcast.c:570
#5  0x00007fffeea0de28 in ompi_coll_tuned_bcast_intra_dec_fixed (buff=0x62c000000200, count=1008, datatype=0x6130000042c0, root=0, comm=0x7ffff7faf340 <ompi_mpi_comm_world>, module=0x61a000015c80) at /home/christoph/work/codes/ompi/ompi/ompi/mca/coll/tuned/coll_tuned_decision_fixed.c:276
#6  0x00007ffff7590bb1 in PMPI_Bcast (buffer=0x62c000000200, count=1008, datatype=0x6130000042c0, root=0, comm=0x7ffff7faf340 <ompi_mpi_comm_world>) at /home/christoph/work/codes/ompi/ompi/ompi/mpi/c/profile/pbcast.c:115
#7  0x000055555564b9e6 in main (argc=1, argv=0x7fffffffd708) at Bcast_test.c:28
```
