### ISSUE TITLE
mpi4py: Regression in MPI_Sendrecv_replace

### ISSUE THREAD

**Issue by dalcinl** [open-mpi/ompi#8907]
While I'm still waiting for Open MPI to pass the full mpi4py testsuite and hand things over to @jsquyres, a new regression showed up in `MPI_Sendrecv_replace`:

https://github.com/mpi4py/mpi4py-testing/runs/2476248326?check_suite_focus=true

The reproducer is fairly trivial:

```python
from mpi4py import MPI
import array

comm = MPI.COMM_WORLD
size = comm.Get_size()
rank = comm.Get_rank()
dest = (rank + 1) % size
source = (rank - 1) % size
buf = array.array('i', [rank])
comm.Sendrecv_replace(buf, dest, 0, source, 0)
assert buf[0] == source
```

```
$ mpiexec -n 1 python test.py 
Traceback (most recent call last):
  File "/tmp/test.py", line 10, in <module>
    comm.Sendrecv_replace(buf, dest, 0, source, 0)
  File "mpi4py/MPI/Comm.pyx", line 360, in mpi4py.MPI.Comm.Sendrecv_replace
mpi4py.MPI.Exception: MPI_ERR_BUFFER: invalid buffer pointer
```

**Comment by awlauria** [comment]
PR's merged, closing this. @dalcinl if you see this continue please re-open. Thanks!
