### ISSUE TITLE
Option --preload-files causes segmentation fault

### ISSUE THREAD

**Issue by albandil** [open-mpi/ompi#9976]
I am using self-compiled Open MPI from the 5.0.x development branch on a standard desktop system with openSUSE Tumbleweed. I have up-to-date Git submodules and have executed autogen.pl before compilation. I compiled the package by
```shell
$ ../../configure --prefix=/dev/shm/openmpi-5.0.x --enable-debug
```

When I attempt to use the option `--preload-files`, I get segmentation fault:
```shell
$ mpiexec -n 1 hostname
yunipher

$ mpiexec -n 1 --preload-files xxx hostname
Segmentation fault (core dumped)

$ gdb --args mpiexec -n 1 --preload-files xxx hostname
(...)
Thread 1 "prterun" received signal SIGSEGV, Segmentation fault.
(...)
#0  __strlen_evex () at ../sysdeps/x86_64/multiarch/strlen-evex.S:77
#1  0x00007ffff76d7b03 in __GI___strdup (s=0x1 <error: Cannot access memory at address 0x1>) at strdup.c:41
#2  0x00007ffff7e33bdc in prte_attr_load (kv=0x613280, data=0x1, type=3) at ../../../../../../3rd-party/prrte/src/util/attr.c:578
#3  0x00007ffff7e32a67 in prte_set_attribute (attributes=0x4c0eb0, key=8, local=false, data=0x1, type=3) at ../../../../../../3rd-party/prrte/src/util/attr.c:91
#4  0x00007ffff7dfea6b in interim (sd=-1, args=4, cbdata=0x61c390) at ../../../../../3rd-party/prrte/src/prted/pmix/pmix_server_dyn.c:287
#5  0x00007ffff79b5f88 in event_process_active_single_queue (base=base@entry=0x430520, activeq=0x430a30, max_to_process=max_to_process@entry=2147483647, endtime=endtime@entry=0x0) at /usr/src/debug/libevent-2.1.12-2.6.x86_64/event.c:1706
#6  0x00007ffff79b7d4f in event_process_active (base=0x430520) at /usr/src/debug/libevent-2.1.12-2.6.x86_64/event.c:1798
#7  event_base_loop (base=0x430520, flags=1) at /usr/src/debug/libevent-2.1.12-2.6.x86_64/event.c:2040
#8  0x00007ffff7de9ef3 in prte (argc=6, argv=0x7fffffffda98) at ../../../../../3rd-party/prrte/src/prted/prte.c:1221
#9  0x0000000000401156 in main (argc=6, argv=0x7fffffffda98) at ../../../../../../../3rd-party/prrte/src/tools/prte/main.c:13
```
The presence or absence of the file "xxx" does not affect the behaviour.

**Comment by rhc54** [comment]
Fixed in https://github.com/openpmix/prrte/pull/1199 - unsure when it will be updated in OMPI
